Repository rudderlabs/rudderstack-docs, pull requests merged in 2021-12, with the labels that each got.

#284 Intercom v2 doc fixes
  assets/cloud-extract-sources/intercomv2-1.png
  assets/cloud-extract-sources/intercomv2-2.png
  assets/cloud-extract-sources/intercomv2-3.png
  assets/cloud-extract-sources/intercomv2-4.png
  assets/cloud-extract-sources/intercomv2-5.png
  assets/cloud-extract-sources/intercomv2-6.png
  assets/cloud-extract-sources/intercomv2-7.png
  assets/cloud-extract-sources/singer-intercom-2.png
  assets/cloud-extract-sources/singer-intercom-3.png
  assets/cloud-extract-sources/singer-intercom-4.png
  assets/cloud-extract-sources/singer-intercom-5.png
  assets/cloud-extract-sources/singer-intercom-6.png
  assets/cloud-extract-sources/singer-intercom-8.png
  cloud-extract-sources/intercom-v2.mdx
Labels: Ready for review

#290 VDM doc update
  warehouse-actions/visual-data-mapper.mdx
Labels: Good to go!

#289 AppsFlyer documentation update
  assets/event-stream-destinations/appsflyer-connection-settings-1.png
  assets/event-stream-destinations/appsflyer-connection-settings-2.png
  assets/event-stream-destinations/appsflyer-connection-settings.png
  destinations/attribution/appsflyer.mdx
Labels: Good to go!

#291 Cordova docs
  destinations/analytics/adobe-analytics/setting-up-adobe-analytics-in-rudderstack.mdx
  destinations/analytics/firebase.mdx
  destinations/continuous-integration/appcenter.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
Labels: Ready for review

#250 Test API formatting fixes and sidebar references
  assets/test-api-1.png
  assets/test-api-2.png
  postNavList.js
  rudderstack-api/test-api.mdx
  sidebar.js
Labels: Good to go!

#292 Post Affiliate Pro documentation
  assets/event-stream-destinations/pap-connection-settings-1.png
  assets/event-stream-destinations/pap-connection-settings-2.png
  assets/event-stream-destinations/pap-connection-settings-3.png
  assets/event-stream-destinations/pap-cookie-domain.png
  assets/event-stream-destinations/pap-mergeproduct-false.png
  assets/event-stream-destinations/pap-mergeproduct-true.png
  assets/event-stream-destinations/pap-tracking-url.png
  destinations/marketing/post-affiliate-pro.mdx
Labels: Ready for review

#271 Event Stream sources revamp
  assets/event-stream-sources/amp-analytics-1.png
  assets/event-stream-sources/android-sdk-1.png
  assets/event-stream-sources/cordova-sdk-1.png
  assets/event-stream-sources/dot-net-1.png
  assets/event-stream-sources/flutter-sdk-1.png
  assets/event-stream-sources/go-sdk-1.png
  assets/event-stream-sources/ios-sdk-1.png
  assets/event-stream-sources/java-sdk-1.png
  assets/event-stream-sources/node-sdk-1.png
  assets/event-stream-sources/php-sdk-1.png
  assets/event-stream-sources/python-sdk-1.png
  assets/event-stream-sources/react-native-1.png
  assets/event-stream-sources/ruby-sdk-1.png
  assets/event-stream-sources/unity-sdk-1.png
  assets/event-stream-sources/unity-sdk-2.png
  assets/event-stream-sources/unity-sdk-3.png
  assets/event-stream-sources/unity-sdk-4.png
  stream-sources/rudderstack-sdk-integration-guides/amp-analytics.mdx
  stream-sources/rudderstack-sdk-integration-guides/dotnet.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-amp-analytics.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-dotnet-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-go-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-java-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-node-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-php-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-python-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-ruby-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-rust-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-unity-sdk.mdx
Labels: Ready for review

#293 Update SDK sources file paths
  postNavList.js
  sidebar.js
Labels: Good to go!

#294 Implemented Cordova AppsFlyer docs
  destinations/attribution/appsflyer.mdx
  destinations/continuous-integration/appcenter.mdx
Labels: Do not merge, Ready for review

#295 Google Optimize documentation
  assets/event-stream-destinations/google-optimize-connection-settings-1.png
  assets/event-stream-destinations/google-optimize-container-id.png
  assets/event-stream-destinations/google-optimize-ga-tracking-id.png
  destinations/testing-and-personalization/google-optimize.mdx
Labels: Good to go!

#301 GA documentation update
  destinations/analytics/google-analytics-ga.mdx
Labels: Ready for review

#299 Test API updates
  rudderstack-api/test-api.mdx
Labels: Ready for review

#303 Salesforce Cloud Extract Documentation Updates
  assets/cloud-extract-sources/salesforce-1.png
  assets/cloud-extract-sources/salesforce-2.png
  assets/cloud-extract-sources/salesforce-3.png
  assets/cloud-extract-sources/salesforce-4.png
  assets/cloud-extract-sources/salesforce-5.png
  assets/cloud-extract-sources/salesforce-6.png
  cloud-extract-sources/salesforce/index.mdx
Labels: Ready for review

#304 Flutter v1.2 Documentation Update
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/flutter-v1.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/index.mdx
Labels: Good to go!

#302 Chargebee Documentation
  assets/cloud-extract-sources/chargebee-1.png
  assets/cloud-extract-sources/chargebee-2.png
  assets/cloud-extract-sources/chargebee-3.png
  assets/cloud-extract-sources/chargebee-4.png
  assets/cloud-extract-sources/chargebee-5.png
  assets/cloud-extract-sources/chargebee-6.png
  cloud-extract-sources/chargebee.mdx
Labels: Good to go!

#285 Event Stream cloud sources revamp
  assets/event-stream-sources/appcenter-1.png
  assets/event-stream-sources/appcenter-2.png
  assets/event-stream-sources/appcenter-3.png
  assets/event-stream-sources/appcenter-4.png
  assets/event-stream-sources/appsflyer-1.png
  assets/event-stream-sources/appsflyer-2.png
  assets/event-stream-sources/appsflyer-3.png
  assets/event-stream-sources/appsflyer-4.png
  assets/event-stream-sources/auth0-1.png
  assets/event-stream-sources/auth0-2.png
  assets/event-stream-sources/auth0-3.png
  assets/event-stream-sources/auth0-4.png
  assets/event-stream-sources/auth0-5.png
  assets/event-stream-sources/auth0-6.png
  assets/event-stream-sources/customerio-1.png
  assets/event-stream-sources/customerio-2.png
  assets/event-stream-sources/customerio-3.png
  assets/event-stream-sources/customerio-4.png
  assets/event-stream-sources/customerio-5.png
  assets/event-stream-sources/extole-1.png
  assets/event-stream-sources/extole-2.png
  assets/event-stream-sources/extole-3.png
  assets/event-stream-sources/extole-4.png
  assets/event-stream-sources/looker-1.png
  assets/event-stream-sources/looker-2.png
  assets/event-stream-sources/looker-3.png
  assets/event-stream-sources/looker-4.png
  assets/event-stream-sources/posthog-1.png
  assets/event-stream-sources/posthog-2.png
  assets/event-stream-sources/posthog-3.png
  assets/event-stream-sources/posthog-4.png
  assets/event-stream-sources/segment-1.png
  assets/event-stream-sources/segment-2.png
  assets/event-stream-sources/segment-3.png
  assets/event-stream-sources/segment-4.png
  assets/event-stream-sources/webhook-1.png
  assets/event-stream-sources/webhook-2.png
  assets/event-stream-sources/webhook-3.png
  assets/event-stream-sources/webhook-4.png
  stream-sources/appcenter.mdx
  stream-sources/appsflyer.mdx
  stream-sources/auth0.mdx
  stream-sources/customerio.mdx
  stream-sources/extole.mdx
  stream-sources/looker.mdx
  stream-sources/posthog.mdx
  stream-sources/segment.mdx
  stream-sources/webhook-source.mdx
Labels: Ready for review

#300 Klaviyo Documentation Update
  assets/event-stream-destinations/klaviyo-connection-settings.png
  destinations/marketing/klaviyo.mdx
Labels: Do not merge, Ready for review

#306 Secure Cookie flag in JS SDK
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
Labels: Good to go!

#305 Facebook Pixel Documentation Updates
  destinations/advertising/fb-pixel.mdx
Labels: Good to go!

#307 Google Ads Documentation Update
  assets/event-stream-destinations/googleads-connection-settings.png
  destinations/advertising/google-ads.mdx
Labels: Review in progress

#296 Delta Lake destination docs
  assets/dw-integrations/delta-lake-1.png
  assets/dw-integrations/delta-lake-10.png
  assets/dw-integrations/delta-lake-11.png
  assets/dw-integrations/delta-lake-12.png
  assets/dw-integrations/delta-lake-2.png
  assets/dw-integrations/delta-lake-3.png
  assets/dw-integrations/delta-lake-4.png
  assets/dw-integrations/delta-lake-5.png
  assets/dw-integrations/delta-lake-6.png
  assets/dw-integrations/delta-lake-7.png
  assets/dw-integrations/delta-lake-8.png
  assets/dw-integrations/delta-lake-9.png
  assets/dw-integrations/delta-lake-connection-settings-1.png
  assets/dw-integrations/delta-lake-connection-settings-2.png
  assets/dw-integrations/delta-lake-connection-settings-3.png
  assets/dw-integrations/delta-lake-connection-settings-4.png
  assets/dw-integrations/delta-lake-connection-settings-5.png
  data-warehouse-integrations/delta-lake.mdx
Labels: Good to go!

#313 BigQuery Stream Updated documentation
  assets/event-stream-destinations/bqstream-1.png
  assets/event-stream-destinations/bqstream-2.png
  assets/event-stream-destinations/bqstream-3.png
  assets/event-stream-destinations/bqstream-4.png
  assets/event-stream-destinations/bqstream-5.png
  assets/event-stream-destinations/bqstream-6.png
  assets/event-stream-destinations/bqstream-service-account-1.png
  assets/event-stream-destinations/bqstream-service-account-2.png
  assets/event-stream-destinations/bqstream-service-account-3.png
  destinations/streaming-platforms/bigquery-stream.mdx
  destinations/streaming-platforms/index.mdx
Labels: Good to go!

#312 Added documentation for background run time on iOS
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
Labels: Review in progress

#309 Library supported syntax
  transformations/index.mdx
Labels: Good to go!

#308 Delta Lake Doc Update
  data-warehouse-integrations/delta-lake.mdx
Labels: Review in progress

#311 Documentation changes for iOS & watchOS
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/watchOS.mdx
Labels: Good to go!

#315 iOS SDK Documentation updates
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
Labels: Review in progress

#314 Intercom: creating anonymousId as secondary userId as per user's choice
  assets/event-stream-destinations/intercom-connection-settings.png
  destinations/business-messaging/intercom.mdx
Labels: Review in progress

#317 VDM Doc Update
  warehouse-actions/visual-data-mapper.mdx
Labels: Ready for review
