Repository rudderlabs/rudderstack-docs, pull requests merged in 2021-09, with the labels that each got.

#171 initial draft for marketo lead import
  .gitbook/assets/marketo_lead_import.png
  SUMMARY.md
  destinations/marketing/marketo_lead_import.md
Labels: Good to Go!

#172 add event_id info in ometria
  destinations/marketing/ometria.md
Labels: Enhancement

#170 Qualtrics Android and iOS device mode docs - Ready from Dev
  destinations/marketing/qualtrics-website-feedback.md
Labels: Ready for Review

#176 Updated Version for iOS Branch Device Mode
  destinations/attribution/branchio.md
Labels: Ready for Review

#180 Added Docs for GDPR Support across Native Mobile SDK's
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/README.md
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk.md
Labels: Ready for Review

#184 Updated importing statement for Qualtrics docs
  destinations/marketing/qualtrics.md
Labels: Ready for Review

#175 orders event update
  destinations/marketing/ometria.md
Labels: Enhancement, Good to Go!

#169 Branch - revamp update event-mapping
  destinations/attribution/branchio.md
Labels: Good to Go!

#162 Update rudderstack-node-sdk.md
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-node-sdk.md
Labels: Ready for Review

#182 JS SDK clarification re: IP address
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/README.md
Labels: Good to Go!

#185 Algolia destination
  .gitbook/assets/Algolia.png
  SUMMARY.md
  destinations/testing-and-personalization/algolia.md
Labels: Ready for Review

#188 Consolidate RudderStack Cloud questions
  faqs.md
Labels: Ready for Review

#181 Added Docs for GDPR Support across Hybrid Mobile SDK's
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk.md
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.md
Labels: Ready for Review

#186 profitwell Integration
  .gitbook/assets/ProfitWell-1.png
  .gitbook/assets/ProfitWell-2.png
  SUMMARY.md
  destinations/analytics/profitwell.md
Labels: Ready for Review

#190 Fixed Follow Us link titles
  README.md
Labels: Ready for Review

#192 Remove asterisks
  README.md
Labels: Ready for Review

#196 Update glossary.md
  glossary.md
Labels: Ready for Review

#195 ProfitWell device-mode Integration
  SUMMARY.md
  destinations/analytics/profitwell/README.md
  destinations/analytics/profitwell/profitwell-cloud-mode.md
  destinations/analytics/profitwell/profitwell-web-device-mode.md
Labels: Ready for Review

#200 Updated AppsFlyer Docs on Retreiving AppsFlyer Id on Android and RN
  destinations/attribution/appsflyer.md
Labels: Ready for Review

#198 Update user permissions to include detailed steps
  warehouse-actions/snowflake.md
Labels: Ready for Review

#193 Change code whitespace
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/README.md
Labels: Good to Go!

#194 Documentation for Cordova SDK
  .gitbook/assets/Cordova_Source.png
  SUMMARY.md
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
Labels: Ready for Review

#211 Sentry integration Docs
  .gitbook/assets/sentry.png
  SUMMARY.md
  destinations/error-reporting/sentry.md
Labels: Ready for Review

#201 User permissions for setting up Warehouse Actions sources
  warehouse-actions/amazon-redshift.md
  warehouse-actions/google-bigquery.md
  warehouse-actions/postgresql.md
Labels: Ready for Review

#202 Opt-out doc for Mobile-SDK's
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/README.md
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk.md
Labels: Ready for Review

#216 Add SKAdNetwork FAQ
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk.md
Labels: Ready for Review

#219 GDPR FAQs for Android / iOS SDKs
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/README.md
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk.md
Labels: Ready for Review

#207 Update home
  README.md
Labels: Ready for Review

#218 Personalize doc edits
  .gitbook/assets/putEvents.png
  .gitbook/assets/putItems.png
  destinations/analytics/aws-personalize.md
Labels: Review in progress

#221 QM documentation
  .gitbook/assets/quantum-metric.png
  SUMMARY.md
  destinations/analytics/quantummetric.md
Labels: Good to Go!
