Repository rudderlabs/rudderstack-docs, pull requests merged in 2021-11, with the labels that each got.

#246 Firebase content changes
  assets/firebase-connection-settings.png
  destinations/analytics/firebase.mdx
Labels: Good to Go!

#248 Highlighted tvOS Support in iOS SDK Docs
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk.mdx
Labels: Good to Go!

#245 Firebase docs
  assets/firebase-connection-settings.png
  destinations/analytics/firebase.mdx
Labels: Good to Go!

#251 Update VDM doc to specify Customer.io support
  assets/vdm-1.png
  assets/vdm-2.png
  assets/vdm-3.png
  assets/vdm-4.png
  assets/vdm-5.png
  assets/vdm-6.png
  assets/vdm-7.png
  warehouse-actions/visual-data-mapper.mdx
Labels: Good to Go!

#249 JavaScript SDK Documentation Revamp
  assets/js-sdk-version-migration.png
  assets/requireintegration-call-flow.png
  assets/sample-page-call.png
  assets/sample-track-call.png
  postNavList.js
  sidebar.js
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/detecting-adblocked-pages.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/javascript-sdk-enhancements.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/js-sdk-faqs.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/querystring-api.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/quick-start-guide.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/version-migration-guide.mdx
Labels: Ready for Review

#235 Cordova SDK GDPR Update
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
Labels: Good to Go!

#254 Added Docs for Amplitude and Braze for RN Device Mode
  destinations/analytics/amplitude.mdx
  destinations/marketing/braze.mdx
Labels: Good to Go!

#253 Documentation fixes
  destinations/analytics/firebase.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/quick-start-guide.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/version-migration-guide.mdx
  warehouse-actions/visual-data-mapper.mdx
Labels: Ready for Review

#255 Updated code snippet to fix callback position
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/quick-start-guide.mdx
Labels: Ready for Review

#257 JS SDK Version Migration guide updates
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/version-migration-guide.mdx
Labels: Ready for Review

#256 Mobile SDK fixes and enhancements
  postNavList.js
  sidebar.js
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/tvOS.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/version-migration-guide.mdx
Labels: Ready for Review

#259 Enterprise plan badges
  data-governance/rudderstack-data-governance-api.mdx
  data-warehouse-integrations/identity-resolution-in-rudderstack.mdx
  rudderstack-api/user-suppression.mdx
  user-guides/administrators-guide/okta-sso.mdx
  user-guides/administrators-guide/onelogin-sso.mdx
Labels: Good to Go!

#261 Hotjar - fix: add identify info
  assets/Hotjar-1.png
  assets/image (42).png
  destinations/analytics/hotjar.mdx
Labels: Good to Go!

#263 GCS Data Lake and Azure Data Lake documentation
  assets/dw-integrations/azure-datalake-1.png
  assets/dw-integrations/gcs-datalake-1.png
  assets/dw-integrations/gcs-datalake-2.png
  assets/dw-integrations/gcs-datalake-3.png
  assets/dw-integrations/gcs-datalake-4.png
  assets/dw-integrations/gcs-datalake-5.png
  assets/dw-integrations/gcs-datalake-6.png
  assets/dw-integrations/gcs-datalake-7.png
  assets/dw-integrations/gcs-datalake-8.png
  data-warehouse-integrations/azure-datalake.mdx
  data-warehouse-integrations/gcs-datalake.mdx
  postNavList.js
  sidebar.js
Labels: Good to Go!

#264 FullStory mobile device mode docs
  assets/event-stream-destinations/fullstory-connection-settings.png
  assets/event-stream-destinations/fullstory-devicemode-ios.png
  destinations/analytics/fullstory.mdx
Labels: Good to go!

#266 FullStory code hotfix
  destinations/analytics/fullstory.mdx
Labels: Ready for review

#269 Fix typo in alerting.mdx
  user-guides/administrators-guide/alerting.mdx
Labels: Good to go!

#265 Updated doc structure
  postNavList.js
  sidebar.js
Labels: Ready for review

#272 Android SDK updates
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
Labels: Ready for review

#270 Added Documentation for using Rudder Android SDK version on Api level less than 20
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
Labels: Ready for review

#260 Intercom v2 documentation
  assets/cloud-extract-sources/singer-intercom-1.png
  assets/cloud-extract-sources/singer-intercom-2.png
  assets/cloud-extract-sources/singer-intercom-3.png
  assets/cloud-extract-sources/singer-intercom-4.png
  assets/cloud-extract-sources/singer-intercom-5.png
  assets/cloud-extract-sources/singer-intercom-6.png
  assets/cloud-extract-sources/singer-intercom-7.png
  assets/cloud-extract-sources/singer-intercom-8.png
  cloud-extract-sources/airbyte-sources/index.mdx
  cloud-extract-sources/airbyte-sources/intercom-v2.mdx
  postNavList.js
  sidebar.js
Labels: Good to go!

#276 Intercom v2 structure fix
  cloud-extract-sources/airbyte-sources/index.mdx
  cloud-extract-sources/intercom-v2.mdx
  postNavList.js
  sidebar.js
Labels: Ready for review

#273 Update how-to-filter-selective-destinations.mdx
  user-guides/how-to-guides/how-to-filter-selective-destinations.mdx
Labels: Good to go!

#252 Sendgrid PR migration
  assets/event-stream-destinations/sendgrid-connection-settings-1.png
  assets/event-stream-destinations/sendgrid-connection-settings-2.png
  assets/event-stream-destinations/sendgrid-connection-settings-3.png
  assets/event-stream-destinations/sendgrid-connection-settings-4.png
  destinations/marketing/sendgrid.mdx
Labels: Good to go!

#278 Update identify.mdx
  rudderstack-api/api-specification/rudderstack-spec/identify.mdx
Labels: Good to go!

#280 Update page.mdx
  rudderstack-api/api-specification/rudderstack-spec/page.mdx
Labels: Good to go!

#281 Update track.mdx
  rudderstack-api/api-specification/rudderstack-spec/track.mdx
Labels: Good to go!

#282 Update group.mdx
  rudderstack-api/api-specification/rudderstack-spec/group.mdx
Labels: Good to go!

#283 Update alias.mdx
  rudderstack-api/api-specification/rudderstack-spec/alias.mdx
Labels: Good to go!

#279 Updated Device Token docs of Mobile SDK's
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.mdx
Labels: Good to go!

#287 Minor doc fixes - devicetoken
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.mdx
Labels: Ready for review
