Repository rudderlabs/rudderstack-docs, pull requests merged in 2022-05, with the labels that each got.

#537 Google Ads Cloud Extract source documentation
  assets/cloud-extract-sources/g-ads-connection-settings-1.png
  assets/cloud-extract-sources/g-ads-connection-settings-2.png
  assets/cloud-extract-sources/g-ads-connection-settings-3.png
  assets/cloud-extract-sources/g-ads-connection-settings-4.png
  assets/cloud-extract-sources/g-ads-connection-settings-5.png
  assets/cloud-extract-sources/g-ads-customer-id.png
  cloud-extract-sources/google-adwords.mdx
  cloud-extract-sources/sendgrid.mdx
Labels: Good to go!

#548 GA4 formatting fix
  destinations/analytics/google-analytics-4/google-analytics-4-cloud-mode.mdx
  destinations/analytics/google-analytics-4/index.mdx
  destinations/analytics/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
Labels: Ready for review

#549 Added documentation for first_purchase event in Appsflyer destination
  destinations/attribution/appsflyer.mdx
Labels: Good to go!

#525 Slack doc revamp
  assets/event-stream-destinations/choose-channel-slack.png
  assets/event-stream-destinations/slack-settings.png
  assets/event-stream-destinations/slack-settings2.png
  assets/event-stream-destinations/slack-settings3.png
  assets/event-stream-destinations/slack-settings4.png
  assets/event-stream-destinations/traits-slack.png
  assets/event-stream-destinations/webhook-url-slack.png
  destinations/business-messaging/slack.mdx
Labels: Good to go!

#547 Iterable doc
  assets/event-stream-sources/iterable-1.png
  assets/event-stream-sources/iterable-2.png
  assets/event-stream-sources/webhook-url-iterable.png
  stream-sources/iterable.mdx
Labels: Good to go!

#554 NetSuite Documentation Update
  assets/cloud-extract-sources/netsuite-settings-1.png
  assets/cloud-extract-sources/netsuite-settings-10.png
  assets/cloud-extract-sources/netsuite-settings-11.png
  assets/cloud-extract-sources/netsuite-settings-12.png
  assets/cloud-extract-sources/netsuite-settings-13.png
  assets/cloud-extract-sources/netsuite-settings-14.png
  assets/cloud-extract-sources/netsuite-settings-15.png
  assets/cloud-extract-sources/netsuite-settings-16.png
  assets/cloud-extract-sources/netsuite-settings-17.png
  assets/cloud-extract-sources/netsuite-settings-2.png
  assets/cloud-extract-sources/netsuite-settings-3.png
  assets/cloud-extract-sources/netsuite-settings-4.png
  assets/cloud-extract-sources/netsuite-settings-5.png
  assets/cloud-extract-sources/netsuite-settings-6.png
  assets/cloud-extract-sources/netsuite-settings-7.png
  assets/cloud-extract-sources/netsuite-settings-8.png
  assets/cloud-extract-sources/netsuite-settings-9.png
  cloud-extract-sources/netsuite.mdx
Labels: Ready for review

#551 feat(data plane setup): send events script out of the box, bump versions
  rudderstack-open-source/control-plane-lite.mdx
  rudderstack-open-source/installing-and-setting-up-rudderstack/developer-machine-setup.mdx
  rudderstack-open-source/installing-and-setting-up-rudderstack/sending-test-events.mdx
Labels: Good to go!

#556 Added FAQ for sync lag
  assets/warehouse-destinations/exclusion-window.png
  assets/warehouse-destinations/read-write-database.png
  assets/warehouse-destinations/sync-frequency.png
  data-warehouse-integrations/warehouse-faqs.mdx
Labels: Ready for review

#555 Regulation API documentation updates
  rudderstack-api/data-regulation-api.mdx
Labels: Good to go!

#553 Added cookie
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/data-storage-cookies.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
Labels: Good to go!

#557 Chargebee doc revamp
  assets/cloud-extract-sources/chargebee-1.png
  assets/cloud-extract-sources/chargebee-2.png
  cloud-extract-sources/chargebee.mdx
  cloud-extract-sources/sendgrid.mdx
Labels: Good to go!

#558 Splitio Revamp and eventTypeId constraints
  assets/event-stream-destinations/splitio-api-key.png
  assets/event-stream-destinations/splitio-connection-settings.png
  assets/event-stream-destinations/splitio-environment.png
  destinations/testing-and-personalization/splitio.mdx
Labels: Good to go!

#550 Stripe Documentation Update
  assets/cloud-extract-sources/stripe-api-version.png
  assets/cloud-extract-sources/stripe-data-import-settings.png
  assets/cloud-extract-sources/stripe-source-settings.png
  cloud-extract-sources/stripe.mdx
Labels: Good to go!

#559 ActiveCampaign doc revamp
  assets/cloud-extract-sources/activecampaign-connection-settings-2.png
  assets/cloud-extract-sources/activecampaign-connection-settings-3.png
  assets/cloud-extract-sources/activecampaign-connection-settings-4.png
  assets/cloud-extract-sources/activecampaign-connection-settings.png
  cloud-extract-sources/activecampaign.mdx
Labels: Good to go!

#566 URL Fixes
  rudderstack-cloud/live-events.mdx
  stream-sources/index.mdx
Labels: Good to go!

#571 Okta SSO documentation updates
  user-guides/administrators-guide/okta-sso.mdx
Labels: Good to go!

#569 Add aliases to mdx frontmatter for Algolia testing
  reverse-etl/google-bigquery.mdx
  stream-sources/customerio.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
Labels: Good to go!

#563 Alias information in Warehouse Schema documentation
  data-warehouse-integrations/warehouse-schemas.mdx
Labels: Good to go!

#568 RS Dashboard: Get started option
  assets/rs-cloud/get-started.png
  get-started/index.mdx
  rudderstack-cloud/dashboard-overview.mdx
Labels: Ready for review

#572 Personal Access Token documentation updates
  assets/rudderstack-api/new-personal-access-token.png
  assets/rudderstack-api/personal-access-tokens-1.png
  assets/rudderstack-api/personal-access-tokens-2.png
  assets/rudderstack-api/personal-access-tokens-3.png
  data-governance/tracking-plans/index.mdx
  faqs.mdx
  postNavList.js
  reverse-etl/features/airflow-provider.mdx
  rudderstack-api/data-regulation-api.mdx
  rudderstack-api/personal-access-tokens.mdx
  rudderstack-api/test-api.mdx
  rudderstack-cloud/dashboard-overview.mdx
  sidebar.js
  sidebar.yml
  transformations/rudderstack-transformation-api.mdx
Labels: Good to go!

#573 AdRoll Documentation
  assets/event-stream-destinations/adroll-connection-settings.png
  assets/event-stream-destinations/adroll-details.png
  assets/event-stream-destinations/adroll-event-mapping.png
  assets/event-stream-destinations/adroll-new-audience-settings.png
  assets/event-stream-destinations/adroll-new-audience.png
  assets/event-stream-destinations/adroll-pixel.png
  destinations/marketing/adroll.mdx
Labels: Good to go!

#565 BigQuery Update - Deduplication Information
  data-warehouse-integrations/google-bigquery.mdx
Labels: Good to go!

#584 Snowflake documentation updates
  docs/data-warehouse-integrations/snowflake.mdx
Labels: Ready for review

#583 Amplitude: Send event_id
  docs/destinations/analytics/amplitude.mdx
Labels: Ready for review

#582 Snapchat Conversions doc
  docs/assets/event-stream-destinations/snap-conversions-add-new-app.png
  docs/assets/event-stream-destinations/snap-conversions-api-token.png
  docs/assets/event-stream-destinations/snap-conversions-pixel-id.png
  docs/assets/event-stream-destinations/snap-conversions-setup-pixel.png
  docs/assets/event-stream-destinations/snapchat-conversion-connection-settings.png
  docs/destinations/advertising/snapchat-conversion.mdx
Labels: Ready for review

#587 Okta SSO documentation updates
  docs/assets/user-guides/okta-sso-6.png
  docs/user-guides/administrators-guide/okta-sso.mdx
Labels: Good to go!

#589 Revenue Cat Documentation
  docs/assets/event-stream-destinations/rev-cat-connection-settings.png
  docs/assets/event-stream-destinations/rev-cat-project.png
  docs/assets/event-stream-destinations/rev-cat-public-api-key.png
  docs/destinations/marketing/revenue-cat.mdx
Labels: Good to go!

#588 New Relic Documentation
  docs/assets/event-stream-destinations/new-relic-connection-settings.png
  docs/assets/event-stream-destinations/new-relic-insert-key.png
  docs/destinations/analytics/new-relic.mdx
Labels: Good to go!

#529 Home page updates
  docs/faqs.mdx
  docs/index.mdx
  src/components/DocsNavigation.js
  src/sidebar.js
Labels: Ready for review

#586 Use gatsby link in OS vs. Cloud guide
  docs/get-started/cloud-vs-open-source.mdx
  docs/get-started/glossary.mdx
  docs/get-started/index.mdx
  docs/get-started/rudderstack-architecture.mdx
Labels: Review in progress

#591 Sidebar updates
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#593 Snowflake documentation updates
  docs/assets/dw-integrations/snowflake-account-id-example.png
  docs/assets/dw-integrations/snowflake-connection-settings.png
  docs/data-warehouse-integrations/snowflake.mdx
Labels: Good to go!

#596 Tracking Plans updates
  docs/data-governance/tracking-plans/index.mdx
  docs/data-governance/tracking-plans/tracking-plan-spreadsheet.mdx
Labels: Good to go!

#597 Swift SDK migration
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/macos.mdx
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#590 Warehouse FAQ revamp and addition
  docs/assets/dw-integrations/namespace.png
  docs/assets/dw-integrations/snowflake-accountid-example.png
  docs/data-warehouse-integrations/clickhouse.mdx
  docs/data-warehouse-integrations/warehouse-faqs.mdx
Labels: Good to go!

#598 Flush API update in mobile SDK
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/flushing-events-periodically.mdx
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.mdx
  src/sidebar.js
Labels: Good to go!

#606 Databricks external location setting
  docs/assets/dw-integrations/delta-lake-connection-settings-1.png
  docs/assets/dw-integrations/delta-lake-connection-settings-13.png
  docs/assets/dw-integrations/delta-lake-connection-settings-2.png
  docs/data-warehouse-integrations/delta-lake.mdx
Labels: Good to go!

#603 Next.js: Use NPM package of JavaScript SDK
  docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-nextjs-integration.mdx
Labels: Good to go!

#609 Firebase device mode updates for iOS SDK v2
  docs/destinations/analytics/firebase.mdx
Labels: Good to go!

#600 Warehouse-specific configuration improvements
  docs/data-warehouse-integrations/azure-synapse.mdx
  docs/data-warehouse-integrations/gcs-datalake.mdx
  docs/data-warehouse-integrations/snowflake.mdx
Labels: Good to go!

#613 ActiveCampaign documentation updates
  docs/assets/event-stream-destinations/activecampaign-eventname-truncation.png
  docs/destinations/marketing/activecampaign.mdx
Labels: Good to go!

#601 feat: add Alias to Variance destination doc
  docs/destinations/crm/variance.mdx
Labels: Review in progress

#594 Custom Domains documentation updates
  docs/user-guides/how-to-guides/custom-domains.mdx
Labels: Good to go!

#616 Intercom documentation updates
  docs/destinations/business-messaging/intercom.mdx
Labels: Good to go!

#619 Customer.io - Alias call
  docs/destinations/marketing/customer.io.mdx
Labels: Good to go!

#614 GA4: Enable Google Signals
  docs/assets/event-stream-destinations/Google-signals-1.png
  docs/assets/event-stream-destinations/Google-signals-2.png
  docs/assets/event-stream-destinations/Google-signals-3.png
  docs/assets/event-stream-destinations/Google-signals-4.png
  docs/assets/event-stream-destinations/Google-signals-5.png
  docs/destinations/analytics/google-analytics-4/google-analytics-4-device-mode.mdx
Labels: Good to go!

#610 Bugsnag device mode updates for iOS SDK v2
  docs/assets/event-stream-destinations/bugsnag-api-key.png
  docs/assets/event-stream-destinations/bugsnag-connection-settings.png
  docs/assets/event-stream-destinations/iterable-connection-settings.png
  docs/destinations/error-reporting/bugsnag.mdx
Labels: Good to go!

#607 Google sheets revamp
  docs/assets/cloud-extract-sources/google-sheets-connection-settings-1.png
  docs/assets/cloud-extract-sources/google-sheets-connection-settings-2.png
  docs/cloud-extract-sources/google-sheets.mdx
Labels: Good to go!
