Repository rudderlabs/rudderstack-docs, pull requests merged in 2022-01, with the labels that each got.

#310 RudderStack Airflow Provider Documentation
  assets/warehouse-actions-sources/airflow-provider-1.png
  assets/warehouse-actions-sources/airflow-provider-2.png
  assets/warehouse-actions-sources/airflow-provider-3.png
  warehouse-actions/airflow-provider.mdx
Labels: Do not merge, Good to go!

#318 Test API updates
  assets/test-api-3.png
  assets/test-api-4.png
  assets/test-api-5.png
  rudderstack-api/test-api.mdx
Labels: Good to go!

#320 Update postNavList.js
  postNavList.js
Labels: Good to go!

#321 Documentation Updates
  data-warehouse-integrations/delta-lake.mdx
  rudderstack-api/test-api.mdx
Labels: Good to go!

#319 Google Analytics Doc Update
  assets/cloud-extract-sources/ga-1.png
  assets/cloud-extract-sources/ga-2.png
  assets/cloud-extract-sources/ga-3.png
  assets/cloud-extract-sources/ga-4.png
  cloud-extract-sources/google-analytics.mdx
Labels: Ready for review

#326 Custom Audience Documentation fix
  destinations/advertising/fb-custom-audience.mdx
Labels: Ready for review

#328 Chromecast Android Doc Update
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
Labels: Ready for review

#324 Branch Missing Updates Fix
  destinations/attribution/branchio.mdx
Labels: Review in progress

#323 Chromecast doc for Android, iOS and Web
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
Labels: Review in progress

#331 Update airflow provider
  warehouse-actions/airflow-provider.mdx
Labels: Ready for review

#327 Posthog update : Added information regarding 'Enable Local storage for persistence'
  assets/posthog-web-settings-1.png
  assets/posthog-web-settings.png
  destinations/analytics/posthog.mdx
Labels: Good to go!

#322 Appsflyer : Update regarding support for all sources.
  assets/event-stream-destinations/appsflyer-2.png
  assets/event-stream-destinations/appsflyer-3.png
  assets/event-stream-destinations/appsflyer-connection-settings-final.png
  destinations/attribution/appsflyer.mdx
Labels: Good to go!

#316 JavaScript SDK Documentation Enhancements
  assets/event-stream-sources/onetrust-1.png
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/consent-managers/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/consent-managers/onetrust.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/javascript-sdk-enhancements.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/quick-start-guide.mdx
Labels: Good to go!

#332 SDK doc fixes
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-go-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-java-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-node-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-python-sdk.mdx
Labels: Good to go!

#335 Fix: broken bigquery stream link
  destinations/streaming-platforms/index.mdx
Labels: Ready for review

#336 Update ruby
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-ruby-sdk.mdx
Labels: Good to go!

#337 DynamicConfigDocAdd: Added few informations
  user-guides/how-to-guides/dynamic-destination-configuration.mdx
Labels: Good to go!

#341 Destination template updates
  Destination_Template.mdx
Labels: Good to go!

#338 Create Destination_Template
  Destination_Template.mdx
Labels: Good to go!

#334 FAQs update
  faqs.mdx
Labels: Good to go!

#343 Hotjar Documentation Update
  assets/event-stream-destinations/hotjar-connection-settings.png
  destinations/analytics/hotjar.mdx
Labels: Good to go!

#344 Identify call doc fixes
  destinations/analytics/amplitude.mdx
  destinations/marketing/activecampaign.mdx
Labels: Good to go!

#342 Add: session id faq
  destinations/analytics/amplitude.mdx
Labels: Good to go!

#329 Adding documentation for Statsig
  destinations/analytics/statsig.mdx
Labels: Good to go!

#347 Update google-ads.mdx
  destinations/advertising/google-ads.mdx
Labels: Review in progress

#349 Google Ads Doc Hotfix
  assets/event-stream-destinations/gads-connection-settings.png
  destinations/advertising/gads.mdx
Labels: Ready for review

#352 Google Ads URL fix
  destinations/advertising/google-ads-gtag.mdx
  postNavList.js
  sidebar.js
Labels: Ready for review

#346 LaunchDarkly documentation
  assets/event-stream-destinations/launchdarkly-clientsideID.png
  assets/event-stream-destinations/launchdarkly-connection-settings.png
  assets/event-stream-destinations/launchdarkly-projects.png
  destinations/testing-and-personalization/launchdarkly.mdx
Labels: Good to go!

#353 GTM Updates
  assets/event-stream-destinations/gtm-connection-settings.png
  assets/event-stream-destinations/rudderstack-container-id.png
  assets/event-stream-destinations/rudderstack-custom-html-gtm.png
  assets/event-stream-destinations/rudderstack-server-container-url.png
  destinations/marketing/sendgrid.mdx
  destinations/tag-managers/google-tag-manager.mdx
Labels: Good to go!

#348 Event Filtering documentation
  assets/event-stream-sources/rudderstack-event-filtering.png
  stream-sources/rudderstack-sdk-integration-guides/event-filtering.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.mdx
Labels: Ready for review

#351 Dynamic Destination Config Updates
  assets/user-guides/dynamic-config-field-mapping.png
  assets/user-guides/dynamic-destination-configuration.png
  user-guides/how-to-guides/dynamic-destination-configuration.mdx
Labels: Good to go!

#354 BigQuery Stream Updates
  destinations/data-ingestion/index.mdx
  destinations/streaming-platforms/amazon-eventbridge.mdx
  destinations/streaming-platforms/amazon-kinesis-firehose.mdx
  destinations/streaming-platforms/amazon-kinesis.mdx
  destinations/streaming-platforms/azure-event-hubs.mdx
  destinations/streaming-platforms/bigquery-stream.mdx
  destinations/streaming-platforms/confluent-cloud.mdx
  destinations/streaming-platforms/google-pub-sub.mdx
  destinations/streaming-platforms/index.mdx
  destinations/streaming-platforms/kafka.mdx
  postNavList.js
  rudderstack-api/test-api.mdx
  sidebar.js
Labels: Ready for review

#355 Marketo Bulk Upload Documentation Updates
  assets/event-stream-destinations/marketo-lead-import-connection-settings.png
  destinations/marketing/marketo-lead-import.mdx
Labels: Good to go!

#356 Event Filtering Documentation Updates
  postNavList.js
  sidebar.js
  stream-sources/rudderstack-sdk-integration-guides/event-filtering.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.mdx
Labels: Good to go!

#357 Batch Request Update
  rudderstack-api/http-api.mdx
Labels: Ready for review

#330 Update transformations
  transformations/faq.mdx
  transformations/index.mdx
Labels: Good to go!

#358 404 fixes
  data-warehouse-integrations/google-bigquery.mdx
  get-started/control-plane-lite.mdx
  glossary.mdx
  rudderstack-api/test-api.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
Labels: Ready for review

#362 Data Regulation API updates
  rudderstack-api/data-regulation-api.mdx
Labels: Good to go!

#363 App Events update
  destinations/advertising/facebook-app-events.mdx
Labels: Good to go!

#361 Add specific place to find data plane URL for RudderStack Cloud in FAQ
  faqs.mdx
Labels: Good to go!

#365 Event Filtering Doc Updates
  stream-sources/rudderstack-sdk-integration-guides/event-filtering.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
Labels: Good to go!

#366 Customer.io Update: Unsubscribing Users
  destinations/marketing/customer.io.mdx
Labels: Ready for review

#369 Remove: home button
  user-guides/administrators-guide/index.mdx
Labels: Good to go!

#370 BigQuery Stream Documentation Updates
  assets/event-stream-destinations/bqstream-service-account-4.png
  destinations/streaming-platforms/bigquery-stream.mdx
Labels: Good to go!

#359 Added Candu doc and image
  assets/event-stream-destinations/candu-api-key.png
  assets/event-stream-destinations/candu-connection-settings.png
  destinations/testing-and-personalization/candu.mdx
Labels: Internal review

#372 ActiveCampaign Updates
  destinations/marketing/activecampaign.mdx
Labels: Ready for review
