Repository rudderlabs/rudderstack-docs, pull requests merged in 2022-04, with the labels that each got.

#487 Measurement protocol parameters for GA
  destinations/analytics/google-analytics-ga.mdx
Labels: Internal review

#492 Page call support added for FB App event
  destinations/advertising/facebook-app-events.mdx
Labels: Ready for review

#493 GARL access levels FAQ
  assets/event-stream-destinations/gads-access-security.png
  assets/event-stream-destinations/gads-specify-access-level.png
  destinations/advertising/google-adwords-remarketing-list.mdx
Labels: Ready for review

#489 Android SDK configuration for advertising IDs
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/flutter-v2.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-unity-sdk.mdx
Labels: Good to go!

#495 Badge layout update
  rudderstack-api/data-regulation-api.mdx
Labels: Good to go!

#497 Destination name fix in JS SDK
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
Labels: Good to go!

#498 Google Ads path update in the main page.
  destinations/advertising/index.mdx
Labels: Good to go!

#499 Blueshift documentation update - remove group call
  destinations/marketing/blueshift.mdx
Labels: Good to go!

#503 Lifecycle Event Spec documentation
  rudderstack-api/api-specification/application-lifecycle-events-spec.mdx
Labels: Good to go!

#488 Version badges for all SDK docs
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-dotnet-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/flutter-v1.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/flutter-v2.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-go-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-java-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-node-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-php-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-python-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-ruby-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-rust-sdk.mdx
Labels: Ready for review

#494 RudderStack Open Source Revamp
  assets/rudderstack-open-source/control-plane-lite-dashboard.png
  assets/rudderstack-open-source/control-plane-lite-source-writekey.png
  assets/rudderstack-open-source/export-source-config.png
  assets/rudderstack-open-source/rudder-config-1.png
  assets/rudderstack-open-source/rudder-docker-yml-file.png
  assets/rudderstack-open-source/source-write-key.png
  assets/rudderstack-open-source/test-event-error.png
  assets/rudderstack-open-source/test-event.png
  assets/rudderstack-open-source/workspace-token.png
  assets/rudderstack-open-source/write-key-vs-workspace-token.png
  rudderstack-open-source/control-plane-lite.mdx
  rudderstack-open-source/index.mdx
  rudderstack-open-source/installing-and-setting-up-rudderstack/developer-machine-setup.mdx
  rudderstack-open-source/installing-and-setting-up-rudderstack/docker.mdx
  rudderstack-open-source/installing-and-setting-up-rudderstack/index.mdx
  rudderstack-open-source/installing-and-setting-up-rudderstack/kubernetes.mdx
  rudderstack-open-source/installing-and-setting-up-rudderstack/sending-test-events.mdx
Labels: Good to go!

#500 Added pre-defined API for traits in Unity
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-unity-sdk.mdx
Labels: Ready for review

#486 Identity Resolution documentation
  assets/identity-resolution/identity-mappings-table.png
  assets/identity-resolution/identity-merge-rules.png
  assets/identity-resolution/identity-resolution-workflow.png
  assets/identity-resolution/rudder-id.png
  identity-resolution.mdx
Labels: Good to go!

#507 Airship documentation update
  assets/event-stream-destinations/airship-connection-settings.png
  destinations/marketing/airship.mdx
Labels: Ready for review

#508 Residency server setting in Amplitude
  destinations/analytics/amplitude.mdx
Labels: Good to go!

#510 SSL section added for PostgreSQL and Redshift
  assets/warehouse-actions-sources/postgresql-connection-settings.png
  assets/warehouse-actions-sources/redshift-connection-settings.png
  reverse-etl/amazon-redshift.mdx
  reverse-etl/postgresql.mdx
Labels: Good to go!

#509 FB Pixel Event ID details
  destinations/advertising/fb-pixel.mdx
Labels: Good to go!

#501 Storage settings in WH destination docs
  assets/dw-integrations/azure-synapse-connection.png
  assets/dw-integrations/azure-synapse-connection2.png
  assets/dw-integrations/bigquery-connection-settings-1.png
  assets/dw-integrations/bigquery-connection-settings-2.png
  assets/dw-integrations/clickhouse-connection-settings.png
  assets/dw-integrations/clickhouse-connection-settings2.png
  assets/dw-integrations/mssqlconnection.png
  assets/dw-integrations/mssqlconnection2.png
  assets/dw-integrations/redshift-connection-settings.png
  assets/dw-integrations/redshift-connection-settings2.png
  data-warehouse-integrations/amazon-redshift.mdx
  data-warehouse-integrations/azure-datalake.mdx
  data-warehouse-integrations/azure-synapse.mdx
  data-warehouse-integrations/clickhouse.mdx
  data-warehouse-integrations/delta-lake.mdx
  data-warehouse-integrations/gcs-datalake.mdx
  data-warehouse-integrations/google-bigquery.mdx
  data-warehouse-integrations/index.mdx
  data-warehouse-integrations/microsoft-sql-server.mdx
  data-warehouse-integrations/postgresql.mdx
  data-warehouse-integrations/s3-datalake.mdx
  data-warehouse-integrations/snowflake.mdx
  data-warehouse-integrations/warehouse-faqs.mdx
  data-warehouse-integrations/warehouse-schemas.mdx
Labels: Good to go!

#511 Updated VDM supported destinations
  reverse-etl/features/visual-data-mapper.mdx
Labels: Good to go!

#505 DCM Floodlight doc
  assets/event-stream-destinations/dcm-floodlight-advertiser-id.png
  assets/event-stream-destinations/dcm-floodlight-cat-vs-type.png
  assets/event-stream-destinations/dcm-floodlight-connection-settings.png
  assets/event-stream-destinations/dcm-floodlight-connection-settings2.png
  assets/event-stream-destinations/dcm-floodlight-custom-variables.png
  assets/event-stream-destinations/dcm-floodlight-report-builder.png
  assets/event-stream-destinations/dcm-floodlight-report-settings.png
  destinations/advertising/dcm-floodlight.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
Labels: Good to go!

#516 Removed web support for DCM cloud mode
  destinations/advertising/dcm-floodlight.mdx
Labels: Ready for review

#515 AppsFlyer device mode updates
  destinations/attribution/appsflyer.mdx
Labels: Good to go!

#513 Snap Pixel: Updated e-commerce events
  destinations/advertising/snap-pixel.mdx
Labels: Ready for review

#514 Group call added and update data center for Blueshift
  assets/event-stream-destinations/blueshift-connection-settings.png
  destinations/marketing/blueshift.mdx
Labels: Ready for review

#502 RS Cloud
  assets/rs-cloud/add-source-destination.png
  assets/rs-cloud/add-source.png
  assets/rs-cloud/audit-logs-dashboard.png
  assets/rs-cloud/audit-logs-details.png
  assets/rs-cloud/audit-logs-source.png
  assets/rs-cloud/audit-logs.png
  assets/rs-cloud/connections-dashboard.png
  assets/rs-cloud/custom-audience-error.png
  assets/rs-cloud/custom-audience-full-error.png
  assets/rs-cloud/destination-configuration.png
  assets/rs-cloud/destination-live-events-details.png
  assets/rs-cloud/destination-live-events.png
  assets/rs-cloud/destinations.png
  assets/rs-cloud/directory.png
  assets/rs-cloud/duplicate-destination.png
  assets/rs-cloud/getting-started-connection-modes.png
  assets/rs-cloud/invite-teammates.png
  assets/rs-cloud/rename-destination.png
  assets/rs-cloud/rename-source.png
  assets/rs-cloud/rs-cloud-workflow.png
  assets/rs-cloud/rudderstack-cloud-mode.png
  assets/rs-cloud/rudderstack-dashboard.png
  assets/rs-cloud/rudderstack-destinations.png
  assets/rs-cloud/rudderstack-device-mode.png
  assets/rs-cloud/rudderstack-source-details.png
  assets/rs-cloud/rudderstack-sources.png
  assets/rs-cloud/select-source.png
  assets/rs-cloud/settings-dashboard.png
  assets/rs-cloud/source-configure.png
  assets/rs-cloud/source-live-events-details.png
  assets/rs-cloud/source-live-events.png
  assets/rs-cloud/syncs-dashboard.png
  assets/rs-cloud/teammate-details.png
  assets/rs-cloud/transformation-live-events-details.png
  assets/rs-cloud/transformation-live-events-errors.png
  assets/rs-cloud/transformations-dashboard.png
  assets/rs-cloud/web-device-mode-settings.png
  rudderstack-cloud/audit-logs.mdx
  rudderstack-cloud/connections/adding-source-and-destination-rudderstack.mdx
  rudderstack-cloud/connections/index.mdx
  rudderstack-cloud/dashboard-overview.mdx
  rudderstack-cloud/destinations.mdx
  rudderstack-cloud/index.mdx
  rudderstack-cloud/live-events.mdx
  rudderstack-cloud/rudderstack-connection-modes.mdx
  rudderstack-cloud/sources.mdx
  rudderstack-cloud/teammates.mdx
Labels: Good to go!

#518 Lytics connection settings updated
  assets/event-stream-destinations/lytics-connection-settings-2.png
  assets/event-stream-destinations/lytics-connection-settings.png
  destinations/analytics/lytics.mdx
Labels: Ready for review

#520 Minor documentation fixes
  assets/get-started/adding-new-destination.png
  assets/get-started/connections-dashboard.png
  assets/get-started/source-details.png
  connections/rudderstack-connection-modes.mdx
  get-started/glossary.mdx
  get-started/rudderstack-architecture.mdx
  rudderstack-cloud/audit-logs.mdx
  rudderstack-cloud/dashboard-overview.mdx
  rudderstack-cloud/destinations.mdx
  rudderstack-cloud/index.mdx
  rudderstack-cloud/sources.mdx
  rudderstack-cloud/teammates.mdx
  sidebar.js
Labels: Good to go!

#517 FAQ revamp
  assets/general/destination-event-metrics.png
  assets/general/wh-destination-namespace.png
  faqs.mdx
Labels: Ready for review

#522 Sidebar updates
  sidebar.js
Labels: Good to go!

#526 Enhanced Conversions FAQ
  destinations/advertising/google-adwords-enhanced-conversions.mdx
  destinations/advertising/google-adwords-remarketing-list.mdx
Labels: Good to go!

#523 Device specific information for DCM Floodlight
  destinations/advertising/dcm-floodlight.mdx
Labels: Good to go!

#524 Sendgrid Cloud Extract documentation
  assets/cloud-extract-sources/add-destination.png
  assets/cloud-extract-sources/sendgrid-api-key-details.png
  assets/cloud-extract-sources/sendgrid-api-key-permissions.png
  assets/cloud-extract-sources/sendgrid-api-key.png
  assets/cloud-extract-sources/sendgrid-api-permissions.png
  assets/cloud-extract-sources/sendgrid-connection-settings-2.png
  assets/cloud-extract-sources/sendgrid-connection-settings-3.png
  assets/cloud-extract-sources/sendgrid-connection-settings.png
  assets/cloud-extract-sources/sync-schedule-manual.png
  assets/cloud-extract-sources/sync-schedule-settings-change.png
  cloud-extract-sources/common-settings.mdx
  cloud-extract-sources/sendgrid.mdx
Labels: Ready for review

#528 Home page updates
  rudderstack-cloud/index.mdx
  user-guides/migration-guides/home.mdx
Labels: Good to go!

#519 anonymousIdOptions added in JS SDK
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/javascript-sdk-enhancements.mdx
  user-guides/migration-guides/rudderstack-migration-guide.mdx
Labels: Good to go!

#531 Tracking Plans update
  data-governance/tracking-plans/index.mdx
  rudderstack-cloud/dashboard-overview.mdx
Labels: Good to go!

#530 Statsig documentation update
  assets/event-stream-destinations/statsig-api-keys.png
  assets/event-stream-destinations/statsig-settings.png
  destinations/testing-and-personalization/statsig.mdx
Labels: Good to go!

#535 Application Lifecycle Events Hotfix
  rudderstack-api/api-specification/application-lifecycle-events-spec.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-unity-sdk.mdx
Labels: Good to go!

#527 Methods to filter event data
  postNavList.js
  sidebar.js
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/js-sdk-faqs.mdx
  stream-sources/rudderstack-sdk-integration-guides/sdk-faqs.mdx
  user-guides/how-to-guides/filter-events.mdx
Labels: Good to go!

#538 Okta SSO documentation update
  assets/user-guides/okta-sso-4.png
  assets/user-guides/okta-sso-5.png
  assets/user-guides/okta-sso-6.png
  user-guides/administrators-guide/okta-sso.mdx
Labels: Ready for review

#540 GAEC - Added Hashing option
  assets/event-stream-destinations/enhanced-conversions-connection-settings.png
  destinations/advertising/google-adwords-enhanced-conversions.mdx
Labels: Ready for review

#539 JS SDK Reset method update
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
Labels: Ready for review

#533 Updated Appsflyer Device Mode related information
  destinations/attribution/appsflyer.mdx
Labels: Ready for review

#544 Updated info for lifecycle events
  rudderstack-api/api-specification/application-lifecycle-events-spec.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-unity-sdk.mdx
Labels: Ready for review

#534 JS SDK Quick Start Guide update
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/quick-start-guide.mdx
Labels: Good to go!

#532 Support for cloud mode in Google Analytics 4
  assets/event-stream-destinations/api-secret.png
  assets/event-stream-destinations/firebase-app-id.png
  assets/event-stream-destinations/google-analytics-4-connection-settings.png
  assets/event-stream-destinations/google-analytics-4-connection-settings2.png
  assets/event-stream-destinations/google-analytics-4-connection-settings3.png
  assets/event-stream-destinations/measurement-id.png
  destinations/analytics/google-analytics-4.mdx
  destinations/analytics/google-analytics-4/google-analytics-4-cloud-mode.mdx
  destinations/analytics/google-analytics-4/google-analytics-4-device-mode.mdx
  destinations/analytics/google-analytics-4/index.mdx
  destinations/analytics/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
  postNavList.js
  sidebar.js
Labels: Ready for review
