Repository rudderlabs/rudderstack-docs, pull requests merged in 2022-09, with the labels that each got.

#859 Branch.io updates (Take II)
  docs/assets/event-stream-destinations/branchio-connection-settings.png
  docs/assets/event-stream-destinations/branchio-key.png
  docs/destinations/streaming-destinations/branchio.mdx
Labels: Good to go!

#860 Column count threshold FAQ update
  docs/destinations/warehouse-destinations/faq.mdx
Labels: Good to go!

#866 Zapier documentation
  docs/assets/event-stream-destinations/create-zap-1.png
  docs/assets/event-stream-destinations/create-zap-2.png
  docs/assets/event-stream-destinations/create-zap-3.png
  docs/assets/event-stream-destinations/zapier-connection-settings.png
  docs/destinations/streaming-destinations/zapier.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#853 Fb App Events ios device mode updates
  docs/assets/event-stream-destinations/fb-app-events-app-id.png
  docs/assets/event-stream-destinations/fb-app-events-client-token.png
  docs/assets/event-stream-destinations/fb-app-events-connection-settings-2.png
  docs/assets/event-stream-destinations/fb-app-events-connection-settings.png
  docs/destinations/streaming-destinations/facebook-app-events.mdx
Labels: Good to go!

#865 Data Plane Setup command updates
  docs/get-started/rudderstack-open-source/data-plane-setup/docker.mdx
  docs/get-started/rudderstack-open-source/data-plane-setup/index.mdx
Labels: Good to go!

#864 Split permissions management doc
  docs/dashboard-guides/permissions-management.mdx
  docs/dashboard-guides/user-management.mdx
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#868 Freshsales documentation
  docs/assets/event-stream-destinations/freshsales-api-key.png
  docs/assets/event-stream-destinations/freshsales-connection-settings.png
  docs/destinations/streaming-destinations/freshsales.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#869 Freshmarketer documentation
  docs/assets/event-stream-destinations/freshmarketer-api-key.png
  docs/assets/event-stream-destinations/freshmarketer-connection-settings.png
  docs/destinations/streaming-destinations/freshmarketer.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#867 Rockerbox doc
  docs/assets/event-stream-destinations/rockerbox-connection-settings-2.png
  docs/assets/event-stream-destinations/rockerbox-connection-settings-3.png
  docs/assets/event-stream-destinations/rockerbox-connection-settings.png
  docs/destinations/streaming-destinations/rockerbox/index.mdx
  docs/destinations/streaming-destinations/rockerbox/rockerbox-cloud-mode.mdx
  docs/destinations/streaming-destinations/rockerbox/rockerbox-device-mode.mdx
  docs/destinations/streaming-destinations/rockerbox/setting-up-rockerbox.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#862 Amplitude group call updates
  docs/destinations/streaming-destinations/amplitude.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/supported-api.mdx
Labels: Good to go!

#870 Shynet doc
  docs/assets/event-stream-destinations/shynet-connection-settings-2.png
  docs/assets/event-stream-destinations/shynet-connection-settings-3.png
  docs/assets/event-stream-destinations/shynet-connection-settings.png
  docs/assets/event-stream-destinations/shynet-script-url.png
  docs/destinations/streaming-destinations/shynet.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#873 NetSuite source updates
  docs/assets/cloud-extract-sources/netsuite-account-id.png
  docs/assets/cloud-extract-sources/netsuite-connection-settings-2.png
  docs/assets/cloud-extract-sources/netsuite-create-employee-1.png
  docs/assets/cloud-extract-sources/netsuite-create-employee-2.png
  docs/assets/cloud-extract-sources/netsuite-create-role-1.png
  docs/assets/cloud-extract-sources/netsuite-integration-flow-1.png
  docs/assets/cloud-extract-sources/netsuite-integration-flow-2.png
  docs/assets/cloud-extract-sources/netsuite-token-based-auth-1.png
  docs/assets/cloud-extract-sources/netsuite-token-based-auth-2.png
  docs/assets/cloud-extract-sources/netsuite-token-based-auth-3.png
  docs/sources/extract/netsuite.mdx
Labels: Good to go!

#874 FB Pixel update
  docs/destinations/streaming-destinations/fb-pixel.mdx
Labels: Good to go!

#880 Shynet sidebar update
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#878 ClickUp integration docs
  docs/assets/event-stream-destinations/clickup-api-token.png
  docs/assets/event-stream-destinations/clickup-connection-settings-1.png
  docs/assets/event-stream-destinations/clickup-connection-settings-2.png
  docs/assets/event-stream-destinations/clickup-custom-field.png
  docs/assets/event-stream-destinations/clickup-custom-fields-1.png
  docs/assets/event-stream-destinations/clickup-custom-fields-2.png
  docs/assets/event-stream-destinations/clickup-listid-1.png
  docs/assets/event-stream-destinations/clickup-listid-2.png
  docs/destinations/streaming-destinations/clickup.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#871 LiveChat integration docs
  docs/assets/event-stream-destinations/livechat-connection-settings-1.png
  docs/assets/event-stream-destinations/livechat-connection-settings-2.png
  docs/assets/event-stream-destinations/livechat-connection-settings-3.png
  docs/assets/event-stream-destinations/livechat-connection-settings-4.png
  docs/assets/event-stream-destinations/livechat-event-mapping.png
  docs/assets/event-stream-destinations/livechat-license-id.png
  docs/destinations/streaming-destinations/livechat.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#876 Monday destination doc
  docs/assets/event-stream-destinations/monday-api-token.png
  docs/assets/event-stream-destinations/monday-connection-settings-2.png
  docs/assets/event-stream-destinations/monday-connection-settings.png
  docs/assets/event-stream-destinations/monday-dashboard.png
  docs/destinations/streaming-destinations/monday.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#881 Pinterest updates
  docs/assets/event-stream-destinations/pinterest-tag-events-cloud.png
  docs/assets/event-stream-destinations/pinterest-tag-events.png
  docs/destinations/streaming-destinations/pinterest-ads/pinterest-ads-cloud-mode.mdx
  docs/destinations/streaming-destinations/pinterest-ads/pinterest-ads-device-mode.mdx
Labels: Good to go!

#882 DCM Floodlight Note
  docs/destinations/streaming-destinations/dcm-floodlight/setting-up-dcm-floodlight-in-rudderstack.mdx
Labels: Good to go!

#884 Web device mode listing
  docs/destinations/streaming-destinations/index.mdx
Labels: Good to go!

#879 Setting external ID in JS SDK
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/supported-api.mdx
Labels: Good to go!

#887 AWS Personalize note
  docs/destinations/streaming-destinations/aws-personalize.mdx
Labels: Good to go!

#883 Added FAQ related to rudder_discards
  docs/destinations/warehouse-destinations/azure-datalake.mdx
  docs/destinations/warehouse-destinations/azure-synapse.mdx
  docs/destinations/warehouse-destinations/bigquery.mdx
  docs/destinations/warehouse-destinations/clickhouse.mdx
  docs/destinations/warehouse-destinations/delta-lake.mdx
  docs/destinations/warehouse-destinations/faq.mdx
  docs/destinations/warehouse-destinations/gcs-datalake.mdx
  docs/destinations/warehouse-destinations/postgresql.mdx
  docs/destinations/warehouse-destinations/redshift.mdx
  docs/destinations/warehouse-destinations/s3-datalake.mdx
  docs/destinations/warehouse-destinations/snowflake.mdx
  docs/destinations/warehouse-destinations/sql-server.mdx
  docs/destinations/warehouse-destinations/warehouse-schema.mdx
Labels: Good to go!

#849 Documentation for the Custify destination for RudderStack
  docs/assets/event-stream-destinations/custify-connection-settings.png
  docs/destinations/streaming-destinations/custify.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#888 Mailmodo source doc
  docs/assets/event-stream-sources/Mailmodo-2.png
  docs/assets/event-stream-sources/webhook_url_1.png
  docs/assets/event-stream-sources/webhook_url_2.png
  docs/sources/event-streams/cloud-apps/canny.mdx
  docs/sources/event-streams/cloud-apps/mailmodo.mdx
  src/data/sources.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#893 Rockerbox hotfix
  docs/assets/event-stream-destinations/rockerbox-connection-settings.png
  docs/destinations/streaming-destinations/rockerbox/setting-up-rockerbox.mdx
Labels: Good to go!

#903 Update Rockerbox mappings
  docs/destinations/streaming-destinations/rockerbox/rockerbox-cloud-mode.mdx
Labels: Ready for review

#899 Added phone number FAQ to TikTok docs
  docs/destinations/streaming-destinations/tiktok-ads.mdx
Labels: Good to go!

#900 Added new event for Braze Currents
  docs/sources/event-streams/cloud-apps/braze-currents.mdx
Labels: Good to go!

#889 Woopra documentation
  docs/assets/event-stream-destinations/woopra-connection-settings-1.png
  docs/assets/event-stream-destinations/woopra-connection-settings-2.png
  docs/assets/event-stream-destinations/woopra-connection-settings-3.png
  docs/assets/event-stream-destinations/woopra-domain-name.png
  docs/assets/event-stream-destinations/woopra-project-name.png
  docs/destinations/streaming-destinations/woopra.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#898 Write key and data plane screenshots
  docs/assets/event-stream-sources/amp-write-key.png
  docs/assets/event-stream-sources/android-write-key.png
  docs/assets/event-stream-sources/appcenter-write-key.png
  docs/assets/event-stream-sources/appsflyer-write-key.png
  docs/assets/event-stream-sources/auth0-write-key.png
  docs/assets/event-stream-sources/braze-write-key.png
  docs/assets/event-stream-sources/cordova-write-key.png
  docs/assets/event-stream-sources/customerio-write-key.png
  docs/assets/event-stream-sources/dotnet-write-key.png
  docs/assets/event-stream-sources/extole-webhook-url.png
  docs/assets/event-stream-sources/flutter-write-key.png
  docs/assets/event-stream-sources/go-write-key.png
  docs/assets/event-stream-sources/ios-write-key.png
  docs/assets/event-stream-sources/iterable-webhook-url.png
  docs/assets/event-stream-sources/java-write-key.png
  docs/assets/event-stream-sources/javascript-setup.png
  docs/assets/event-stream-sources/javascript-write-key.png
  docs/assets/event-stream-sources/looker-write-key.png
  docs/assets/event-stream-sources/node-write-key.png
  docs/assets/event-stream-sources/php-write-key.png
  docs/assets/event-stream-sources/posthog-write-key.png
  docs/assets/event-stream-sources/python-write-key.png
  docs/assets/event-stream-sources/reactnative-write-key.png
  docs/assets/event-stream-sources/ruby-write-key.png
  docs/assets/event-stream-sources/rust-write-key.png
  docs/assets/event-stream-sources/segment-webhook-url.png
  docs/assets/event-stream-sources/shopify-data-plane-url.png
  docs/assets/event-stream-sources/shopify-write-key.png
  docs/assets/event-stream-sources/unity-write-key.png
  docs/assets/event-stream-sources/webhook-endpoint-url.png
  docs/assets/event-stream-sources/webhook-url-canny.png
  docs/assets/rs-cloud/connections-dashboard.png
  docs/assets/rs-cloud/setup-tab.png
Labels: Good to go!

#905 Renamed Iterable EventStream source to Iterable Webhook
  docs/sources/event-streams/cloud-apps/iterable.mdx
  src/sidebar.js
Labels: Good to go!

#895 LinkedIn Insight Tag documentation update
  docs/assets/event-stream-destinations/insight-tag-campaign-manager.png
  docs/assets/event-stream-destinations/insight-tag-connection-settings.png
  docs/assets/event-stream-destinations/insight-tag-conversion-id.png
  docs/assets/event-stream-destinations/insight-tag-conversion-status.png
  docs/assets/event-stream-destinations/insight-tag-online-conversion.png
  docs/assets/event-stream-destinations/insight-tag-partner-id.png
  docs/assets/event-stream-destinations/insight-tag-usecase.png
  docs/destinations/streaming-destinations/linkedin-insight-tag.mdx
  src/css/docs.css
Labels: Good to go!

#902 Quora pixel
  docs/assets/event-stream-destinations/quora-pixel-connection-settings.png
  docs/assets/event-stream-destinations/quora-pixel-custom-event.png
  docs/assets/event-stream-destinations/quora-pixel-custom-events-example.png
  docs/assets/event-stream-destinations/quora-pixel-event-mapping.png
  docs/assets/event-stream-destinations/quora-pixel-usecase.png
  docs/destinations/streaming-destinations/quora-pixel.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#906 Blur images hotfix
  docs/assets/event-stream-sources/appcenter-source-write-key.png
  docs/assets/event-stream-sources/appcenter-write-key.png
  docs/assets/event-stream-sources/appsflyer-source-write-key.png
  docs/assets/event-stream-sources/auth0-source-write-key.png
  docs/assets/event-stream-sources/braze-source-write-key.png
  docs/assets/event-stream-sources/customerio-webhook-url.png
  docs/sources/event-streams/cloud-apps/appcenter.mdx
  docs/sources/event-streams/cloud-apps/appsflyer.mdx
  docs/sources/event-streams/cloud-apps/auth0.mdx
  docs/sources/event-streams/cloud-apps/braze-currents.mdx
Labels: Good to go!

#875 Monday source documentation
  docs/assets/event-stream-sources/monday-webhook-url.png
  docs/sources/event-streams/cloud-apps/monday.mdx
  src/data/sources.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#901 Mixpanel documentation updates
  docs/destinations/streaming-destinations/mixpanel.mdx
Labels: Good to go!

#910 Automatic screen recording details in iOS SDK
  docs/sources/event-streams/sdks/rudderstack-ios-sdk/index.mdx
Labels: Good to go!

#897 Braze documentation update
  docs/assets/event-stream-destinations/braze-api-key.png
  docs/assets/event-stream-destinations/braze-app-key.png
  docs/assets/event-stream-destinations/braze-connection-settings.png
  docs/destinations/streaming-destinations/braze.mdx
Labels: Internal review

#894 Rollbar documentation
  docs/assets/event-stream-destinations/rollbar-access-token-1.png
  docs/assets/event-stream-destinations/rollbar-access-token-2.png
  docs/destinations/streaming-destinations/rollbar.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#885 Session tracking documentation
  docs/assets/event-stream-sources/session-tracking-mobile.png
  docs/assets/event-stream-sources/session-tracking-web-new.png
  docs/assets/event-stream-sources/session-tracking-web.png
  docs/sources/event-streams/sdks/rudderstack-android-sdk/index.mdx
  docs/sources/event-streams/sdks/rudderstack-ios-sdk/index.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
  docs/sources/event-streams/sdks/session-tracking/faq.mdx
  docs/sources/event-streams/sdks/session-tracking/index.mdx
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#891 Mailmodo destination doc
  docs/assets/event-stream-destinations/mailmodo-api-key.png
  docs/assets/event-stream-destinations/mailmodo-connection-settings.png
  docs/destinations/streaming-destinations/mailmodo.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#914 Updated supported SDK versions in Session tracking
  docs/sources/event-streams/sdks/session-tracking/index.mdx
Labels: Good to go!

#911 Signl4 source
  docs/assets/event-stream-sources/signl4-source-webhook.png
  docs/assets/event-stream-sources/signl4-source.png
  docs/sources/event-streams/cloud-apps/signl4.mdx
  src/data/sources.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#909 Reverse ETL source primary key setting
  docs/assets/warehouse-actions-sources/data-import-settings-2.png
  docs/sources/reverse-etl/common-settings/importing-data-using-tables.mdx
Labels: Good to go!

#896 User.com doc
  docs/assets/event-stream-destinations/user-com-connection-settings-2.png
  docs/assets/event-stream-destinations/user-com-connection-settings-3.png
  docs/assets/event-stream-destinations/user-com-connection-settings.png
  docs/assets/event-stream-destinations/user-com-dashboard-2.png
  docs/assets/event-stream-destinations/user-com-dashboard.png
  docs/destinations/streaming-destinations/user-com.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Internal review

#913 Signl4 destination
  docs/assets/event-stream-destinations/categories-signl4.png
  docs/assets/event-stream-destinations/signl-dashboard-1.png
  docs/assets/event-stream-destinations/signl-dashboard-2.png
  docs/assets/event-stream-destinations/signl4-conn-settings-2.png
  docs/assets/event-stream-destinations/signl4-conn-settings-3.png
  docs/assets/event-stream-destinations/signl4-conn-settings-4.png
  docs/assets/event-stream-destinations/signl4-conn-settings-5.png
  docs/assets/event-stream-destinations/signl4-connection-settings-2.png
  docs/assets/event-stream-destinations/signl4-connection-settings.png
  docs/destinations/streaming-destinations/signl4.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#917 Minor fixes in Control plane lite
  docs/get-started/rudderstack-open-source/control-plane-lite.mdx
  docs/sources/event-streams/sdks/rudderstack-android-sdk/index.mdx
  docs/sources/event-streams/sdks/rudderstack-flutter-sdk/flutter-v1.mdx
  docs/sources/event-streams/sdks/rudderstack-flutter-sdk/flutter-v2.mdx
  docs/sources/event-streams/sdks/rudderstack-flutter-sdk/index.mdx
  docs/sources/event-streams/sdks/rudderstack-ios-sdk/index.mdx
  docs/sources/event-streams/sdks/rudderstack-ios-sdk/ios-v2.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
  docs/sources/event-streams/sdks/rudderstack-unity-sdk.mdx
Labels: Good to go!

#921 UI mapping in Snap Pixel, Reddit Pixel and Google ads
  docs/destinations/streaming-destinations/g-ads-gtag.mdx
  docs/destinations/streaming-destinations/reddit-pixel.mdx
  docs/destinations/streaming-destinations/snap-pixel.mdx
Labels: Good to go!

#912 ClickUp source documentation
  docs/assets/event-stream-sources/clickup-add-automation.png
  docs/assets/event-stream-sources/clickup-configure-automation.png
  docs/assets/event-stream-sources/clickup-webhook-url.png
  docs/sources/event-streams/cloud-apps/clickup.mdx
  src/data/sources.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#928 Note to send large numbers as strings
  docs/event-spec/standard-events/index.mdx
Labels: Good to go!

#930 User deletion in AppsFlyer, CleverTap, and Mixpanel
  docs/api/data-regulation-api.mdx
  docs/destinations/streaming-destinations/amplitude.mdx
  docs/destinations/streaming-destinations/appsflyer.mdx
  docs/destinations/streaming-destinations/clevertap.mdx
  docs/destinations/streaming-destinations/intercom.mdx
  docs/destinations/streaming-destinations/mixpanel.mdx
Labels: Good to go!

#927 Zendesk chat v2 documentation
  docs/assets/cloud-extract-sources/zendesk-chat-connection-settings-2.png
  docs/assets/cloud-extract-sources/zendesk-chat-connection-settings.png
  docs/sources/extract/intercom-v2.mdx
  docs/sources/extract/zendesk-chat-v2.mdx
  docs/sources/extract/zendesk-chat.mdx
  src/data/sources.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#929 Customer.io Cloud Extract source
  docs/assets/cloud-extract-sources/customerio-connection-settings.png
  docs/assets/cloud-extract-sources/customerio-resources.png
  docs/assets/event-stream-sources/customerio-connection-settings.png
  docs/assets/event-stream-sources/customerio-resources.png
  docs/sources/extract/customerio.mdx
  src/data/sources.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Ready for review
