Repository rudderlabs/rudderstack-docs, pull requests merged in 2022-03, with the labels that each got.

#424 Warehouse Actions Sources updates
  assets/warehouse-actions-sources/sync-mirror-mode.png
  assets/warehouse-actions-sources/sync-schedule-basic-options.png
  assets/warehouse-actions-sources/sync-schedule-basic.png
  assets/warehouse-actions-sources/sync-schedule-cron-error.png
  assets/warehouse-actions-sources/sync-schedule-cron.png
  assets/warehouse-actions-sources/sync-schedule-manual.png
  assets/warehouse-actions-sources/sync-schedule-settings-change.png
  warehouse-actions/common-settings/index.mdx
  warehouse-actions/common-settings/sync-modes.mdx
  warehouse-actions/common-settings/sync-schedule-settings.mdx
  warehouse-actions/features/airflow-provider.mdx
  warehouse-actions/features/index.mdx
  warehouse-actions/features/visual-data-mapper.mdx
Labels: Good to go!

#423 Facebook Custom Audience documentation updates
  assets/event-stream-destinations/fb-custom-audience-access-token.png
  assets/event-stream-destinations/fb-custom-audience-api-tools.png
  assets/event-stream-destinations/fb-custom-audience-customer-value.png
  assets/event-stream-destinations/fb-custom-audience-edit-permissions.png
  assets/event-stream-destinations/fb-custom-audience-source.png
  destinations/advertising/fb-custom-audience.mdx
Labels: Good to go!

#428 Consent manager doc update
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/consent-managers/onetrust.mdx
Labels: Ready for review

#426 Custom SQL Models
  assets/warehouse-actions-sources/add-constant.png
  assets/warehouse-actions-sources/add-destination.png
  assets/warehouse-actions-sources/configure-model.png
  assets/warehouse-actions-sources/edit-model-configuration.png
  assets/warehouse-actions-sources/model-rename.png
  assets/warehouse-actions-sources/model-settings.png
  assets/warehouse-actions-sources/models-dashboard.png
  assets/warehouse-actions-sources/models-data-snippet.png
  assets/warehouse-actions-sources/models-view-dashboard.png
  assets/warehouse-actions-sources/sample-sql-query.png
  assets/warehouse-actions-sources/select-model-option.png
  assets/warehouse-actions-sources/select-source-model.png
  assets/warehouse-actions-sources/table-model-options.png
  assets/warehouse-actions-sources/update-table-selection.png
  assets/warehouse-actions-sources/warehouse-action-sources.png
  connections/models.mdx
  warehouse-actions/setting-connections-using-models.mdx
Labels: Good to go!

#427 Connection settings update for null check
  assets/event-stream-destinations/Fb-custom-audience-connection-settings-1.png
  assets/event-stream-destinations/Fb-custom-audience-connection-settings-2.png
  destinations/advertising/fb-custom-audience.mdx
Labels: Good to go!

#429 Category field update
  destinations/marketing/iterable.mdx
Labels: Good to go!

#430 Custom Models - content and sidebar updates
  connections/models.mdx
  postNavList.js
  sidebar.js
  warehouse-actions/setting-connections-using-models.mdx
Labels: Good to go!

#405 Timestamp Docs Enhancement
  data-warehouse-integrations/warehouse-schemas.mdx
  rudderstack-api/api-specification/rudderstack-spec/common-fields.mdx
  rudderstack-api/http-api.mdx
Labels: Good to go!

#422 Event Replay feature
  event-replay.mdx
Labels: Good to go!

#432 Event replay - content and sidebar updates
  postNavList.js
  sidebar.js
  user-guides/administrators-guide/event-replay.mdx
Labels: Good to go!

#433 Warehouse Actions features - Image URL fixes
  warehouse-actions/features/airflow-provider.mdx
  warehouse-actions/features/visual-data-mapper.mdx
Labels: Good to go!

#434 AdWords Remarketing List code formatting
  destinations/advertising/google-adwords-remarketing-list.mdx
Labels: Good to go!

#436 Google Ads Remarketing Lists: hotfix - correct example payload
  destinations/advertising/google-adwords-remarketing-list.mdx
Labels: Good to go!

#435 Models topic rename and formatting changes
  connections/models.mdx
  postNavList.js
  sidebar.js
  warehouse-actions/features/index.mdx
  warehouse-actions/features/setting-connections-using-models.mdx
Labels: Good to go!

#431 Google Analytics - clarity on clientId
  assets/event-stream-destinations/ga-md5-encryption-disabled.png
  destinations/analytics/google-analytics-ga.mdx
Labels: Good to go!

#438 Ignore 'Last seen' property
  destinations/analytics/mixpanel.mdx
Labels: Ready for review

#406 Adobe Analytics Cloud Mode Update
  assets/adobe-1.png
  assets/adobe-2.png
  assets/adobe-3.png
  assets/image (105).png
  assets/image (107).png
  assets/image (108).png
  assets/image (109).png
  assets/image (110).png
  assets/image (111).png
  assets/mapping-adobe.png
  destinations/analytics/adobe-analytics/setting-up-adobe-analytics-in-rudderstack.mdx
Labels: Internal review

#437 .NET SDK implementation in the Segment-RudderStack migration guide
  assets/user-guides/segment-rudder-migration-dotnet-dependencies.png
  user-guides/migration-guides/rudderstack-migration-guide.mdx
Labels: Good to go!

#439 FB Pixel documentation update
  assets/event-stream-destinations/fb-pixel-connection-settings-1.png
  assets/event-stream-destinations/fb-pixel-connection-settings-2.png
  assets/event-stream-destinations/fb-pixel-connection-settings-3.png
  assets/event-stream-destinations/fb-pixel-connection-settings-4.png
  assets/event-stream-destinations/fb-pixel-connection-settings-5.png
  destinations/advertising/fb-pixel.mdx
  destinations/advertising/google-adwords-remarketing-list.mdx
Labels: Good to go!

#440 Singular docs
  assets/event-stream-destinations/singular-connection-settings.png
  destinations/analytics/singular.mdx
Labels: Good to go!

#441 Live events update
  get-started/live-events.mdx
Labels: Good to go!

#446 PR Template
  .github/pull_request_template.md
Labels: Good to go!

#445 Google Ads Remarketing Lists Update
  destinations/advertising/google-adwords-remarketing-list.mdx
Labels: Good to go!

#447 React Native SDK implementation in Segment-RudderStack migration guide
  user-guides/migration-guides/rudderstack-migration-guide.mdx
Labels: Good to go!

#448 URL fix in Models documentation
  warehouse-actions/features/setting-up-connections-using-models.mdx
Labels: Good to go!

#449 Migration guide hotfix
  user-guides/migration-guides/rudderstack-migration-guide.mdx
Labels: Good to go!

#443 ActiveCampaign documentation update
  assets/event-stream-destinations/activecampaign-connection-settings.png
  destinations/marketing/activecampaign.mdx
Labels: Good to go!

#456 Google Analytics connection settings
  assets/event-stream-destinations/google-analytics-connection-settings-1.png
  assets/event-stream-destinations/google-analytics-connection-settings-2.png
  assets/event-stream-destinations/google-analytics-connection-settings-3.png
  assets/event-stream-destinations/google-analytics-connection-settings-4.png
  assets/event-stream-destinations/google-analytics-connection-settings-5.png
  assets/event-stream-destinations/google-analytics-connection-settings-6.png
  assets/event-stream-destinations/google-analytics-connection-settings-7.png
  assets/event-stream-destinations/google-analytics-connection-settings-8.png
  destinations/analytics/google-analytics-ga.mdx
Labels: Internal review

#297 Braze Currents documentation
  assets/event-stream-sources/braze-1.png
  assets/event-stream-sources/braze-2.png
  stream-sources/braze-currents.mdx
Labels: Good to go!

#444 Snowflake documentation update
  assets/warehouse-actions-sources/add-constant-in-json.png
  assets/warehouse-actions-sources/add-destination-1.png
  assets/warehouse-actions-sources/add-destination.png
  assets/warehouse-actions-sources/dot-notation-constant.png
  assets/warehouse-actions-sources/permissions-error.png
  assets/warehouse-actions-sources/schema-tab-options.png
  assets/warehouse-actions-sources/select-source.png
  assets/warehouse-actions-sources/snowflake-accountadmin.png
  assets/warehouse-actions-sources/snowflake-source.png
  assets/warehouse-actions-sources/update-table-selection-old.png
  assets/warehouse-actions-sources/update-table-selection.png
  assets/warehouse-actions-sources/validations.png
  warehouse-actions/common-settings/importing-data-using-tables.mdx
  warehouse-actions/common-settings/sync-modes.mdx
  warehouse-actions/snowflake.mdx
Labels: Good to go!

#451 Clickhouse revamp
  assets/warehouse-actions-sources/clickhouse-additional-settings.png
  assets/warehouse-actions-sources/clickhouse-connection-settings.png
  warehouse-actions/clickhouse.mdx
Labels: Good to go!

#458 S3 Documentation Revamp
  warehouse-actions/amazon-s3.mdx
Labels: Good to go!

#454 Airflow Documentation Updates
  assets/warehouse-actions-sources/source-id.png
  warehouse-actions/features/airflow-provider.mdx
Labels: Good to go!

#453 Google Bigquery revamp
  assets/warehouse-actions-sources/GCP-create-role.png
  assets/warehouse-actions-sources/GCP-service-account.png
  assets/warehouse-actions-sources/bigquery-connection-settings.png
  assets/warehouse-actions-sources/create-new-key.png
  assets/warehouse-actions-sources/gcp-add-key.png
  assets/warehouse-actions-sources/gcp-create-service-account.png
  assets/warehouse-actions-sources/gcp-role-details.png
  assets/warehouse-actions-sources/gcp-service-account-details.png
  assets/warehouse-actions-sources/gcp-service-account-role-details.png
  assets/warehouse-actions-sources/image2.png
  assets/warehouse-actions-sources/manage-keys.png
  warehouse-actions/google-bigquery.mdx
Labels: Good to go!

#457 Warehouse Actions landing page
  warehouse-actions/faq.mdx
  warehouse-actions/index.mdx
Labels: Good to go!

#450 PostgreSQL WH Source Documentation Update
  assets/warehouse-actions-sources/postgresql-add-desitnation.png
  assets/warehouse-actions-sources/postgresql-source.png
  warehouse-actions/postgresql.mdx
Labels: Good to go!

#460 Warehouse Actions FAQ update
  warehouse-actions/faq.mdx
Labels: Good to go!

#455 Singular Documentation Updates
  assets/event-stream-destinations/singular-api-key.png
  destinations/analytics/singular.mdx
Labels: Good to go!

#459 Visual data mapper revamp
  assets/vdm-1.png
  assets/vdm-2.png
  assets/warehouse-actions-sources/vdm-2.png
  assets/warehouse-actions-sources/vdm-3.png
  assets/warehouse-actions-sources/vdm-4.png
  assets/warehouse-actions-sources/vdm-5.png
  assets/warehouse-actions-sources/vdm-6.png
  assets/warehouse-actions-sources/vdm-7.png
  assets/warehouse-actions-sources/vdm-model.png
  assets/warehouse-actions-sources/vdm-object.png
  warehouse-actions/features/visual-data-mapper.mdx
Labels: Good to go!

#467 Intercom Update
  destinations/business-messaging/intercom.mdx
Labels: Good to go!

#461 PostHog documentation updates
  assets/event-stream-destinations/posthog-additional-settings.png
  assets/event-stream-destinations/posthog-connection-settings.png
  assets/event-stream-destinations/posthog-updated-group-mapping.png
  assets/event-stream-destinations/posthog-web-sdk-settings.png
  destinations/analytics/posthog.mdx
Labels: Good to go!

#462 Track screen recording
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.mdx
Labels: Good to go!

#465 Google AdWords Enhanced Conversions documentation
  assets/event-stream-destinations/enhanced-conversions-connection-settings.png
  destinations/advertising/google-adwords-enhanced-conversions.mdx
Labels: Good to go!

#468 Salesforce documentation update
  destinations/crm/salesforce.mdx
Labels: Internal review

#466 Flush and Periodic Work Requests
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/add-an-application-class-to-you-android-application.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/flushing-events-periodically.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
Labels: Good to go!

#471 RudderStack to MoEngage mappings
  destinations/marketing/moengage.mdx
Labels: Good to go!

#470 Data type for category field
  destinations/advertising/fb-pixel.mdx
Labels: Ready for review

#469 Supported destinations and sync modes update
  assets/warehouse-actions-sources/mirror-mode.png
  assets/warehouse-actions-sources/sync-schedule-basic.png
  assets/warehouse-actions-sources/sync-schedule-cron-error.png
  assets/warehouse-actions-sources/sync-schedule-cron.png
  assets/warehouse-actions-sources/sync-schedule-manual.png
  assets/warehouse-actions-sources/upsert-mode.png
  reverse-etl/common-settings/sync-modes.mdx
  reverse-etl/common-settings/sync-schedule-settings.mdx
  reverse-etl/features/visual-data-mapper.mdx
Labels: Good to go!

#475 Salesforce doc update
  assets/event-stream-destinations/salesforce-connection-settings.png
  destinations/crm/salesforce.mdx
Labels: Good to go!

#442 RS cloud vs open-source docs
  get-started/cloud-vs-open-source.mdx
Labels: Good to go!

#474 Update JS SDK using NPM and browser versions update
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/quick-start-guide.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/version-migration-guide.mdx
Labels: Good to go!

#472 Data storage JavaScript SDK
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/data-storage-cookies.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
Labels: Good to go!

#478 JS SDK documentation formatting hotfix
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/data-storage-cookies.mdx
Labels: Good to go!

#476 Updated JS SDK v1 to v1.1
  data-governance/rudder-typer.mdx
  data-governance/ruddertyper.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/javascript-sdk-enhancements.mdx
  user-guides/how-to-guides/custom-domains.mdx
  user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-angular-integration.mdx
  user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-hugo-integration.mdx
  user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-jekyll-integration.mdx
  user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-nextjs-integration.mdx
  user-guides/migration-guides/rudderstack-migration-guide.mdx
Labels: Ready for review

#479 Shopify remove beta badge
  stream-sources/shopify.mdx
Labels: Good to go!

#482 ActiveCampaign Documentation Updates
  destinations/marketing/activecampaign.mdx
Labels: Ready for review

#483 Open Source vs Cloud feedback incorporated
  get-started/cloud-vs-open-source.mdx
Labels: Good to go!

#484 Flutter v2 Screen Updates
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/flutter-v2.mdx
Labels: Good to go!

#480 Add MoEngage to React Native app
  destinations/marketing/moengage.mdx
Labels: Good to go!

#481 Airship documentation
  assets/event-stream-destinations/airship-app-key-secret.png
  assets/event-stream-destinations/airship-connection-settings.png
  assets/event-stream-destinations/airship-create-new-token.png
  assets/event-stream-destinations/new-attribute-airship.png
  destinations/marketing/airship.mdx
Labels: Good to go!

#485 Custom domains documentation update
  assets/user-guides/custom-domains/custom-domains-1.png
  assets/user-guides/custom-domains/custom-domains-2.png
  assets/user-guides/custom-domains/custom-domains-3.png
  assets/user-guides/custom-domains/custom-domains-4.png
  assets/user-guides/custom-domains/custom-domains-5.png
  assets/user-guides/custom-domains/custom-domains-6.png
  assets/user-guides/custom-domains/custom-domains-7.png
  assets/user-guides/custom-domains/custom-domains-8.png
  user-guides/how-to-guides/custom-domains.mdx
Labels: Good to go!
