Repository rudderlabs/rudderstack-docs, pull requests merged in 2022-10, with the labels that each got.

#932 Extract source patch and other hotfixes
  docs/sources/extract/zendesk-support.mdx
Labels: Good to go!

#918 Engage.so destination documentation
  docs/assets/event-stream-destinations/engage-public-private-key.png
  docs/destinations/streaming-destinations/engage/engage-cloud-mode.mdx
  docs/destinations/streaming-destinations/engage/engage-device-mode.mdx
  docs/destinations/streaming-destinations/engage/index.mdx
  docs/destinations/streaming-destinations/engage/setting-up-engage.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Do not merge, Good to go!

#933 Google Analytics V2 Cloud Extract doc
  docs/assets/cloud-extract-sources/delete-custom-report.png
  docs/assets/cloud-extract-sources/edit-custom-report.png
  docs/assets/cloud-extract-sources/ga-custom-report.png
  docs/assets/cloud-extract-sources/ga-oauth-settings-2.png
  docs/assets/cloud-extract-sources/ga-oauth-settings-3.png
  docs/assets/cloud-extract-sources/ga-oauth-settings-4.png
  docs/assets/cloud-extract-sources/ga-oauth-settings.png
  docs/assets/cloud-extract-sources/ga-resources.png
  docs/sources/extract/google-analytics-v2.mdx
  docs/sources/extract/google-analytics.mdx
  src/data/sources.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#907 Hubspot doc refactor
  docs/assets/event-stream-destinations/hubspot-connection-settings-2.png
  docs/assets/event-stream-destinations/hubspot-connection-settings-auth-type-1.png
  docs/assets/event-stream-destinations/hubspot-connection-settings-auth-type-2.png
  docs/assets/event-stream-destinations/hubspot-connection-settings.png
  docs/assets/event-stream-destinations/hubspotv2-connection-settings-2.png
  docs/assets/event-stream-destinations/hubspotv2-connection-settings-3.png
  docs/assets/event-stream-destinations/object-hubspot.png
  docs/assets/event-stream-destinations/predefined_object_hubspot.png
  docs/assets/event-stream-destinations/sync-associations-hubspot.png
  docs/assets/event-stream-destinations/unique-identifier-hubspot-1.png
  docs/assets/event-stream-destinations/unique-identifier-hubspot.png
  docs/destinations/streaming-destinations/hubspot-v2.mdx
  docs/destinations/streaming-destinations/hubspot.mdx
  docs/destinations/streaming-destinations/hubspot/connect-reverse-etl-source.mdx
  docs/destinations/streaming-destinations/hubspot/hubspot-cloud-mode/hubspot-legacy-api-cloud.mdx
  docs/destinations/streaming-destinations/hubspot/hubspot-cloud-mode/hubspot-new-api-cloud.mdx
  docs/destinations/streaming-destinations/hubspot/hubspot-cloud-mode/index.mdx
  docs/destinations/streaming-destinations/hubspot/hubspot-device-mode.mdx
  docs/destinations/streaming-destinations/hubspot/index.mdx
  docs/destinations/streaming-destinations/hubspot/setting-up-hubspot-in-rudderstack.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#925 Mixpanel resources update
  docs/sources/extract/mixpanel-v2.mdx
Labels: Good to go!

#935 Google ads offline conversion doc
  docs/assets/event-stream-destinations/gads-custom-variable.png
  docs/destinations/streaming-destinations/google-adwords-offline-conversions.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Ready for review

#934 Event Replay FAQ
  docs/user-guides/administrators-guide/event-replay.mdx
Labels: Good to go!

#931 RudderStack IAM role for AWS-based destinations
  docs/assets/destinations/aws-role-1.png
  docs/assets/destinations/aws-role-2.png
  docs/assets/destinations/aws-role-3.png
  docs/assets/destinations/aws-role-4.png
  docs/assets/destinations/aws-role-5.png
  docs/assets/destinations/aws-role-6.png
  docs/assets/rs-cloud/rudderstack-workspace-id.png
  docs/assets/rs-cloud/workspace-token-reveal.png
  docs/dashboard-guides/overview.mdx
  docs/destinations/aws-iam-role-for-rudderstack.mdx
  docs/destinations/streaming-destinations/amazon-eventbridge.mdx
  docs/destinations/streaming-destinations/amazon-kinesis-firehose.mdx
  docs/destinations/streaming-destinations/amazon-kinesis.mdx
  docs/destinations/streaming-destinations/aws-lambda.mdx
  docs/destinations/streaming-destinations/aws-personalize.mdx
  docs/resources/glossary.mdx
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#919 June destination
  docs/assets/event-stream-destinations/june-dashboard.png
  docs/destinations/streaming-destinations/june/index.mdx
  docs/destinations/streaming-destinations/june/june-cloud-mode.mdx
  docs/destinations/streaming-destinations/june/june-device-mode.mdx
  docs/destinations/streaming-destinations/june/setting-up-june-in-rudderstack.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#939 GA Offline Conversion enhancements
  docs/assets/event-stream-destinations/gads-track-conversion.png
  docs/assets/event-stream-destinations/gads-upload-conversion.png
  docs/destinations/streaming-destinations/google-adwords-offline-conversions.mdx
  src/data/destinations.yaml
Labels: Good to go!

#915 Control Plane Lite documentation update
  docs/assets/rudderstack-open-source/control-plane-lite-dashboard.png
  docs/get-started/rudderstack-open-source/control-plane-lite.mdx
  docs/sources/event-streams/sdks/rudderstack-android-sdk/index.mdx
  docs/sources/event-streams/sdks/rudderstack-flutter-sdk/flutter-v1.mdx
  docs/sources/event-streams/sdks/rudderstack-flutter-sdk/flutter-v2.mdx
  docs/sources/event-streams/sdks/rudderstack-flutter-sdk/index.mdx
  docs/sources/event-streams/sdks/rudderstack-ios-sdk/index.mdx
  docs/sources/event-streams/sdks/rudderstack-ios-sdk/ios-v2.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
  docs/sources/event-streams/sdks/rudderstack-unity-sdk.mdx
Labels: Good to go!

#937 Update README and Contributing guide
  CONTRIBUTING.mdx
  README.mdx
Labels: WIP

#946 Session ID in Amplitude
  docs/sources/event-streams/sdks/session-tracking/index.mdx
Labels: Ready for review

#943 Mailjet documentation
  docs/assets/event-stream-destinations/mailjet-apikey-secret.png
  docs/assets/event-stream-destinations/mailjet-contactlistid.png
  docs/destinations/streaming-destinations/mailjet.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Review in progress

#944 Mailjet source doc
  docs/assets/event-stream-sources/mailjet-src-settings.png
  docs/assets/event-stream-sources/mailjet-webhook.png
  docs/sources/event-streams/cloud-apps/mailjet.mdx
  src/data/sources.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#945 Clevertap alias call support
  docs/destinations/streaming-destinations/clevertap.mdx
Labels: Good to go!

#947 Fb pixel update
  docs/destinations/streaming-destinations/fb-pixel.mdx
Labels: Good to go!

#926 GA: Missing info
  docs/destinations/streaming-destinations/google-analytics-ga.mdx
Labels: Good to go!

#948 Iterable web device mode documentation
  docs/assets/event-stream-destinations/iterable-getinappmessages.png
  docs/assets/event-stream-destinations/iterable-purchaseevents.png
  docs/assets/event-stream-destinations/web-push-notifications-iterable.png
  docs/destinations/streaming-destinations/iterable/index.mdx
  docs/destinations/streaming-destinations/iterable/iterable-cloud-mode.mdx
  docs/destinations/streaming-destinations/iterable/iterable-device-mode.mdx
  docs/destinations/streaming-destinations/iterable/setting-up-iterable.mdx
  src/sidebar.js
Labels: Good to go!

#942 Documentation for Flutter Device Mode
  docs/destinations/streaming-destinations/adjust.mdx
  docs/destinations/streaming-destinations/amplitude.mdx
  docs/destinations/streaming-destinations/appcenter.mdx
  docs/destinations/streaming-destinations/braze.mdx
  docs/destinations/streaming-destinations/firebase.mdx
  docs/destinations/streaming-destinations/leanplum.mdx
Labels: Good to go!

#904 Update DESTINATION_TEMPLATE.mdx
  DESTINATION_TEMPLATE.mdx
Labels: Review in progress

#950 Device mode transformations doc
  docs/assets/features/device-mode-transformations-workflow.png
  docs/features/transformations/cloud-mode-transformations.mdx
  docs/features/transformations/device-mode-transformations.mdx
  docs/features/transformations/faq.mdx
  docs/features/transformations/index.mdx
  docs/features/transformations/using-libraries.mdx
  docs/get-started/cloud-vs-open-source.mdx
  src/postNavList.js
  src/sidebar.js
Labels: Ready for review

#951 Braze doc update
  docs/destinations/streaming-destinations/braze.mdx
Labels: Ready for review

#957 Yandex.Metrica destination documentation
  docs/assets/event-stream-destinations/yandex-metrica-container-name.png
  docs/assets/event-stream-destinations/yandex-metrica-goal-id.png
  docs/assets/event-stream-destinations/yandex-metrica-tag-id.png
  docs/destinations/streaming-destinations/yandex-metrica.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#955 Snowplow migration doc
  docs/user-guides/migration-guides/snowplow-migration-guide.mdx
  src/sidebar.js
Labels: Ready for review

#960 Looker source updates
  docs/assets/event-stream-sources/looker-4.png
  docs/sources/event-streams/cloud-apps/looker.mdx
Labels: Good to go!

#962 Klaviyo extract source documentation
  docs/assets/cloud-extract-sources/klaviyo-connection-settings-2.png
  docs/assets/cloud-extract-sources/klaviyo-connection-settings.png
  docs/sources/extract/klaviyo.mdx
  src/data/sources.yaml
  src/sidebar.js
Labels: Good to go!

#954 content_type enhancement in FB Offline Conversions
  docs/destinations/streaming-destinations/fb-offline-conversions.mdx
Labels: Good to go!

#963 Personal Access Tokens documentation update
  docs/assets/rudderstack-api/new-personal-access-token.png
  docs/assets/rudderstack-api/personal-access-token-1.png
  docs/assets/rudderstack-api/personal-access-token-2.png
  docs/assets/rudderstack-api/personal-access-token-3.png
  docs/assets/rudderstack-api/personal-access-tokens-1.png
  docs/assets/rudderstack-api/personal-access-tokens-2.png
  docs/assets/rudderstack-api/personal-access-tokens-3.png
  docs/dashboard-guides/personal-access-token.mdx
Labels: Ready for review

#966 Broken links fix
  docs/destinations/streaming-destinations/mailmodo.mdx
  docs/destinations/streaming-destinations/pinterest-ads/pinterest-ads-cloud-mode.mdx
  docs/destinations/streaming-destinations/pinterest-ads/setting-up-pinterest-ads.mdx
  docs/sources/event-streams/cloud-apps/clickup.mdx
  docs/sources/event-streams/sdks/session-tracking/faq.mdx
Labels: Ready for review

#958 Refiner documentation
  docs/assets/event-stream-destinations/refiner-rest-api-key.png
  docs/assets/event-stream-destinations/refiner-web-client-api-key.png
  docs/destinations/streaming-destinations/refiner/index.mdx
  docs/destinations/streaming-destinations/refiner/refiner-cloud-mode.mdx
  docs/destinations/streaming-destinations/refiner/refiner-device-mode.mdx
  docs/destinations/streaming-destinations/refiner/setting-up-refiner.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#890 SAS tokens documentation
  docs/assets/dw-integrations/azure-data-lake-connection-settings-1.png
  docs/assets/dw-integrations/azure-data-lake-connection-settings-2.png
  docs/assets/dw-integrations/azure-sas-token.png
  docs/assets/dw-integrations/synapse-connection-settings-1.png
  docs/assets/dw-integrations/synapse-connection-settings-2.png
  docs/assets/event-stream-destinations/azure-blob-storage-connection-1.png
  docs/assets/event-stream-destinations/azure-blob-storage-connection-2.png
  docs/assets/event-stream-destinations/sas-token-permissions.png
  docs/destinations/streaming-destinations/microsoft-azure-blob-storage.mdx
  docs/destinations/warehouse-destinations/azure-datalake.mdx
  docs/destinations/warehouse-destinations/azure-synapse.mdx
  docs/destinations/warehouse-destinations/delta-lake.mdx
  docs/destinations/warehouse-destinations/faq.mdx
  docs/destinations/warehouse-destinations/sql-server.mdx
Labels: Good to go!

#971 Iframe tag support for DCM web device mode
  docs/assets/event-stream-destinations/dcm-floodlight-connection-settings4-new.png
  docs/destinations/streaming-destinations/dcm-floodlight/dcm-floodlight-device-mode.mdx
  docs/destinations/streaming-destinations/dcm-floodlight/setting-up-dcm-floodlight-in-rudderstack.mdx
Labels: Good to go!

#972 Refiner source
  docs/assets/event-stream-sources/refiner-dashboard-webhook.png
  docs/assets/event-stream-sources/refiner-webhook-url.png
  docs/sources/event-streams/cloud-apps/refiner.mdx
  src/data/sources.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#974 Remove refs to salesforce flag
  docs/destinations/streaming-destinations/salesforce.mdx
Labels: Ready for review
