Repository rudderlabs/rudderstack-docs, pull requests merged in 2022-06, with the labels that each got.

#627 Warehouse FAQ update
  docs/data-warehouse-integrations/warehouse-faqs.mdx
Labels: Ready for review

#622 GA4- Added info on payload parameters
  docs/destinations/analytics/google-analytics-4/google-analytics-4-cloud-mode.mdx
Labels: Internal review

#624 Shopify best practices
  docs/stream-sources/shopify.mdx
Labels: Good to go!

#628 Amplitude - iOS v2 device mode update
  docs/destinations/analytics/amplitude.mdx
Labels: Ready for review

#633 Standardize pro/enterprise labels across docs
  docs/data-governance/index.mdx
  docs/data-governance/rudder-typer.mdx
  docs/data-governance/rudderstack-data-governance-api.mdx
  docs/data-governance/ruddertyper.mdx
  docs/data-governance/tracking-plans/index.mdx
  docs/identity-resolution.mdx
  docs/rudderstack-api/data-regulation-api.mdx
  docs/rudderstack-cloud/audit-logs.mdx
  docs/user-guides/administrators-guide/onelogin-sso.mdx
  docs/user-guides/administrators-guide/rudderstack-grafana-dashboard.mdx
Labels: Good to go!

#642 Updated redirect links
  netlify.toml
Labels: Ready for review

#643 Identity Resolution doc updates
  docs/identity-resolution.mdx
Labels: Good to go!

#644 Workspace token updates
  docs/assets/rs-cloud/workspace-token.png
  docs/assets/rudderstack-open-source/write-key.png
  docs/faqs.mdx
  docs/get-started/glossary.mdx
  docs/rudderstack-cloud/dashboard-overview.mdx
  docs/rudderstack-open-source/installing-and-setting-up-rudderstack/developer-machine-setup.mdx
  docs/rudderstack-open-source/installing-and-setting-up-rudderstack/docker.mdx
  docs/rudderstack-open-source/installing-and-setting-up-rudderstack/kubernetes.mdx
  docs/rudderstack-open-source/installing-and-setting-up-rudderstack/sending-test-events.mdx
Labels: Internal review

#623 DCM Floodlight - Device mode updates
  docs/assets/event-stream-destinations/counter-tag.png
  docs/assets/event-stream-destinations/dcm-floodlight-connection-settings3.png
  docs/assets/event-stream-destinations/dcm-floodlight-connection-settings4.png
  docs/assets/event-stream-destinations/sales-tag.png
  docs/destinations/advertising/dcm-floodlight/dcm-floodlight-cloud-mode.mdx
  docs/destinations/advertising/dcm-floodlight/dcm-floodlight-device-mode.mdx
  docs/destinations/advertising/dcm-floodlight/index.mdx
  docs/destinations/advertising/dcm-floodlight/setting-up-dcm-floodlight-in-rudderstack.mdx
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#632 Azure Synapse fixes
  docs/data-warehouse-integrations/azure-synapse.mdx
Labels: Good to go!

#645 Adjust documentation updates
  docs/destinations/attribution/adjust.mdx
Labels: Good to go!

#652 Namespace warehouse FAQ tweaks
  docs/assets/dw-integrations/namespace-example.png
  docs/data-warehouse-integrations/warehouse-faqs.mdx
Labels: Good to go!

#649 AWS Personalize: Revamp and add connection setting
  docs/assets/event-stream-destinations/personalize-1.png
  docs/assets/event-stream-destinations/personalize-2.png
  docs/destinations/analytics/aws-personalize.mdx
Labels: Good to go!

#651 Allow/Denylist
  docs/cloud-extract-sources/netsuite.mdx
  docs/data-warehouse-integrations/amazon-redshift.mdx
  docs/data-warehouse-integrations/azure-datalake.mdx
  docs/data-warehouse-integrations/azure-synapse.mdx
  docs/data-warehouse-integrations/clickhouse.mdx
  docs/data-warehouse-integrations/delta-lake.mdx
  docs/data-warehouse-integrations/gcs-datalake.mdx
  docs/data-warehouse-integrations/google-bigquery.mdx
  docs/data-warehouse-integrations/microsoft-sql-server.mdx
  docs/data-warehouse-integrations/postgresql.mdx
  docs/data-warehouse-integrations/s3-datalake.mdx
  docs/data-warehouse-integrations/snowflake.mdx
  docs/data-warehouse-integrations/warehouse-faqs.mdx
  docs/destinations/advertising/fb-pixel.mdx
  docs/destinations/analytics/posthog.mdx
  docs/destinations/attribution/tvsquared.mdx
  docs/destinations/business-messaging/slack.mdx
  docs/destinations/marketing/activecampaign.mdx
  docs/faqs.mdx
  docs/stream-sources/rudderstack-sdk-integration-guides/event-filtering.mdx
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/flutter-v2.mdx
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/index.mdx
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.mdx
  docs/stream-sources/rudderstack-sdk-integration-guides/sdk-faqs.mdx
  docs/user-guides/how-to-guides/custom-domains.mdx
  docs/user-guides/how-to-guides/filter-events.mdx
Labels: Good to go!

#648 Singular iOS v2 device mode updates
  docs/destinations/analytics/singular.mdx
Labels: Good to go!

#647 Adjust device mode integration for iOS v2
  docs/destinations/attribution/adjust.mdx
Labels: Good to go!

#646 App Center device mode integration steps for iOS v2
  docs/destinations/continuous-integration/appcenter.mdx
Labels: Good to go!

#650 OneLogin SSO documentation updates
  docs/assets/user-guides/onelogin-1.png
  docs/assets/user-guides/onelogin-10.png
  docs/assets/user-guides/onelogin-2.png
  docs/assets/user-guides/onelogin-3.png
  docs/assets/user-guides/onelogin-4.png
  docs/assets/user-guides/onelogin-5.png
  docs/assets/user-guides/onelogin-6.png
  docs/assets/user-guides/onelogin-7.png
  docs/assets/user-guides/onelogin-8.png
  docs/assets/user-guides/onelogin-9.png
  docs/user-guides/administrators-guide/onelogin-sso.mdx
Labels: Good to go!

#654 iOS v2 push notifications support
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
Labels: Good to go!

#663 Netsuite and Event Replay: Minor content changes
  docs/cloud-extract-sources/netsuite.mdx
  docs/user-guides/administrators-guide/event-replay.mdx
Labels: Good to go!

#660 Warehouse FAQ updates
  docs/data-warehouse-integrations/gcs-datalake.mdx
  docs/data-warehouse-integrations/warehouse-faqs.mdx
  docs/destinations/marketing/attentive-tag.mdx
Labels: Good to go!

#664 AppsFlyer iOS v2 device mode updates
  docs/destinations/attribution/appsflyer.mdx
Labels: Good to go!

#667 Customer.io documentation updates
  docs/destinations/marketing/customer.io.mdx
Labels: Good to go!

#665 MoEngage iOS v2 device mode updates
  docs/assets/event-stream-destinations/moengage-background-mode.png
  docs/destinations/marketing/moengage.mdx
Labels: Good to go!

#668 GH Badge cleanup
  README.mdx
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/flutter-v1.mdx
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ruby-sdk.mdx
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-rust-sdk.mdx
  docs/user-guides/administrators-guide/okta-sso.mdx
Labels: Ready for review

#666 Tracking plan API doc
  docs/data-governance/tracking-plans/index.mdx
  docs/data-warehouse-integrations/warehouse-schemas.mdx
  docs/rudderstack-api/tracking-plan-api.mdx
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#661 Updated DCM floodlight - minor changes
  docs/assets/event-stream-destinations/dcm-floodlight-connection-settings2.png
  docs/destinations/advertising/dcm-floodlight/dcm-floodlight-device-mode.mdx
Labels: Good to go!

#669 Yahoo DSP integration doc
  docs/assets/event-stream-destinations/yahoo-dsp-2.png
  docs/assets/event-stream-destinations/yahoo-dsp-3.png
  docs/assets/event-stream-destinations/yahoo-dsp-connection-settings-2.png
  docs/assets/event-stream-destinations/yahoo-dsp-connection-settings-3.png
  docs/assets/event-stream-destinations/yahoo-dsp-connection-settings.png
  docs/assets/event-stream-destinations/yahoo-dsp.png
  docs/destinations/advertising/yahoo-dsp.mdx
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#678 Minor changes in DCM
  docs/assets/event-stream-destinations/dcm-floodlight-connection-settings-2.png
  docs/destinations/advertising/dcm-floodlight/dcm-floodlight-device-mode.mdx
  docs/destinations/advertising/dcm-floodlight/setting-up-dcm-floodlight-in-rudderstack.mdx
Labels: Ready for review

#683 Yahoo DSP: Added rate limit for requests
  docs/destinations/advertising/yahoo-dsp.mdx
Labels: Good to go!

#676 GA4 enhancement
  docs/assets/event-stream-destinations/google-analytics-4-connection-settings-1.png
  docs/assets/event-stream-destinations/google-analytics-4-connection-settings-2.png
  docs/assets/event-stream-destinations/google-analytics-4-connection-settings-3.png
  docs/assets/event-stream-destinations/google-analytics-4-connection-settings-4.png
  docs/assets/event-stream-destinations/google-analytics-4-connection-settings.png
  docs/destinations/analytics/google-analytics-4/google-analytics-4-cloud-mode.mdx
  docs/destinations/analytics/google-analytics-4/google-analytics-4-device-mode.mdx
  docs/destinations/analytics/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
Labels: Good to go!

#690 Get started - sidebar updates
  src/sidebar.js
Labels: Good to go!

#658 Databricks Reverse ETL source
  docs/assets/warehouse-actions-sources/connection-settings-databricks-2.png
  docs/assets/warehouse-actions-sources/connection-settings-databricks.png
  docs/assets/warehouse-actions-sources/select-source-databricks.png
  docs/reverse-etl/amazon-s3.mdx
  docs/reverse-etl/common-settings/sync-modes.mdx
  docs/reverse-etl/databricks.mdx
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#694 New nav - API section
  docs/api/data-governance-api.mdx
  docs/api/data-regulation-api.mdx
  docs/api/http-api.mdx
  docs/api/overview.mdx
  docs/api/pixel-api-spec.mdx
  docs/api/test-api.mdx
  docs/api/tracking-plan-api.mdx
  docs/api/transformation-api.mdx
Labels: Ready for review

#693 New nav - Features
  docs/features/data-governance/index.mdx
  docs/features/data-governance/ruddertyper.mdx
  docs/features/data-governance/tracking-plans/index.mdx
  docs/features/data-governance/tracking-plans/tracking-plan-spreadsheet.mdx
  docs/features/identity-resolution.mdx
  docs/features/transformations.mdx
Labels: Good to go!

#691 Event Spec Restructuring
  docs/event-spec/alias.mdx
  docs/event-spec/application-lifecycle-events-spec.mdx
  docs/event-spec/common-fields.mdx
  docs/event-spec/ecommerce-events-spec/browsing.mdx
  docs/event-spec/ecommerce-events-spec/coupons.mdx
  docs/event-spec/ecommerce-events-spec/index.mdx
  docs/event-spec/ecommerce-events-spec/ordering.mdx
  docs/event-spec/ecommerce-events-spec/promotions.mdx
  docs/event-spec/ecommerce-events-spec/reviewing.mdx
  docs/event-spec/ecommerce-events-spec/sharing.mdx
  docs/event-spec/ecommerce-events-spec/wishlisting.mdx
  docs/event-spec/group.mdx
  docs/event-spec/identify.mdx
  docs/event-spec/overview.mdx
  docs/event-spec/page.mdx
  docs/event-spec/screen.mdx
  docs/event-spec/track.mdx
  docs/event-spec/video-events-spec.mdx
Labels: Good to go!

#692 New nav - Dashboard overview
  docs/dashboard-guides/audit-logs.mdx
  docs/dashboard-guides/destinations.mdx
  docs/dashboard-guides/live-events.mdx
  docs/dashboard-guides/overview.mdx
  docs/dashboard-guides/personal-access-token.mdx
  docs/dashboard-guides/sources.mdx
  docs/dashboard-guides/teammates.mdx
  src/sidebar.js
Labels: Good to go!

#697 Resources section revamp
  docs/get-started/rudderstack-architecture.mdx
  docs/resources/community.mdx
  docs/resources/faq.mdx
  docs/resources/glossary.mdx
  docs/resources/index.mdx
  docs/resources/rudderstack-architecture.mdx
Labels: Good to go!

#699 Databricks RETL hotfix
  docs/reverse-etl/databricks.mdx
Labels: Good to go!

#677 Amplitude group call update
  docs/destinations/analytics/amplitude.mdx
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
Labels: Good to go!

#700 Amplitude doc formatting hotfix
  docs/destinations/analytics/amplitude.mdx
Labels: Good to go!

#698 iOS SDK Advertising ID documentation update
  docs/destinations/webhooks.mdx
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
  docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
Labels: Good to go!

#701 Databricks: Generic cloud platform
  docs/reverse-etl/databricks.mdx
Labels: Good to go!

#705 Internal linking: Getting started
  docs/index.mdx
  docs/tmp-get-started/cloud-vs-open-source.mdx
  docs/tmp-get-started/quickstart.mdx
  docs/tmp-get-started/rudderstack-cloud.mdx
  docs/tmp-get-started/rudderstack-open-source/control-plane-lite.mdx
  docs/tmp-get-started/rudderstack-open-source/data-plane-setup/developer-machine-setup.mdx
  docs/tmp-get-started/rudderstack-open-source/data-plane-setup/docker.mdx
  docs/tmp-get-started/rudderstack-open-source/data-plane-setup/index.mdx
  docs/tmp-get-started/rudderstack-open-source/data-plane-setup/kubernetes.mdx
  docs/tmp-get-started/rudderstack-open-source/index.mdx
  docs/tmp-get-started/rudderstack-open-source/sending-test-events.mdx
  docs/tmp-get-started/what-is-rudderstack.mdx
  docs/user-guides/administrators-guide/index.mdx
Labels: Ready for review

#706 Internal Linking: Dashboard guide
  docs/dashboard-guides/audit-logs.mdx
  docs/dashboard-guides/destinations.mdx
  docs/dashboard-guides/live-events.mdx
  docs/dashboard-guides/overview.mdx
  docs/dashboard-guides/personal-access-token.mdx
  docs/dashboard-guides/sources.mdx
  docs/dashboard-guides/teammates.mdx
Labels: Ready for review

#707 Internal Linking: Features
  docs/features/data-governance/index.mdx
  docs/features/data-governance/ruddertyper.mdx
  docs/features/data-governance/tracking-plans/index.mdx
  docs/features/data-governance/tracking-plans/tracking-plan-spreadsheet.mdx
  docs/features/identity-resolution.mdx
  docs/features/transformations.mdx
Labels: Ready for review

#704 Update internal links
  docs/sources/cloud-apps/braze-currents.mdx
  docs/sources/extract/activecampaign.mdx
  docs/sources/extract/chargebee.mdx
  docs/sources/extract/facebook-ads.mdx
  docs/sources/extract/google-adwords.mdx
  docs/sources/extract/google-analytics.mdx
  docs/sources/extract/google-sheets.mdx
  docs/sources/extract/hubspot-v2.mdx
  docs/sources/extract/hubspot/index.mdx
  docs/sources/extract/intercom-v2.mdx
  docs/sources/extract/netsuite.mdx
  docs/sources/extract/sendgrid.mdx
  docs/sources/extract/stripe.mdx
  docs/sources/reverse-etl/amazon-redshift.mdx
  docs/sources/reverse-etl/amazon-s3.mdx
  docs/sources/reverse-etl/clickhouse.mdx
  docs/sources/reverse-etl/common-settings/importing-data-using-models.mdx
  docs/sources/reverse-etl/common-settings/importing-data-using-tables.mdx
  docs/sources/reverse-etl/common-settings/index.mdx
  docs/sources/reverse-etl/common-settings/sync-modes.mdx
  docs/sources/reverse-etl/common-settings/sync-schedule-settings.mdx
  docs/sources/reverse-etl/faq.mdx
  docs/sources/reverse-etl/features/airflow-provider.mdx
  docs/sources/reverse-etl/features/index.mdx
  docs/sources/reverse-etl/features/models.mdx
  docs/sources/reverse-etl/features/visual-data-mapper.mdx
  docs/sources/reverse-etl/google-bigquery.mdx
  docs/sources/reverse-etl/index.mdx
  docs/sources/reverse-etl/mysql.mdx
  docs/sources/reverse-etl/postgresql.mdx
  docs/sources/reverse-etl/snowflake.mdx
  docs/sources/sdks/event-filtering.mdx
  docs/sources/sdks/index.mdx
  docs/sources/sdks/rudderstack-amp-analytics.mdx
  docs/sources/sdks/rudderstack-android-sdk/index.mdx
  docs/sources/sdks/rudderstack-cordova-sdk.mdx
  docs/sources/sdks/rudderstack-dotnet-sdk.mdx
  docs/sources/sdks/rudderstack-flutter-sdk/flutter-v1.mdx
  docs/sources/sdks/rudderstack-flutter-sdk/flutter-v2.mdx
  docs/sources/sdks/rudderstack-flutter-sdk/index.mdx
  docs/sources/sdks/rudderstack-ios-sdk/index.mdx
  docs/sources/sdks/rudderstack-ios-sdk/ios-v2.mdx
  docs/sources/sdks/rudderstack-ios-sdk/macos.mdx
  docs/sources/sdks/rudderstack-ios-sdk/tvOS.mdx
  docs/sources/sdks/rudderstack-ios-sdk/watchOS.mdx
  docs/sources/sdks/rudderstack-javascript-sdk/data-storage-cookies.mdx
  docs/sources/sdks/rudderstack-javascript-sdk/detecting-adblocked-pages.mdx
  docs/sources/sdks/rudderstack-javascript-sdk/index.mdx
  docs/sources/sdks/rudderstack-javascript-sdk/javascript-sdk-enhancements.mdx
  docs/sources/sdks/rudderstack-javascript-sdk/js-sdk-faqs.mdx
  docs/sources/sdks/rudderstack-javascript-sdk/quick-start-guide.mdx
  docs/sources/sdks/rudderstack-javascript-sdk/version-migration-guide.mdx
  docs/sources/sdks/rudderstack-react-native-sdk.mdx
  docs/sources/sdks/rudderstack-rust-sdk.mdx
  docs/sources/sdks/rudderstack-unity-sdk.mdx
  docs/sources/sdks/sdk-faqs.mdx
Labels: Ready for review

#711 Internal Linking: Event specification
  docs/event-spec/application-lifecycle-events-spec.mdx
  docs/event-spec/ecommerce-events-spec/browsing.mdx
  docs/event-spec/ecommerce-events-spec/coupons.mdx
  docs/event-spec/ecommerce-events-spec/ordering.mdx
  docs/event-spec/ecommerce-events-spec/promotions.mdx
  docs/event-spec/ecommerce-events-spec/reviewing.mdx
  docs/event-spec/ecommerce-events-spec/sharing.mdx
  docs/event-spec/ecommerce-events-spec/wishlisting.mdx
  docs/event-spec/standard-events/alias.mdx
  docs/event-spec/standard-events/common-fields.mdx
  docs/event-spec/standard-events/group.mdx
  docs/event-spec/standard-events/identify.mdx
  docs/event-spec/standard-events/index.mdx
  docs/event-spec/standard-events/page.mdx
  docs/event-spec/standard-events/screen.mdx
  docs/event-spec/standard-events/track.mdx
  docs/event-spec/video-events-spec.mdx
Labels: Ready for review

#710 Internal linking: API
  docs/api/data-governance-api.mdx
  docs/api/data-regulation-api.mdx
  docs/api/http-api.mdx
  docs/api/overview.mdx
  docs/api/pixel-api-spec.mdx
  docs/api/test-api.mdx
  docs/api/tracking-plan-api.mdx
  docs/api/transformation-api.mdx
  src/sidebar.js
Labels: Ready for review

#708 Internal Linking: Resources
  docs/resources/community.mdx
  docs/resources/faq.mdx
  docs/resources/glossary.mdx
  docs/resources/rudderstack-architecture.mdx
Labels: Ready for review

#712 Internal Linking: User Guides
  docs/user-guides/administrators-guide/admin-troubleshooting-guide.mdx
  docs/user-guides/administrators-guide/alerting.mdx
  docs/user-guides/administrators-guide/bucket-configuration-settings.mdx
  docs/user-guides/administrators-guide/config-parameters.mdx
  docs/user-guides/administrators-guide/event-replay.mdx
  docs/user-guides/administrators-guide/high-availability.mdx
  docs/user-guides/administrators-guide/horizontal-scaling-1.mdx
  docs/user-guides/administrators-guide/index.mdx
  docs/user-guides/administrators-guide/infra-provisioning.mdx
  docs/user-guides/administrators-guide/monitoring-and-metrics.mdx
  docs/user-guides/administrators-guide/okta-sso.mdx
  docs/user-guides/administrators-guide/onelogin-sso.mdx
  docs/user-guides/administrators-guide/rudderstack-grafana-dashboard.mdx
  docs/user-guides/administrators-guide/software-releases.mdx
  docs/user-guides/how-to-guides/create-a-new-destination-transformer-for-rudder/best-practices-for-coding-transformation-functions-in-javascript.mdx
  docs/user-guides/how-to-guides/create-a-new-destination-transformer-for-rudder/index.mdx
  docs/user-guides/how-to-guides/custom-domains.mdx
  docs/user-guides/how-to-guides/developing-integrations-for-rudderstack.mdx
  docs/user-guides/how-to-guides/dynamic-destination-configuration.mdx
  docs/user-guides/how-to-guides/filter-events.mdx
  docs/user-guides/how-to-guides/how-to-filter-selective-destinations.mdx
  docs/user-guides/how-to-guides/how-to-submit-an-integration-pull-request.mdx
  docs/user-guides/how-to-guides/implement-native-js-sdk-integration/add-device-mode-sdk-to-js.mdx
  docs/user-guides/how-to-guides/implement-native-js-sdk-integration/index.mdx
  docs/user-guides/how-to-guides/index.mdx
  docs/user-guides/how-to-guides/live-destination-event-debugger.mdx
  docs/user-guides/how-to-guides/rudderstack-jamstack-integration/index.mdx
  docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-angular-integration.mdx
  docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-astro-integration.mdx
  docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-eleventy-integration.mdx
  docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-ember-integration.mdx
  docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-gatsby-integration.mdx
  docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-hugo-integration.mdx
  docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-jekyll-integration.mdx
  docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-nextjs-integration.mdx
  docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-nuxtjs-integration.mdx
  docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-svelte-integration.mdx
  docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-vue-integration.mdx
  docs/user-guides/how-to-guides/using-aws-lambda-functions-with-rudderstack.mdx
  docs/user-guides/index.mdx
  docs/user-guides/migration-guides/blendo-rudderstack-migration.mdx
  docs/user-guides/migration-guides/how-to-migrate-warehouse-destination-from-segment-to-rudderstack.mdx
  docs/user-guides/migration-guides/index.mdx
  docs/user-guides/migration-guides/rudderstack-migration-guide.mdx
Labels: Good to go!

#713 Netlify redirects
  netlify.toml
Labels: Good to go!
