Repository rudderlabs/rudderstack-docs, pull requests merged in 2022-08, with the labels that each got.

#745 Kafka documentation update
  docs/assets/event-stream-destinations/kafka-connection-settings.png
  docs/destinations/streaming-destinations/kafka.mdx
Labels: Good to go!

#795 TikTok Ads updates
  docs/destinations/streaming-destinations/tiktok-ads.mdx
Labels: Good to go!

#799 Minor addition in source types
  docs/get-started/quickstart.mdx
  docs/sources/cloud-apps/index.mdx
Labels: Ready for review

#800 Added Mixpanel FAQ
  docs/destinations/streaming-destinations/mixpanel.mdx
Labels: Good to go!

#786 HubSpot V2 doc
  docs/assets/event-stream-destinations/Hubspot-access-token.png
  docs/assets/event-stream-destinations/hubspot-connection-settings-1.png
  docs/assets/event-stream-destinations/hubspot-connection-settings-2.png
  docs/assets/event-stream-destinations/hubspot-connection-settings-3.png
  docs/assets/event-stream-destinations/hubspotv2-connection-settings-1.png
  docs/assets/event-stream-destinations/hubspotv2-connection-settings-2.png
  docs/assets/event-stream-destinations/hubspotv2-connection-settings-3.png
  docs/destinations/streaming-destinations/hubspot-v2.mdx
  docs/destinations/streaming-destinations/hubspot.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#802 Mouseflow documentation
  docs/assets/event-stream-destinations/mouseflow-connection-settings.png
  docs/assets/event-stream-destinations/mouseflow-dashboard-tags.png
  docs/assets/event-stream-destinations/mouseflow-dashboard-variables.png
  docs/assets/event-stream-destinations/mouseflow-website-id-1.png
  docs/assets/event-stream-destinations/mouseflow-website-id-2.png
  docs/assets/event-stream-destinations/mouseflow-website-id-3.png
  docs/assets/event-stream-destinations/mouseflow-website-id-4.png
  docs/assets/event-stream-destinations/mouseflow-website-id-5.png
  docs/assets/event-stream-destinations/mouseflow-website-id-6.png
  docs/destinations/streaming-destinations/mouseflow.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#812 Minor suggestions re: OneSignal doc
  docs/destinations/streaming-destinations/onesignal.mdx
Labels: Ready for review

#790 OneSignal doc
  docs/assets/event-stream-destinations/onesignal-app-id.png
  docs/assets/event-stream-destinations/onesignal-connection-settings.png
  docs/destinations/streaming-destinations/onesignal.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#808 Criteo doc updates
  docs/assets/event-stream-destinations/criteo-connection-settings-1.png
  docs/assets/event-stream-destinations/criteo-connection-settings-2.png
  docs/assets/event-stream-destinations/criteo-connection-settings-3.png
  docs/destinations/streaming-destinations/criteo.mdx
Labels: Good to go!

#809 Removed Page Reference Formatting
  docs/destinations/streaming-destinations/adobe-analytics/index.mdx
  docs/destinations/streaming-destinations/dcm-floodlight/index.mdx
  docs/destinations/streaming-destinations/drip/index.mdx
  docs/destinations/streaming-destinations/google-analytics-4/index.mdx
  docs/destinations/streaming-destinations/profitwell/index.mdx
  docs/destinations/streaming-destinations/singular/index.mdx
  docs/destinations/streaming-destinations/vero/index.mdx
  docs/sources/sdks/rudderstack-javascript-sdk/consent-managers/index.mdx
Labels: Good to go!

#797 Canny source doc
  docs/assets/event-stream-sources/canny-1.png
  docs/assets/event-stream-sources/canny-2.png
  docs/assets/event-stream-sources/webhook-url-canny.png
  docs/sources/cloud-apps/canny.mdx
  docs/sources/cloud-apps/index.mdx
  docs/sources/cloud-apps/iterable.mdx
  src/data/sources.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#807 Canny destination doc
  docs/assets/event-stream-destinations/canny-api-key.png
  docs/assets/event-stream-destinations/canny-connection-settings.png
  docs/assets/event-stream-destinations/canny-new-field.png
  docs/destinations/streaming-destinations/canny.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#811 Data sync to custom Salesforce objects
  docs/assets/warehouse-actions-sources/salesforce-custom-object-1.png
  docs/assets/warehouse-actions-sources/salesforce-custom-object-2.png
  docs/assets/warehouse-actions-sources/salesforce-custom-object.png
  docs/sources/reverse-etl/features/visual-data-mapper.mdx
Labels: Good to go!

#814 Automatically capture IP address
  docs/destinations/streaming-destinations/singular/singular-cloud-mode.mdx
  docs/event-spec/standard-events/application-lifecycle-events-spec.mdx
  docs/event-spec/standard-events/common-fields.mdx
  docs/event-spec/standard-events/video-events-spec.mdx
  docs/sources/sdks/rudderstack-unity-sdk.mdx
  netlify.toml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#818 Webhook intro update
  docs/destinations/webhooks.mdx
Labels: Internal review

#810 Update links to remove old docs subdomain reference
  CONTRIBUTING.mdx
  docs/sources/sdks/rudderstack-javascript-sdk/detecting-adblocked-pages.mdx
  docs/sources/sdks/rudderstack-javascript-sdk/faq.mdx
  docs/sources/sdks/rudderstack-javascript-sdk/index.mdx
  docs/sources/sdks/rudderstack-javascript-sdk/javascript-sdk-enhancements.mdx
  docs/sources/sdks/rudderstack-javascript-sdk/quick-start-guide.mdx
Labels: Ready for review

#803 Replicate eslint & prettier configs from main site repo.
  .eslintrc
  .prettierignore
  .prettierrc
  package.json
  yarn.lock
Labels: Ready for review

#819 Transformations images hotfix
  docs/assets/features/adding-a-library-1.png
  docs/assets/features/adding-a-library-2.png
  docs/assets/features/adding-a-transformation-1.png
  docs/assets/features/adding-a-transformation-2.png
  docs/assets/features/adding-a-transformation-3.png
  docs/assets/features/adding-transformation-existing-destination-1.png
  docs/assets/features/adding-transformation-existing-destination-2.png
  docs/assets/features/connecting-a-transformation.png
  docs/assets/features/libraries-in-transformations-test.png
  docs/assets/features/libraries-in-transformations.png
  docs/assets/features/older-transformation.png
  docs/assets/features/transformation-log.png
  docs/assets/features/transformations-workflow.png
  docs/features/transformations.mdx
Labels: Good to go!

#820 Image and URL fixes
  docs/destinations/streaming-destinations/gainsight.mdx
  docs/destinations/warehouse-destinations/delta-lake.mdx
  docs/event-spec/ecommerce-events-spec/index.mdx
  docs/sources/extract/salesforce/index.mdx
Labels: Good to go!

#821 Minor style updates
  src/@rocketseat/gatsby-theme-docs/components/Layout/styles.js
  src/css/docs.css
Labels: Good to go!

#825 Open Source multiple nodes warning
  docs/get-started/rudderstack-open-source/data-plane-setup/index.mdx
Labels: Good to go!

#822 GA4 identify call
  docs/assets/event-stream-destinations/google-analytics-4-connection-settings-1.png
  docs/destinations/streaming-destinations/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
Labels: Good to go!

#816 Incorporated RS Open Source vs Cloud feedback
  docs/get-started/cloud-vs-open-source.mdx
Labels: Ready for review

#805 update os vs cloud doc
  docs/get-started/cloud-vs-open-source.mdx
Labels: Review in progress

#830 Added ID resolution note
  docs/features/identity-resolution.mdx
Labels: Good to go!

#827 Marketo documentation revamp
  docs/assets/event-stream-destinations/marketo-connection-settings-1.png
  docs/assets/event-stream-destinations/marketo-connection-settings-2.png
  docs/assets/event-stream-destinations/marketo-connection-settings-3.png
  docs/assets/event-stream-destinations/marketo-connection-settings-4.png
  docs/assets/event-stream-destinations/marketo-launchpoint.png
  docs/assets/event-stream-destinations/marketo-newservice-settings.png
  docs/assets/event-stream-destinations/marketo-service-details.png
  docs/assets/event-stream-destinations/marketo-services.png
  docs/destinations/streaming-destinations/marketo.mdx
Labels: Good to go!

#836 PostHog documentation updates
  docs/destinations/streaming-destinations/posthog.mdx
Labels: Good to go!

#837 HubSpot doc update for RETL sources
  docs/destinations/streaming-destinations/hubspot-v2.mdx
  docs/destinations/streaming-destinations/hubspot.mdx
  docs/sources/reverse-etl/faq.mdx
Labels: Good to go!

#838 Alias call updates
  docs/event-spec/standard-events/alias.mdx
Labels: Good to go!

#832 Google Cloud Functions documentation
  docs/assets/event-stream-destinations/gcf-connection-settings.png
  docs/assets/event-stream-destinations/gcf-setup-1.png
  docs/assets/event-stream-destinations/gcf-setup.png
  docs/assets/event-stream-destinations/gcf-url.png
  docs/destinations/streaming-destinations/google-cloud-functions.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#839 Self-hosted to RS Cloud moved to Migration guides
  docs/user-guides/how-to-guides/switch-to-rudderstack-hosted-data-plane.mdx
  docs/user-guides/migration-guides/index.mdx
  docs/user-guides/migration-guides/switch-to-rudderstack-hosted-data-plane.mdx
  netlify.toml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#791 Transformations doc revamp
  docs/assets/features/deleting-a-library.png
  docs/assets/features/deleting-a-transformation.png
  docs/assets/features/libraries-in-transformations.png
  docs/features/transformations - old.mdx
  docs/features/transformations/faq.mdx
  docs/features/transformations/index.mdx
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#834 SnapEngage documentation
  docs/assets/event-stream-destinations/snapengage-connection-settings-1.png
  docs/assets/event-stream-destinations/snapengage-connection-settings-2.png
  docs/assets/event-stream-destinations/snapengage-event-mapping.png
  docs/assets/event-stream-destinations/snapengage-widget-id.png
  docs/destinations/streaming-destinations/snapengage.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#835 ConvertFlow documentation
  docs/assets/event-stream-destinations/convertflow-connection-settings-1.png
  docs/assets/event-stream-destinations/convertflow-connection-settings-2.png
  docs/assets/event-stream-destinations/convertflow-connection-settings-3.png
  docs/assets/event-stream-destinations/convertflow-event-mapping.png
  docs/assets/event-stream-destinations/convertflow-website-id.png
  docs/assets/event-stream-destinations/convertflow-websites.png
  docs/destinations/streaming-destinations/convertflow.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#806 AWS Lambda documentation
  docs/assets/event-stream-destinations/aws-lambda-connection-settings-1.png
  docs/assets/event-stream-destinations/aws-lambda-connection-settings-2.png
  docs/destinations/streaming-destinations/aws-lambda.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#848 Added Mixpanel extract note
  docs/sources/extract/mixpanel-v2.mdx
Labels: Good to go!

#845 JS SDK revamp latest
  docs/assets/event-stream-sources/javascript-setup.png
  docs/assets/rs-cloud/data-plane-url.png
  docs/dashboard-guides/overview.mdx
  docs/destinations/streaming-destinations/amplitude.mdx
  docs/destinations/streaming-destinations/criteo.mdx
  docs/destinations/streaming-destinations/customer.io.mdx
  docs/destinations/streaming-destinations/google-analytics-ga.mdx
  docs/destinations/streaming-destinations/intercom.mdx
  docs/destinations/streaming-destinations/mouseflow.mdx
  docs/destinations/streaming-destinations/vero/setting-up-vero.mdx
  docs/destinations/warehouse-destinations/json-column-support.mdx
  docs/sources/event-streams/sdks/faq.mdx
  docs/sources/event-streams/sdks/rudderstack-amp-analytics.mdx
  docs/sources/event-streams/sdks/rudderstack-flutter-sdk/flutter-v2.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/consent-managers/index.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/consent-managers/onetrust.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/data-storage-cookies.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/detecting-adblocked-pages.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/faq.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/filtering.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/index.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/javascript-sdk-enhancements.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/onetrust-consent-manager.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/querystring-api.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/quick-start-guide.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/supported-api.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/version-migration-guide.mdx
  docs/user-guides/how-to-guides/custom-domains.mdx
  docs/user-guides/how-to-guides/filter-events.mdx
  docs/user-guides/migration-guides/rudderstack-migration-guide.mdx
  netlify.toml
  src/postNavList.js
  src/sidebar.js
Labels: Ready for review

#826 Wootric destination
  docs/assets/event-stream-destinations/inmoment-account-token.png
  docs/assets/event-stream-destinations/inmoment-connection-settings.png
  docs/destinations/streaming-destinations/inmoment.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Ready for review

#843 GA4 updates
  docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-cloud-mode.mdx
Labels: Good to go!

#847 Hubspot version details update
  docs/destinations/streaming-destinations/hubspot-v2.mdx
  docs/destinations/streaming-destinations/hubspot.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Ready for review

#855 Add <Iplist/> component
  docs/destinations/warehouse-destinations/azure-datalake.mdx
  docs/destinations/warehouse-destinations/azure-synapse.mdx
  docs/destinations/warehouse-destinations/bigquery.mdx
  docs/destinations/warehouse-destinations/clickhouse.mdx
  docs/destinations/warehouse-destinations/delta-lake.mdx
  docs/destinations/warehouse-destinations/gcs-datalake.mdx
  docs/destinations/warehouse-destinations/postgresql.mdx
  docs/destinations/warehouse-destinations/redshift.mdx
  docs/destinations/warehouse-destinations/s3-datalake.mdx
  docs/destinations/warehouse-destinations/snowflake.mdx
  docs/destinations/warehouse-destinations/sql-server.mdx
  src/components/iplist.js
Labels: Ready for review

#852 Branch.io updates
  docs/assets/event-stream-destinations/branchio-connection-settings.png
  docs/assets/event-stream-destinations/branchio-key.png
  docs/destinations/streaming-destinations/branchio.mdx
Labels: Ready for review

#796 Merge API documentation
  docs/api/http-api.mdx
  docs/event-spec/standard-events/index.mdx
  docs/event-spec/standard-events/merge.mdx
Labels: Good to go!

#858 IP list component (Take II)
  docs/destinations/warehouse-destinations/azure-datalake.mdx
  docs/destinations/warehouse-destinations/azure-synapse.mdx
  docs/destinations/warehouse-destinations/bigquery.mdx
  docs/destinations/warehouse-destinations/clickhouse.mdx
  docs/destinations/warehouse-destinations/delta-lake.mdx
  docs/destinations/warehouse-destinations/gcs-datalake.mdx
  docs/destinations/warehouse-destinations/postgresql.mdx
  docs/destinations/warehouse-destinations/redshift.mdx
  docs/destinations/warehouse-destinations/s3-datalake.mdx
  docs/destinations/warehouse-destinations/snowflake.mdx
  docs/destinations/warehouse-destinations/sql-server.mdx
  src/@rocketseat/gatsby-theme-docs/components/Docs/index.js
  src/components/iplist.js
Labels: Good to go!

#823 Widen main content column
  src/@rocketseat/gatsby-theme-docs/components/Layout/styles.js
Labels: Good to go!

#833 Mautic documentation
  docs/assets/event-stream-destinations/mautic-connection-settings.png
  docs/destinations/streaming-destinations/mautic.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!
