Repository rudderlabs/rudderstack-docs, pull requests merged in 2022-12, with the labels that each got.

#1018 Iterable extract source
  docs/assets/cloud-extract-sources/iterable-connection-settings.png
  docs/assets/cloud-extract-sources/iterable-resources.png
  docs/sources/event-streams/cloud-apps/iterable.mdx
  docs/sources/extract/iterable.mdx
  src/data/sources.yaml
  src/sidebar.js
Labels: Good to go!

#1021 Data management and event replay updates
  docs/assets/dashboard-guides/connect-cloud-storage.png
  docs/dashboard-guides/data-retention.mdx
  docs/user-guides/administrators-guide/event-replay.mdx
Labels: Good to go!

#1030 Destination Live Events how to guide update
  docs/assets/user-guides/destination-live-events-details.png
  docs/assets/user-guides/destination-live-events-error-new.png
  docs/assets/user-guides/destination-live-events-error.png
  docs/assets/user-guides/destination-live-events.png
  docs/user-guides/how-to-guides/debugging-destination-live-events.mdx
  docs/user-guides/how-to-guides/live-destination-event-debugger.mdx
  src/sidebar.js
  vercel.json
Labels: Good to go!

#1031 Bing Ads doc update
  docs/destinations/streaming-destinations/bingads.mdx
Labels: Good to go!

#1032 Braze doc update
  docs/destinations/streaming-destinations/braze.mdx
Labels: Good to go!

#1039 Notification guide updates
  docs/dashboard-guides/notifications.mdx
  docs/destinations/warehouse-destinations/faq.mdx
  docs/destinations/warehouse-destinations/json-column-support.mdx
Labels: Good to go!

#1007 Marketo Static Lists documentation
  docs/assets/event-stream-destinations/marketo-munchkin-id.png
  docs/assets/event-stream-destinations/marketo-static-list-id.png
  docs/destinations/streaming-destinations/marketo-static-lists.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#1044 PostHog device mode doc update
  docs/destinations/streaming-destinations/posthog/posthog-device-mode.mdx
Labels: Good to go!

#1028 Update for Oauth destinations
  docs/assets/event-stream-destinations/account-connect-normal.png
  docs/destinations/streaming-destinations/campaign-manager-360.mdx
  docs/destinations/streaming-destinations/google-adwords-enhanced-conversions.mdx
  docs/destinations/streaming-destinations/google-adwords-offline-conversions.mdx
  docs/destinations/streaming-destinations/google-adwords-remarketing-list.mdx
  docs/destinations/streaming-destinations/pardot.mdx
  docs/destinations/streaming-destinations/snapchat-custom-audience.mdx
Labels: Good to go!

#1029 Satismeter destination documentation
  docs/assets/event-stream-destinations/record-satismeter-events.png
  docs/assets/event-stream-destinations/satismeter-update-track-event-name.png
  docs/assets/event-stream-destinations/satismeter-write-key.png
  docs/destinations/streaming-destinations/satismeter.mdx
  src/data/destinations.yaml
  src/sidebar.js
Labels: Good to go!

#1024 Microsoft Clarity destination docs
  docs/assets/event-stream-destinations/clarity-cookie-consent.png
  docs/assets/event-stream-destinations/clarity-project-id.png
  docs/destinations/streaming-destinations/microsoft-clarity.mdx
  src/data/destinations.yaml
  src/sidebar.js
Labels: Good to go!

#1033 Axeptio documentation
  docs/assets/event-stream-destinations/axeptio-client-id-2.png
  docs/assets/event-stream-destinations/axeptio-client-id.png
  docs/destinations/streaming-destinations/axeptio.mdx
  src/data/destinations.yaml
  src/sidebar.js
Labels: Good to go!

#1027 Delete user support for GA
  docs/api/data-regulation-api.mdx
  docs/assets/event-stream-destinations/account-connect.png
  docs/assets/event-stream-destinations/edit-account-creds.png
  docs/assets/event-stream-destinations/user-deletion.png
  docs/destinations/streaming-destinations/google-analytics-ga.mdx
Labels: Good to go!

#1043 Olark src doc
  docs/assets/event-stream-sources/olark-webhook-src.png
  docs/sources/event-streams/cloud-apps/olark.mdx
  src/data/sources.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#1045 PersistIQ documentation
  docs/assets/event-stream-destinations/persistiq-api-key.png
  docs/assets/event-stream-destinations/persistiq-campaign-id.png
  docs/assets/event-stream-destinations/persistiq-lead-id.png
  docs/destinations/streaming-destinations/persistiq.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#1051 S3 RETL source IAM role authentication
  docs/assets/warehouse-actions-sources/aws-security-credentials.png
  docs/sources/reverse-etl/amazon-s3.mdx
Labels: Good to go!

#1042 VWO doc standardization
  docs/destinations/streaming-destinations/vwo.mdx
Labels: Good to go!

#1047 Amplitude config update
  docs/destinations/streaming-destinations/amplitude.mdx
Labels: Good to go!

#1055 Zendesk documentation updates
  docs/assets/event-stream-destinations/zendesk-connection-settings.png
  docs/destinations/streaming-destinations/zendesk.mdx
Labels: Internal review

#1059 Reverted destinations
  docs/destinations/streaming-destinations/axeptio.mdx
  docs/destinations/streaming-destinations/microsoft-clarity.mdx
  docs/destinations/streaming-destinations/satismeter.mdx
  src/data/destinations.yaml
  src/sidebar.js
Labels: Good to go!, To be reverted

#1034 RETL - Features overview and Models guide
  docs/assets/warehouse-actions-sources/edit-model-configuration.png
  docs/assets/warehouse-actions-sources/model-settings.png
  docs/assets/warehouse-actions-sources/models-dashboard.png
  docs/assets/warehouse-actions-sources/sample-sql-query.png
  docs/assets/warehouse-actions-sources/select-source-model.png
  docs/sources/reverse-etl/common-settings/models.mdx
  docs/sources/reverse-etl/common-settings/visual-data-mapper.mdx
  docs/sources/reverse-etl/features/overview.mdx
  docs/sources/reverse-etl/features/syncing-events.mdx
  src/postNavList.js
  src/sidebar.js
  vercel.json
Labels: Ready for review

#1058 FTR update for warehouse destinations
  docs/assets/dw-integrations/delta-lake-connection-settings-3.png
  docs/destinations/aws-iam-role-for-rudderstack.mdx
  docs/destinations/streaming-destinations/amazon-s3.mdx
  docs/destinations/warehouse-destinations/azure-datalake.mdx
  docs/destinations/warehouse-destinations/azure-synapse.mdx
  docs/destinations/warehouse-destinations/bigquery.mdx
  docs/destinations/warehouse-destinations/clickhouse.mdx
  docs/destinations/warehouse-destinations/delta-lake.mdx
  docs/destinations/warehouse-destinations/gcs-datalake.mdx
  docs/destinations/warehouse-destinations/json-column-support.mdx
  docs/destinations/warehouse-destinations/postgresql.mdx
  docs/destinations/warehouse-destinations/redshift.mdx
  docs/destinations/warehouse-destinations/s3-datalake.mdx
  docs/destinations/warehouse-destinations/snowflake.mdx
  docs/destinations/warehouse-destinations/sql-server.mdx
  src/@rocketseat/gatsby-theme-docs/components/Docs/index.js
  src/components/ftrdestinations.js
  src/data/destinations.yaml
Labels: Good to go!

#1060 Extract sources cleanup
  docs/sources/extract/activecampaign.mdx
  docs/sources/extract/amplitude.mdx
  docs/sources/extract/bing-ads.mdx
  docs/sources/extract/chargebee.mdx
  docs/sources/extract/customerio.mdx
  docs/sources/extract/facebook-ads.mdx
  docs/sources/extract/freshdesk-v2.mdx
  docs/sources/extract/freshdesk.mdx
  docs/sources/extract/google-adwords.mdx
  docs/sources/extract/google-analytics.mdx
  docs/sources/extract/google-search-console-v2.mdx
  docs/sources/extract/google-search-console.mdx
  docs/sources/extract/google-sheets.mdx
  docs/sources/extract/hubspot.mdx
  docs/sources/extract/intercom.mdx
  docs/sources/extract/iterable.mdx
  docs/sources/extract/klaviyo.mdx
  docs/sources/extract/mailchimp.mdx
  docs/sources/extract/marketo.mdx
  docs/sources/extract/mixpanel.mdx
  docs/sources/extract/netsuite.mdx
  docs/sources/extract/pipedrive.mdx
  docs/sources/extract/quickbooks.mdx
  docs/sources/extract/recurly.mdx
  docs/sources/extract/salesforce-pardot.mdx
  docs/sources/extract/salesforce.mdx
  docs/sources/extract/sendgrid.mdx
  docs/sources/extract/stripe.mdx
  docs/sources/extract/zendesk-chat.mdx
  docs/sources/extract/zendesk-support.mdx
  src/data/sources.yaml
  src/sidebar.js
  vercel.json
Labels: Good to go!

#1048 Google Analytics 4 source documentation
  docs/assets/cloud-extract-sources/google-analytics-4-connection-settings-1.png
  docs/assets/cloud-extract-sources/google-analytics-4-connection-settings-2.png
  docs/assets/cloud-extract-sources/google-analytics-4-custom-report.png
  docs/assets/cloud-extract-sources/google-analytics-4-data-import-settings.png
  docs/sources/extract/google-analytics-4.mdx
  src/data/sources.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#1064 PHP SDK initialization snippet update
  docs/sources/event-streams/sdks/rudderstack-php-sdk.mdx
Labels: Good to go!

#1066 Access key based auth deprecation note
  docs/destinations/aws-iam-role-for-rudderstack.mdx
  docs/destinations/streaming-destinations/amazon-eventbridge.mdx
  docs/destinations/streaming-destinations/amazon-kinesis-firehose.mdx
  docs/destinations/streaming-destinations/amazon-kinesis.mdx
  docs/destinations/streaming-destinations/amazon-s3.mdx
  docs/destinations/streaming-destinations/aws-lambda.mdx
  docs/destinations/streaming-destinations/aws-personalize.mdx
  docs/destinations/warehouse-destinations/delta-lake.mdx
  docs/destinations/warehouse-destinations/s3-datalake.mdx
  docs/destinations/warehouse-destinations/snowflake.mdx
Labels: Good to go!

#1038 Google Sheets V2 documentation
  docs/assets/cloud-extract-sources/googlesheets-beta-connection-settings.png
  docs/assets/cloud-extract-sources/googlesheets-beta-service-account-email.png
  docs/assets/cloud-extract-sources/googlesheets-beta-service-account-permissions.png
  docs/assets/cloud-extract-sources/googlesheets-beta-sheet.png
  docs/sources/extract/customerio.mdx
  docs/sources/extract/google-sheets-v2.mdx
  docs/sources/extract/google-sheets.mdx
  src/data/sources.yaml
  src/sidebar.js
Labels: Good to go!

#1067 Pipedream source documentation
  docs/assets/event-stream-sources/pipedream-custom-http-request.png
  docs/assets/event-stream-sources/pipedream-http-webhook.png
  docs/assets/event-stream-sources/pipedream-webhook.png
  docs/sources/event-streams/cloud-apps/pipedream.mdx
  src/data/sources.yaml
  src/sidebar.js
Labels: Good to go!

#1073 Appsflyer doc hotfix
  docs/destinations/streaming-destinations/appsflyer.mdx
Labels: Good to go!

#1070 TikTok track call payload update
  docs/destinations/streaming-destinations/tiktok-ads.mdx
Labels: Good to go!

#1062 Session tracking docs optimization
  docs/sources/event-streams/sdks/session-tracking/faq.mdx
  docs/sources/event-streams/sdks/session-tracking/index.mdx
  docs/sources/event-streams/sdks/session-tracking/manual-session-tracking.mdx
  src/sidebar.js
Labels: Good to go!

#1076 AppsFlyer doc updates
  docs/destinations/streaming-destinations/appsflyer.mdx
Labels: Good to go!

#977 FactorsAI doc
  docs/assets/event-stream-destinations/factorsai-api-key.png
  docs/destinations/streaming-destinations/factors.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
  vercel.json
Labels: Good to go!
