Repository rudderlabs/rudderstack-docs, pull requests merged in 2022-02, with the labels that each got.

#367 Data Governance Updates
  data-governance/index.mdx
Labels: Ready for review, Low Priority

#364 TikTok Ads integration doc
  assets/event-stream-destinations/tiktokads-connection-settings.png
  destinations/advertising/tiktok-ads.mdx
Labels: Good to go!

#375 Salesforce Identify Call Correction
  destinations/crm/salesforce.mdx
Labels: Good to go!

#368 Updated Whitelisted IPs
  data-warehouse-integrations/amazon-redshift.mdx
  data-warehouse-integrations/azure-datalake.mdx
  data-warehouse-integrations/azure-synapse.mdx
  data-warehouse-integrations/clickhouse.mdx
  data-warehouse-integrations/delta-lake.mdx
  data-warehouse-integrations/gcs-datalake.mdx
  data-warehouse-integrations/google-bigquery.mdx
  data-warehouse-integrations/microsoft-sql-server.mdx
  data-warehouse-integrations/postgresql.mdx
  data-warehouse-integrations/s3-datalake.mdx
  data-warehouse-integrations/warehouse-faqs.mdx
Labels: Ready for review

#350 Integration PR Guide Updates
  user-guides/how-to-guides/how-to-submit-an-integration-pull-request.mdx
Labels: Review in progress

#374 Updated event mapping
  destinations/advertising/pinterest-ads.mdx
Labels: Ready for review

#373 Iterable Documentation Updates
  assets/event-stream-destinations/iterable-connection-settings.png
  destinations/marketing/iterable.mdx
Labels: Ready for review

#360 AppsFlyer Documentation Update
  destinations/attribution/appsflyer.mdx
Labels: Good to go!

#380 maxRetryDelay Default Value Correction
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
Labels: Good to go!

#382 Candu and TikTok ads
  postNavList.js
  sidebar.js
Labels: Good to go!

#381 Mixpanel Mapping Updates
  assets/event-map-setting.png
  assets/event-stream-destinations/mixpanel-connection-settings-1.png
  assets/event-stream-destinations/mixpanel-connection-settings-2.png
  assets/event-stream-destinations/mixpanel-connection-settings-3.png
  assets/event-stream-destinations/mixpanel-connection-settings-4.png
  assets/event-stream-destinations/mixpanel-group-key-settings.png
  assets/event-stream-destinations/mixpanel-super-people.png
  destinations/analytics/mixpanel.mdx
Labels: Internal review

#383 PostgreSQL Documentation Update
  assets/dw-integrations/postgresql-connection-settings-1.png
  assets/dw-integrations/postgresql-connection-settings-2.png
  assets/dw-integrations/postgresql-ssl-pem-contents.png
  assets/dw-integrations/postgresql-verify-ca-dashboard.png
  data-warehouse-integrations/postgresql.mdx
Labels: Ready for review

#385 CleverTap doc updates
  destinations/marketing/clevertap.mdx
Labels: Good to go!

#387 Mixpanel Documentation Updates
  assets/event-stream-destinations/mixpanel-connection-settings-3.png
  destinations/analytics/mixpanel.mdx
Labels: Good to go!

#386 Amplitude Documentation Updates
  assets/event-stream-destinations/amplitude-connection-settings-1.png
  assets/event-stream-destinations/amplitude-connection-settings-2.png
  assets/event-stream-destinations/amplitude-connection-settings-3.png
  assets/event-stream-destinations/amplitude-connection-settings-4.png
  destinations/analytics/amplitude.mdx
Labels: Ready for review

#379 minSdk for device mode integrations
  destinations/attribution/branchio.mdx
  destinations/business-messaging/intercom.mdx
  destinations/continuous-integration/appcenter.mdx
  destinations/marketing/qualtrics.mdx
Labels: Good to go!

#388 Timestamp format info update
  rudderstack-api/http-api.mdx
Labels: Ready for review

#345 Guides to Docs conversion
  assets/user-guides/browser-network-tab-1.png
  assets/user-guides/browser-network-tab.png
  assets/user-guides/document-next-app.png
  assets/user-guides/ga-live-events-angular.png
  assets/user-guides/ga-live-events-astro.png
  assets/user-guides/ga-live-events-ember.png
  assets/user-guides/ga-live-events-svelte.png
  assets/user-guides/ga-live-events-vue.png
  assets/user-guides/ga-live-events.png
  assets/user-guides/ga-settings.png
  assets/user-guides/index-next-app.png
  assets/user-guides/javascript-writekey.png
  assets/user-guides/live-events.png
  assets/user-guides/nuxtjs-config.png
  assets/user-guides/rudderstack-dashboard.png
  assets/user-guides/rudderstack-directory.png
  assets/user-guides/rudderstack-ga-connection.png
  assets/user-guides/run-next-app.png
  assets/user-guides/successful-live-events-angular.png
  assets/user-guides/successful-live-events-astro.png
  assets/user-guides/successful-live-events-ember.png
  assets/user-guides/successful-live-events-svelte.png
  assets/user-guides/successful-live-events-vue.png
  assets/user-guides/successful-live-events.png
  user-guides/how-to-guides/rudderstack-jamstack-integration/index.mdx
  user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-angular-integration.mdx
  user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-astro-integration.mdx
  user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-eleventy-integration.mdx
  user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-ember-integration.mdx
  user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-gatsby-integration.mdx
  user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-hugo-integration.mdx
  user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-jekyll-integration.mdx
  user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-nextjs-integration.mdx
  user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-nuxtjs-integration.mdx
  user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-svelte-integration.mdx
  user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-vue-integration.mdx
Labels: Good to go!

#298 Tracking Plan documentation
  assets/data-governance/download-tracking-plan.png
  assets/data-governance/personal-access-token.png
  assets/data-governance/tracking-plan-menu.png
  assets/data-governance/tracking-plan-source-id.png
  assets/data-governance/tracking-plans-permissions.png
  assets/data-governance/upload-tracking-plan.png
  data-governance/ruddertyper.mdx
  data-governance/tracking-plans/index.mdx
  data-governance/tracking-plans/tracking-plan-spreadsheet.mdx
Labels: Ready for review

#389 Update: webhooks
  destinations/webhooks.mdx
Labels: Good to go!

#391 React Native SDK documentation update
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.mdx
Labels: Good to go!

#393 update the licensing for MinIO
  destinations/storage-platforms/minio.mdx
Labels: Good to go!

#390 Google AdWords documentation update
  assets/cloud-extract-sources/google-adwords-add-resource-1.png
  assets/cloud-extract-sources/google-adwords-add-resource-2.png
  assets/cloud-extract-sources/google-adwords-connect-destinations.png
  assets/cloud-extract-sources/google-adwords-dashboard.png
  assets/cloud-extract-sources/google-adwords-destination-settings.png
  assets/cloud-extract-sources/google-adwords-resources.png
  assets/cloud-extract-sources/google-adwords-source-settings.png
  cloud-extract-sources/google-adwords.mdx
Labels: Good to go!

#394 Create test-image.mdx
  assets/cloud-extract-sources/BigScreen.png
  assets/cloud-extract-sources/laptop_fullscreen.png
  assets/cloud-extract-sources/laptop_optimalscreen.png
  assets/cloud-extract-sources/size1115.png
  assets/cloud-extract-sources/size930.png
  user-guides/migration-guides/test-image.mdx
Labels: Good to go!

#396 Okta SSO Documentation Updates
  assets/user-guides/okta-sso-1.png
  assets/user-guides/okta-sso-2.png
  assets/user-guides/okta-sso-3.png
  assets/user-guides/okta-sso-4.png
  assets/user-guides/okta-sso-5.png
  assets/user-guides/okta-sso-6.png
  assets/user-guides/okta-sso-7.png
  user-guides/administrators-guide/okta-sso.mdx
Labels: Good to go!

#378 Customer.io Source Updates
  assets/event-stream-sources/customerio-5.png
  stream-sources/customerio.mdx
Labels: Good to go!

#398 Marketo Lead Import documentation update
  assets/event-stream-destinations/marketo-lead-import-connection-settings.png
  destinations/marketing/marketo-lead-import.mdx
Labels: Internal review

#392 Segment anonymousId backfilling section updates
  assets/user-guides/rudderstack-dashboard.png
  user-guides/migration-guides/rudderstack-migration-guide.mdx
Labels: Good to go!

#397 Gender-neutral pronoun usage
  cloud-extract-sources/google-search-console.mdx
  cloud-extract-sources/intercom-v2.mdx
  cloud-extract-sources/pipedrive.mdx
  connections/adding-source-and-destination-rudderstack.mdx
  data-governance/index.mdx
  data-warehouse-integrations/index.mdx
  destinations/advertising/facebook-app-events.mdx
  destinations/advertising/tiktok-ads.mdx
  destinations/analytics/aws-personalize.mdx
  destinations/analytics/kubit.mdx
  destinations/continuous-integration/appcenter.mdx
  faqs.mdx
  get-started/dashboard-overview/audit-logs.mdx
  glossary.mdx
  transformations/rudderstack-transformation-api.mdx
  user-guides/administrators-guide/rudderstack-grafana-dashboard.mdx
Labels: Good to go!

#399 Delta Lake documentation updates
  data-warehouse-integrations/delta-lake.mdx
Labels: Ready for review

#371 Snowflake Documentation Update
  assets/dw-integrations/snowflake-connection-settings-1.png
  assets/dw-integrations/snowflake-connection-settings.png
  assets/dw-integrations/snowflake-create-database.png
  assets/dw-integrations/snowflake-create-user.png
  assets/dw-integrations/snowflake-create-warehouse.png
  data-warehouse-integrations/snowflake.mdx
Labels: Ready for review

#407 Logging support for .NET SDK
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-dotnet-sdk.mdx
Labels: Good to go!

#402 Flush support for Python and .NET SDK
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-dotnet-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-python-sdk.mdx
Labels: Good to go!

#408 Mixpanel bug fix
  destinations/analytics/mixpanel.mdx
Labels: Good to go!

#410 Firebase Hotfix
  destinations/analytics/firebase.mdx
Labels: Ready for review

#412 Setting anonymous ID in Unity SDK
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-unity-sdk.mdx
Labels: Good to go!

#413 Minor doc fixes
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-dotnet-sdk.mdx
  stream-sources/rudderstack-sdk-integration-guides/rudderstack-unity-sdk.mdx
Labels: Good to go!

#411 Supported cloud mode and device mode events for Shopify source
  assets/event-stream-sources/RS-Shopify-app.png
  stream-sources/shopify.mdx
Labels: Ready for review

#417 Active Campaign image update
  assets/Active_Campaign.png
Labels: Ready for review

#418 Shopify new updates
  assets/event-stream-sources/RS-Shopify-app.png
  assets/event-stream-sources/shopify-1.png
  assets/event-stream-sources/shopify-2.png
  assets/event-stream-sources/shopify-3.png
  assets/event-stream-sources/shopify-4.png
  assets/event-stream-sources/shopify-5.png
  assets/event-stream-sources/shopify-6.png
  assets/event-stream-sources/shopify-data-plane-url.png
  faqs.mdx
  stream-sources/shopify.mdx
Labels: Ready for review

#419 Update: alias
  rudderstack-api/api-specification/rudderstack-spec/alias.mdx
Labels: Good to go!

#420 Shopify minor doc fixes
  stream-sources/shopify.mdx
Labels: Good to go!

#421 Mixpanel doc update
  destinations/analytics/mixpanel.mdx
Labels: Good to go!

#409 Google Ads Remarketing List documentation
  assets/event-stream-destinations/google-adwords-remarketing-lists-connection-settings.png
  assets/event-stream-destinations/google-adwords-remarketing-lists-customer-id.png
  assets/event-stream-destinations/google-adwords-remarketing-lists-developer-token.png
  destinations/advertising/google-adwords-remarketing-list.mdx
Labels: Good to go!

#404 Pardot destination
  assets/event-stream-destinations/Pardot-crmfid1.png
  assets/event-stream-destinations/Pardot-crmfid2.png
  assets/event-stream-destinations/pardot-business-unit-id.png
  assets/event-stream-destinations/pardot-connection-settings3.png
  destinations/marketing/pardot.mdx
Labels: Good to go!
