Repository rudderlabs/rudderstack-docs, pull requests merged in 2022-11, with the labels that each got.

#970 Snowplow doc enhancements
  docs/user-guides/migration-guides/index.mdx
  docs/user-guides/migration-guides/snowplow-migration-guide.mdx
Labels: Good to go!

#965 Slash fix
  gatsby-config.js
Labels: Ready for review

#976 HubSpot lookup field update
  docs/assets/event-stream-destinations/hubspotv2-connection-settings-3.png
  docs/destinations/streaming-destinations/hubspot/hubspot-cloud-mode/hubspot-new-api-cloud.mdx
Labels: Good to go!

#969 Braze iOS v2 device mode updates
  docs/destinations/streaming-destinations/braze.mdx
Labels: Good to go!

#964 Warehouse FAQ update
  docs/destinations/warehouse-destinations/faq.mdx
Labels: Good to go!

#978 PostHog documentation updates
  docs/destinations/streaming-destinations/posthog.mdx
  docs/destinations/streaming-destinations/posthog/index.mdx
  docs/destinations/streaming-destinations/posthog/posthog-cloud-mode.mdx
  docs/destinations/streaming-destinations/posthog/posthog-device-mode.mdx
  docs/destinations/streaming-destinations/posthog/setting-up-posthog.mdx
  src/sidebar.js
Labels: Good to go!

#967 Freshmarketer updates
  docs/destinations/streaming-destinations/freshmarketer.mdx
Labels: Good to go!

#968 Freshsales updates
  docs/destinations/streaming-destinations/freshsales.mdx
Labels: Good to go!

#979 Adds doc covering the new alerts feature
  docs/assets/rs-cloud/enable-notifications.png
  docs/assets/rs-cloud/manage-subscriptions.png
  docs/assets/rs-cloud/notification-settings.png
  docs/dashboard-guides/notifications.mdx
  src/sidebar.js
Labels: Ready for review

#961 Amplitude Extract source documentation
  docs/assets/cloud-extract-sources/amplitude-connection-settings-2.png
  docs/assets/cloud-extract-sources/amplitude-connection-settings.png
  docs/sources/extract/amplitude.mdx
  src/data/sources.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#984 Okta SSO updates
  docs/user-guides/administrators-guide/okta-sso.mdx
Labels: Good to go!

#983 Remove obsolete destination transformation doc
  docs/user-guides/how-to-guides/create-a-new-destination-transformer-for-rudder/best-practices-for-coding-transformation-functions-in-javascript.mdx
  docs/user-guides/how-to-guides/create-a-new-destination-transformer-for-rudder/index.mdx
  src/sidebar.js
Labels: Good to go!

#988 Ecommerce spec code formatting hotfix
  docs/event-spec/ecommerce-events-spec/browsing.mdx
  docs/event-spec/ecommerce-events-spec/coupons.mdx
  docs/event-spec/ecommerce-events-spec/ordering.mdx
  docs/event-spec/ecommerce-events-spec/promotions.mdx
  docs/event-spec/ecommerce-events-spec/reviewing.mdx
  docs/event-spec/ecommerce-events-spec/sharing.mdx
  docs/event-spec/ecommerce-events-spec/wishlisting.mdx
Labels: Good to go!

#920 Snapchat Custom Audience destination documentation
  docs/assets/event-stream-destinations/snapchat-segment-id.png
  docs/destinations/streaming-destinations/snapchat-custom-audience.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#989 Suppress delete api updates
  docs/api/data-regulation-api.mdx
  docs/destinations/streaming-destinations/amplitude.mdx
  docs/destinations/streaming-destinations/appsflyer.mdx
  docs/destinations/streaming-destinations/braze.mdx
  docs/destinations/streaming-destinations/clevertap.mdx
  docs/destinations/streaming-destinations/intercom.mdx
  docs/destinations/streaming-destinations/mixpanel.mdx
Labels: Ready for review

#980 Track call support for RETL
  docs/assets/warehouse-actions-sources/data-import-settings-2.png
  docs/assets/warehouse-actions-sources/data-import-settings-3.png
  docs/assets/warehouse-actions-sources/event-name-table-track.png
  docs/assets/warehouse-actions-sources/event-name-track.png
  docs/assets/warehouse-actions-sources/models-data-snippet.png
  docs/assets/warehouse-actions-sources/models-name-enter.png
  docs/assets/warehouse-actions-sources/update-table-selection-wh.png
  docs/assets/warehouse-actions-sources/update-table-selection.png
  docs/sources/reverse-etl/common-settings/importing-data-using-models.mdx
  docs/sources/reverse-etl/common-settings/importing-data-using-tables.mdx
  docs/sources/reverse-etl/faq.mdx
  docs/sources/reverse-etl/features/syncing-events.mdx
  src/postNavList.js
  src/sidebar.js
Labels: Ready for review

#982 Podsights documentation
  docs/assets/event-stream-destinations/podsights-alias-calls.png
  docs/assets/event-stream-destinations/podsights-alias-event.png
  docs/assets/event-stream-destinations/podsights-alias-id.png
  docs/assets/event-stream-destinations/podsights-pixel-id.png
  docs/assets/event-stream-destinations/rudderstack-podsights-event-mapping.png
  docs/destinations/streaming-destinations/podsights.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#991 Tracking Plan spreadsheet update
  docs/features/data-governance/tracking-plans/tracking-plan-spreadsheet.mdx
Labels: Good to go!

#993 Zendesk identify call update
  docs/destinations/streaming-destinations/zendesk.mdx
Labels: Good to go!

#994 Klaviyo e-commerce event mapping update
  docs/destinations/streaming-destinations/klaviyo.mdx
Labels: Good to go!

#922 Content security policy
  docs/destinations/streaming-destinations/adobe-analytics/setting-up-adobe-analytics-in-rudderstack.mdx
  docs/destinations/streaming-destinations/adroll.mdx
  docs/destinations/streaming-destinations/amplitude.mdx
  docs/destinations/streaming-destinations/appcues.mdx
  docs/destinations/streaming-destinations/bingads.mdx
  docs/destinations/streaming-destinations/braze.mdx
  docs/destinations/streaming-destinations/bugsnag.mdx
  docs/destinations/streaming-destinations/clevertap.mdx
  docs/destinations/streaming-destinations/convertflow.mdx
  docs/destinations/streaming-destinations/criteo.mdx
  docs/destinations/streaming-destinations/customer.io.mdx
  docs/destinations/streaming-destinations/dcm-floodlight/setting-up-dcm-floodlight-in-rudderstack.mdx
  docs/destinations/streaming-destinations/drip/setting-up-drip-in-rudderstack.mdx
  docs/destinations/streaming-destinations/fb-pixel.mdx
  docs/destinations/streaming-destinations/fullstory.mdx
  docs/destinations/streaming-destinations/g-ads-gtag.mdx
  docs/destinations/streaming-destinations/google-analytics-360.mdx
  docs/destinations/streaming-destinations/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
  docs/destinations/streaming-destinations/google-analytics-ga.mdx
  docs/destinations/streaming-destinations/google-optimize.mdx
  docs/destinations/streaming-destinations/google-tag-manager.mdx
  docs/destinations/streaming-destinations/heap.io.mdx
  docs/destinations/streaming-destinations/hotjar.mdx
  docs/destinations/streaming-destinations/hubspot/setting-up-hubspot-in-rudderstack.mdx
  docs/destinations/streaming-destinations/intercom.mdx
  docs/destinations/streaming-destinations/keen.mdx
  docs/destinations/streaming-destinations/kissmetrics.mdx
  docs/destinations/streaming-destinations/klaviyo.mdx
  docs/destinations/streaming-destinations/launchdarkly.mdx
  docs/destinations/streaming-destinations/linkedin-insight-tag.mdx
  docs/destinations/streaming-destinations/livechat.mdx
  docs/destinations/streaming-destinations/lotame.mdx
  docs/destinations/streaming-destinations/lytics.mdx
  docs/destinations/streaming-destinations/matomo.mdx
  docs/destinations/streaming-destinations/mixpanel.mdx
  docs/destinations/streaming-destinations/moengage.mdx
  docs/destinations/streaming-destinations/mouseflow.mdx
  docs/destinations/streaming-destinations/optimizely-web.mdx
  docs/destinations/streaming-destinations/pendo.mdx
  docs/destinations/streaming-destinations/pinterest-ads/setting-up-pinterest-ads.mdx
  docs/destinations/streaming-destinations/post-affiliate-pro.mdx
  docs/destinations/streaming-destinations/posthog/setting-up-posthog.mdx
  docs/destinations/streaming-destinations/profitwell/profitwell-cloud-mode.mdx
  docs/destinations/streaming-destinations/profitwell/profitwell-web-device-mode.mdx
  docs/destinations/streaming-destinations/qualtrics.mdx
  docs/destinations/streaming-destinations/quantummetric.mdx
  docs/destinations/streaming-destinations/quora-pixel.mdx
  docs/destinations/streaming-destinations/reddit-pixel.mdx
  docs/destinations/streaming-destinations/rockerbox/setting-up-rockerbox.mdx
  docs/destinations/streaming-destinations/rollbar.mdx
  docs/destinations/streaming-destinations/sentry.mdx
  docs/destinations/streaming-destinations/snap-pixel.mdx
  docs/destinations/streaming-destinations/snapengage.mdx
  docs/destinations/streaming-destinations/tvsquared.mdx
  docs/destinations/streaming-destinations/vero/setting-up-vero.mdx
  docs/destinations/streaming-destinations/vwo-beta-visual-website-optimizer.mdx
  docs/destinations/streaming-destinations/woopra.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
Labels: Good to go!

#996 GA4 client_id
  docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-cloud-mode.mdx
  docs/destinations/streaming-destinations/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
Labels: Good to go!

#998 Amazon S3 update
  docs/sources/reverse-etl/amazon-s3.mdx
Labels: Good to go!

#1000 Removed obsolete Cloud Extract docs
  docs/sources/extract/google-analytics.mdx
  docs/sources/extract/intercom.mdx
  docs/sources/extract/mixpanel.mdx
  docs/sources/extract/salesforce/index.mdx
  docs/sources/extract/salesforce/schema-comparison-rudderstack-vs-segment.mdx
  docs/sources/extract/sendgrid.mdx
  docs/sources/extract/zendesk-chat.mdx
  docs/sources/extract/zendesk.mdx
  src/data/sources.yaml
  src/sidebar.js
Labels: Good to go!

#990 Google search console v2
  docs/assets/cloud-extract-sources/gcs-custom-report.png
  docs/assets/cloud-extract-sources/gcs-delete-custom-report.png
  docs/assets/cloud-extract-sources/gcs-edit-custom-report.png
  docs/assets/cloud-extract-sources/gcs-resources.png
  docs/assets/cloud-extract-sources/gsc-auth-settings.png
  docs/assets/cloud-extract-sources/gsc-connection-settings.png
  docs/assets/cloud-extract-sources/gsc-oauth-settings.png
  docs/sources/extract/google-search-console-v2.mdx
  docs/sources/extract/google-search-console.mdx
  src/data/sources.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#995 Hubspot updates
  docs/assets/event-stream-destinations/hubspot-connections.png
  docs/destinations/streaming-destinations/hubspot/connect-reverse-etl-source.mdx
Labels: Good to go!

#1001 Personal access token doc update
  docs/dashboard-guides/personal-access-token.mdx
Labels: Good to go!

#1004 Clevertap updates
  docs/destinations/streaming-destinations/clevertap.mdx
Labels: Good to go!

#1002 JS SDK load options
  docs/features/transformations/device-mode-transformations.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/quick-start-guide.mdx
  docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-nextjs-integration.mdx
  docs/user-guides/how-to-guides/self-hosting-js-sdk.mdx
Labels: Good to go!

#986 Pinterest doc update
  docs/destinations/streaming-destinations/pinterest-ads/setting-up-pinterest-ads.mdx
Labels: Good to go!

#985 FB Pixel update
  docs/destinations/streaming-destinations/fb-offline-conversions.mdx
  docs/destinations/streaming-destinations/fb-pixel.mdx
Labels: Good to go!

#1003 Add Warehouse FAQ
  docs/destinations/warehouse-destinations/faq.mdx
Labels: Good to go!

#1005 Marketo updates
  docs/assets/event-stream-destinations/marketo-connection-settings-4.png
  docs/destinations/streaming-destinations/marketo.mdx
Labels: Good to go!

#1008 Session tracking table formatting fix
  docs/sources/event-streams/sdks/session-tracking/index.mdx
Labels: Good to go!

#1006 Apache Kafka multiple topic support
  docs/assets/event-stream-destinations/kafka-event-mapping-settings.png
  docs/destinations/streaming-destinations/kafka.mdx
Labels: Good to go!

#1009 App Center Android device mode version update
  docs/destinations/streaming-destinations/appcenter.mdx
  docs/sources/event-streams/sdks/rudderstack-android-sdk/index.mdx
Labels: Good to go!

#987 Contextual fields section update
  docs/event-spec/standard-events/common-fields.mdx
Labels: Good to go!

#1010 Campaign Manager 360
  docs/destinations/streaming-destinations/campaign-manager-360.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#1011 Sendgrid updates
  docs/destinations/streaming-destinations/sendgrid.mdx
Labels: Good to go!

#1014 Mixpanel group call updates
  docs/destinations/streaming-destinations/mixpanel.mdx
  docs/destinations/streaming-destinations/serenytics.mdx
Labels: Good to go!

#1019 Config options in Gatsby guide
  docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-gatsby-integration.mdx
Labels: Good to go!

#1017 Warehouse Schema FAQ updates
  docs/destinations/warehouse-destinations/faq.mdx
  docs/destinations/warehouse-destinations/warehouse-schema.mdx
Labels: Good to go!

#1015 Freshdesk cloud extract source
  docs/assets/cloud-extract-sources/freshdesk-connection-settings-4.png
  docs/assets/cloud-extract-sources/freshdesk-resources.png
  docs/sources/extract/common-settings.mdx
  docs/sources/extract/freshdesk-v2.mdx
  docs/sources/extract/freshdesk.mdx
  src/data/sources.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Do not merge, Good to go!

#1020 Gatsby config updated
  docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-gatsby-integration.mdx
Labels: Good to go!

#1023 add integration videos
  docs/destinations/streaming-destinations/mixpanel.mdx
  docs/destinations/streaming-destinations/refiner/refiner-cloud-mode.mdx
  docs/sources/event-streams/cloud-apps/refiner.mdx
Labels: Good to go!
