Repository rudderlabs/rudderstack-docs, pull requests merged in 2022-07, with the labels that each got.

#717 S3 documentation revamp
  docs/assets/event-stream-destinations/s3-connection-settings.png
  docs/assets/event-stream-destinations/s3-default-encryption.png
  docs/destinations/storage-platforms/amazon-s3.mdx
Labels: Good to go!

#709 GCS Data Lake documentation update
  docs/assets/dw-integrations/gcs-datalake-connection-settings-1.png
  docs/assets/dw-integrations/gcs-datalake-connection-settings-2.png
  docs/assets/dw-integrations/gcs-datalake-time-window-layout.png
  docs/data-warehouse-integrations/gcs-datalake.mdx
Labels: Good to go!

#604 JSON Column Support documentation
  docs/assets/dw-integrations/bigquery-connection-settings-1.png
  docs/assets/dw-integrations/bigquery-connection-settings-2.png
  docs/assets/dw-integrations/json-column-dashboard-setting.png
  docs/assets/dw-integrations/postgresql-connection-settings-1.png
  docs/assets/dw-integrations/postgresql-connection-settings-2.png
  docs/assets/dw-integrations/redshift-connection-settings.png
  docs/assets/dw-integrations/snowflake-connection-settings-1.png
  docs/assets/dw-integrations/snowflake-connection-settings-2.png
  docs/data-warehouse-integrations/amazon-redshift.mdx
  docs/data-warehouse-integrations/google-bigquery.mdx
  docs/data-warehouse-integrations/json-column-support.mdx
  docs/data-warehouse-integrations/postgresql.mdx
  docs/data-warehouse-integrations/snowflake.mdx
Labels: Good to go!

#720 JSON Column Support minor fixes
  docs/data-warehouse-integrations/json-column-support.mdx
Labels: Good to go!

#723 Connections content
  docs/sources/cloud-apps/braze-currents.mdx
  docs/sources/cloud-apps/index.mdx
  docs/sources/extract/index.mdx
  docs/sources/index.mdx
  docs/sources/reverse-etl/index.mdx
  docs/sources/sdks/index.mdx
  docs/tmp-destinations/overview.mdx
  docs/tmp-destinations/streaming-destinations/index.mdx
  docs/tmp-destinations/warehouse-destinations/index.mdx
  src/data/destinations.yaml
  src/data/sources.yaml
Labels: Ready for review

#726 Changes in the recently merged PRs
  docs/destinations/streaming-destinations/amazon-s3.mdx
  docs/destinations/streaming-destinations/kustomer.mdx
  docs/destinations/streaming-destinations/singular/singular-cloud-mode.mdx
  docs/destinations/streaming-destinations/yahoo-dsp.mdx
  docs/destinations/warehouse-destinations/bigquery.mdx
  docs/destinations/warehouse-destinations/json-column-support.mdx
  docs/destinations/warehouse-destinations/postgresql.mdx
  docs/destinations/warehouse-destinations/redshift.mdx
  docs/destinations/warehouse-destinations/snowflake.mdx
  docs/sources/cloud-apps/auth0.mdx
  docs/sources/reverse-etl/databricks.mdx
  src/sidebar.js
Labels: Good to go!

#729 Zendesk documentation updates
  docs/assets/cloud-extract-sources/zendesk-api-token.png
  docs/assets/cloud-extract-sources/zendesk-connection-settings-1.png
  docs/assets/cloud-extract-sources/zendesk-connection-settings-2.png
  docs/assets/cloud-extract-sources/zendesk-subdomain.png
  docs/sources/extract/zendesk.mdx
Labels: Good to go!

#731 GA4 documentation updates
  docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-cloud-mode.mdx
Labels: Good to go!

#733 Destination connection settings image update
  docs/assets/event-stream-destinations/firebase-connection-settings.png
  docs/assets/event-stream-destinations/ga-connection-settings-1.png
  docs/assets/event-stream-destinations/ga-connection-settings-2.png
  docs/assets/event-stream-destinations/ga-connection-settings-3.png
  docs/assets/event-stream-destinations/ga-connection-settings-4.png
  docs/assets/event-stream-destinations/ga-connection-settings-5.png
  docs/assets/event-stream-destinations/hubspot-connection-settings-1.png
  docs/assets/event-stream-destinations/hubspot-connection-settings-2.png
  docs/assets/event-stream-destinations/lytics-connection-settings-1.png
  docs/assets/event-stream-destinations/lytics-connection-settings-2.png
  docs/assets/event-stream-destinations/mixpanel-connection-settings-1.png
  docs/assets/event-stream-destinations/mixpanel-connection-settings-2.png
  docs/assets/event-stream-destinations/mixpanel-connection-settings-3.png
  docs/assets/event-stream-destinations/mixpanel-connection-settings-4.png
  docs/assets/event-stream-destinations/mixpanel-connection-settings-5.png
  docs/assets/event-stream-destinations/tvsquared-connection-settings.png
  docs/destinations/streaming-destinations/google-analytics-ga.mdx
  docs/destinations/streaming-destinations/hubspot.mdx
  docs/destinations/streaming-destinations/lytics.mdx
  docs/destinations/streaming-destinations/mixpanel.mdx
  docs/destinations/streaming-destinations/tvsquared.mdx
Labels: Ready for review

#734 formatting, adding back missing identify information
  docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-cloud-mode.mdx
  docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-device-mode.mdx
  docs/destinations/streaming-destinations/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
Labels: Good to go!

#741 Minor documentation updates and bug fixes
  docs/dashboard-guides/overview.mdx
  docs/sources/reverse-etl/common-settings/sync-modes.mdx
  docs/user-guides/administrators-guide/rudderstack-grafana-dashboard.mdx
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#727 Vero destination documentation
  docs/assets/event-stream-destinations/vero-authentication-token.png
  docs/assets/event-stream-destinations/vero-connection-settings.png
  docs/assets/event-stream-destinations/vero-tags.png
  docs/destinations/streaming-destinations/vero/cloud-mode.mdx
  docs/destinations/streaming-destinations/vero/device-mode.mdx
  docs/destinations/streaming-destinations/vero/index.mdx
  docs/destinations/streaming-destinations/vero/setting-up-vero.mdx
  src/postNavList.js
  src/sidebar.js
Labels: Do not merge, Good to go!

#744 Consent Manager FAQ
  docs/sources/sdks/rudderstack-javascript-sdk/consent-managers/index.mdx
  docs/sources/sdks/rudderstack-javascript-sdk/faq.mdx
Labels: Good to go!

#735 Matomo documentation
  docs/assets/event-stream-destinations/matomo-connection-settings-1.png
  docs/assets/event-stream-destinations/matomo-connection-settings-2.png
  docs/assets/event-stream-destinations/matomo-connection-settings-3.png
  docs/assets/event-stream-destinations/matomo-connection-settings-4.png
  docs/assets/event-stream-destinations/matomo-connection-settings.png
  docs/assets/event-stream-destinations/matomo-dashboard.png
  docs/destinations/streaming-destinations/matomo.mdx
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#747 Mailchimp Custom merge fields
  docs/assets/event-stream-destinations/mailchimp-connection-settings.png
  docs/destinations/streaming-destinations/mailchimp.mdx
Labels: Good to go!

#740 GA4 page call property mappings
  docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-cloud-mode.mdx
  docs/destinations/streaming-destinations/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
Labels: Good to go!

#749 GA tracking ID clarity
  docs/assets/event-stream-destinations/ga-tracking-id-2.png
  docs/assets/event-stream-destinations/ga-tracking-id.png
  docs/destinations/streaming-destinations/google-analytics-ga.mdx
Labels: Ready for review

#748 Freshdesk: Doc revamp
  docs/assets/cloud-extract-sources/freshdesk-connection-settings-1.png
  docs/assets/cloud-extract-sources/freshdesk-connection-settings-2.png
  docs/assets/cloud-extract-sources/freshdesk-connection-settings.png
  docs/sources/extract/freshdesk.mdx
Labels: Good to go!

#753 Title updates
  docs/destinations/streaming-destinations/adobe-analytics/adobe-analytics-mobile-device-mode.mdx
  docs/destinations/streaming-destinations/adobe-analytics/adobe-analytics-web-device-mode.mdx
  docs/destinations/streaming-destinations/adobe-analytics/e-commerce-events.mdx
  docs/destinations/streaming-destinations/dcm-floodlight/dcm-floodlight-cloud-mode.mdx
  docs/destinations/streaming-destinations/dcm-floodlight/dcm-floodlight-device-mode.mdx
  docs/destinations/streaming-destinations/drip/drip-cloud-mode.mdx
  docs/destinations/streaming-destinations/drip/drip-web-device-mode.mdx
  docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-cloud-mode.mdx
  docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-device-mode.mdx
  docs/destinations/streaming-destinations/profitwell/profitwell-cloud-mode.mdx
  docs/destinations/streaming-destinations/profitwell/profitwell-web-device-mode.mdx
  docs/destinations/streaming-destinations/singular/singular-cloud-mode.mdx
  docs/destinations/streaming-destinations/singular/singular-device-mode.mdx
Labels: Ready for review

#750 Sources landing page updates
  docs/sources/index.mdx
  docs/sources/reverse-etl/index.mdx
  src/data/sources.yaml
Labels: Ready for review

#757 Remove rate limit note for GA destinations
  docs/destinations/streaming-destinations/google-adwords-enhanced-conversions.mdx
  docs/destinations/streaming-destinations/google-adwords-remarketing-list.mdx
Labels: Good to go!

#760 Docker setup doc update
  docs/get-started/rudderstack-open-source/data-plane-setup/docker.mdx
Labels: Ready for review

#738 Permissions Management documentation
  docs/assets/rs-cloud/audit-logs-dashboard.png
  docs/assets/rs-cloud/connections-dashboard.png
  docs/assets/rs-cloud/destinations.png
  docs/assets/rs-cloud/get-started.png
  docs/assets/rs-cloud/permissions-management-1.png
  docs/assets/rs-cloud/permissions-management-2.png
  docs/assets/rs-cloud/permissions-management-3.png
  docs/assets/rs-cloud/permissions-management-4.png
  docs/assets/rs-cloud/permissions-management-5.png
  docs/assets/rs-cloud/permissions-management-6.png
  docs/assets/rs-cloud/settings-dashboard.png
  docs/assets/rs-cloud/sources.png
  docs/assets/rs-cloud/syncs-dashboard.png
  docs/assets/rs-cloud/transformations.png
  docs/assets/rs-cloud/workspace-token.png
  docs/dashboard-guides/destinations.mdx
  docs/dashboard-guides/overview.mdx
  docs/dashboard-guides/permissions-management.mdx
  docs/dashboard-guides/sources.mdx
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#763 Video event spec documentation update
  docs/event-spec/video-events-spec.mdx
Labels: Good to go!

#758 Adjust documentation updates
  docs/assets/event-stream-destinations/adjust-app-token-1.png
  docs/assets/event-stream-destinations/adjust-app-token-2.png
  docs/assets/event-stream-destinations/adjust-connection-settings-2.png
  docs/assets/event-stream-destinations/adjust-connection-settings.png
  docs/assets/event-stream-destinations/adjust-event-token.png
  docs/assets/event-stream-destinations/adjust-partner-setup.png
  docs/destinations/streaming-destinations/adjust.mdx
Labels: Good to go!

#762 Facebook Pixel documentation updates
  docs/destinations/streaming-destinations/fb-pixel.mdx
Labels: Good to go!

#774 Cloud destination updates
  docs/destinations/overview.mdx
  docs/destinations/streaming-destinations/index.mdx
  src/data/destinations.yaml
  src/sidebar.js
Labels: Good to go!

#772 FAQ added in Databricks
  docs/assets/dw-integrations/databricks-autopilot-options.png
  docs/destinations/warehouse-destinations/delta-lake.mdx
  docs/destinations/warehouse-destinations/faq.mdx
Labels: Good to go!

#775 S3 data lake documentation updates
  docs/assets/dw-integrations/s3-datalake-connection-settings.png
  docs/assets/dw-integrations/s3-datalake-crawler-1.png
  docs/assets/dw-integrations/s3-datalake-crawler-2.png
  docs/assets/dw-integrations/s3-datalake-crawler-3.png
  docs/assets/dw-integrations/s3-datalake-crawler-4.png
  docs/assets/dw-integrations/s3-datalake-crawler-5.png
  docs/assets/dw-integrations/s3-datalake-crawler-6.png
  docs/assets/dw-integrations/s3-datalake-crawler-7.png
  docs/assets/dw-integrations/s3-datalake-crawler-8.png
  docs/assets/dw-integrations/s3-datalake-querying-data-1.png
  docs/assets/dw-integrations/s3-datalake-querying-data-2.png
  docs/assets/dw-integrations/s3-datalake-querying-data-3.png
  docs/destinations/warehouse-destinations/s3-datalake.mdx
Labels: Good to go!

#776 Added debug mode setting in GA4 doc
  docs/assets/event-stream-destinations/google-analytics-4-connection-settings.png
  docs/destinations/streaming-destinations/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
Labels: Good to go!

#771 Non standard properties FAQ
  docs/destinations/warehouse-destinations/faq.mdx
  docs/destinations/warehouse-destinations/warehouse-schema.mdx
Labels: Good to go!

#778 E-commerce spec landing page update
  docs/event-spec/ecommerce-events-spec/index.mdx
Labels: Good to go!

#780 Snapchat conversion setting update
  docs/assets/event-stream-destinations/snapchat-conversion-connection-settings-2.png
  docs/destinations/streaming-destinations/snapchat-conversion.mdx
Labels: Good to go!

#779 Event mapping: Tiktok Ads doc
  docs/assets/event-stream-destinations/tiktokads-connection-settings.png
  docs/destinations/streaming-destinations/tiktok-ads.mdx
Labels: Good to go!

#767 Recurly: Cloud extract source doc
  docs/assets/cloud-extract-sources/recurly-connection-settings-1.png
  docs/assets/cloud-extract-sources/recurly-connection-settings-2.png
  docs/assets/cloud-extract-sources/recurly-connection-settings.png
  docs/sources/extract/recurly.mdx
  src/data/sources.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#768 Salesforce source documentation
  docs/assets/cloud-extract-sources/salesforce-connection-settings-1.png
  docs/assets/cloud-extract-sources/salesforce-connection-settings-2.png
  docs/assets/cloud-extract-sources/salesforce-connection-settings-3.png
  docs/sources/extract/salesforce-v2.mdx
  docs/sources/extract/salesforce/index.mdx
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#743 Contextual fields combine for SDKs
  docs/event-spec/standard-events/common-fields.mdx
Labels: Ready for review

#782 Snap Pixel documentation updates
  docs/assets/event-stream-destinations/snap-pixel-connection-settings.png
  docs/assets/event-stream-destinations/snap-pixel-id.png
  docs/destinations/streaming-destinations/snap-pixel.mdx
Labels: High priority

#784 Minor content updates in Snap Pixel doc
  docs/destinations/streaming-destinations/snap-pixel.mdx
Labels: Good to go!
