Repository rudderlabs/rudderstack-docs, pull requests merged in 2023-01, with the labels that each got.

#1081 JS SDK async load snippet update
  docs/features/transformations/device-mode-transformations.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/quick-start-guide.mdx
  docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-nextjs-integration.mdx
Labels: Good to go!

#1082 Revamped Java SDK documentation
  docs/assets/event-stream-sources/java-sdk-write-key.png
  docs/sources/event-streams/sdks/rudderstack-java-sdk.mdx
Labels: Good to go!

#1084 Go SDK updates
  docs/assets/event-stream-sources/go-sdk-write-key.png
  docs/sources/event-streams/sdks/rudderstack-go-sdk.mdx
  docs/sources/event-streams/sdks/rudderstack-java-sdk.mdx
Labels: Good to go!

#1083 PHP SDK v2.0.0
  docs/assets/event-stream-sources/php-write-key-new.png
  docs/sources/event-streams/sdks/rudderstack-php-sdk.mdx
Labels: Good to go!

#1080 Update MoEngage Android code snippet
  docs/destinations/streaming-destinations/moengage.mdx
Labels: Good to go!

#1089 ActiveCampaign: Updated reference to find event key
  docs/destinations/streaming-destinations/activecampaign.mdx
Labels: Internal review

#1088 Updated Ruby SDK documentation
  docs/sources/event-streams/sdks/rudderstack-ruby-sdk.mdx
Labels: Good to go!

#1091 Node SDK minor updates
  docs/sources/event-streams/sdks/rudderstack-node-sdk.mdx
Labels: Good to go!

#1092 Pinterest Ads - Added LDP support
  docs/destinations/streaming-destinations/pinterest-ads/pinterest-ads-cloud-mode.mdx
Labels: Good to go!

#1093 Pagerduty destination doc
  docs/assets/event-stream-destinations/integration-key-pagerduty.png
  docs/destinations/streaming-destinations/pagerduty.mdx
  src/data/destinations.yaml
  src/sidebar.js
Labels: Good to go!

#1098 PagerDuty source doc
  docs/assets/event-stream-sources/pagerduty-source-webhook.png
  docs/assets/event-stream-sources/pagerduty-source.png
  docs/sources/event-streams/cloud-apps/pagerduty.mdx
  src/data/sources.yaml
  src/sidebar.js
Labels: Good to go!

#1095 Pinterest Ads LDP device mode
  docs/destinations/streaming-destinations/pinterest-ads/pinterest-ads-device-mode.mdx
Labels: Good to go!

#1094 TikTok Ads Offline Events documentation
  docs/assets/event-stream-destinations/tiktok-ads-offline-standard-events.png
  docs/destinations/streaming-destinations/tiktok-ads-offline-events.mdx
  src/data/destinations.yaml
  src/postNavList.js
  src/sidebar.js
Labels: Good to go!

#1099 Olark web device mode documentation
  docs/assets/event-stream-destinations/olark-group-id.png
  docs/assets/event-stream-destinations/olark-track-event-mapping.png
  docs/destinations/streaming-destinations/olark.mdx
  src/data/destinations.yaml
  src/sidebar.js
Labels: Good to go!

#1103 Google Ads doc updates
  docs/destinations/streaming-destinations/google-adwords-enhanced-conversions.mdx
  docs/destinations/streaming-destinations/google-adwords-offline-conversions.mdx
  src/data/destinations.yaml
Labels: Good to go!

#1102 Updated messaging in Tracking Plan docs
  docs/features/data-governance/tracking-plans/index.mdx
Labels: Good to go!

#1096 Impact radius doc
  docs/assets/event-stream-destinations/campaign-id-impact.png
  docs/destinations/streaming-destinations/impact-com.mdx
  src/data/destinations.yaml
  src/sidebar.js
Labels: Good to go!

#1056 Sendinblue destination
  docs/assets/event-stream-destinations/sendinblue-api-key.png
  docs/assets/event-stream-destinations/sendinblue-client-key.png
  docs/assets/event-stream-destinations/sendinblue-doi-template-id.png
  docs/destinations/streaming-destinations/sendinblue/index.mdx
  docs/destinations/streaming-destinations/sendinblue/sendinblue-cloud-mode.mdx
  docs/destinations/streaming-destinations/sendinblue/sendinblue-device-mode.mdx
  docs/destinations/streaming-destinations/sendinblue/setting-up-sendinblue.mdx
  src/data/destinations.yaml
  src/sidebar.js
Labels: Good to go!

#1110 Go SDK doc updates
  docs/sources/event-streams/sdks/rudderstack-go-sdk.mdx
Labels: Good to go!

#1106 Facebook Pixel identify call update
  docs/destinations/streaming-destinations/fb-pixel.mdx
Labels: Good to go!

#1107 iOS SDK updates
  docs/assets/event-stream-sources/spm-dependency-rule-v2.png
  docs/assets/event-stream-sources/spm-dependency-rule.png
  docs/sources/event-streams/sdks/rudderstack-ios-sdk/index.mdx
  docs/sources/event-streams/sdks/rudderstack-ios-sdk/ios-v2.mdx
Labels: Do not merge, Good to go!

#1087 Python transformations doc update
  docs/assets/features/adding-a-library-1.png
  docs/assets/features/adding-a-library-2.png
  docs/assets/features/adding-a-transformation-1.png
  docs/assets/features/adding-a-transformation-2.png
  docs/assets/features/adding-transformation-existing-destination-1.png
  docs/assets/features/adding-transformation-existing-destination-2.png
  docs/assets/features/libraries-in-transformations.png
  docs/features/transformations/cloud-mode-transformations.mdx
  docs/features/transformations/device-mode-transformations.mdx
  docs/features/transformations/faq.mdx
  docs/features/transformations/index.mdx
  docs/features/transformations/using-libraries.mdx
  src/sidebar.js
Labels: Good to go!

#1108 Added load option in JS SDK
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
Labels: Good to go!

#1112 Braze documentation updates
  docs/destinations/streaming-destinations/braze.mdx
Labels: Good to go!

#1109 Discord destination doc
  docs/destinations/streaming-destinations/discord.mdx
  src/data/destinations.yaml
  src/sidebar.js
Labels: Good to go!

#1097 Flutter SDK updates
  docs/sources/event-streams/sdks/rudderstack-flutter-sdk/flutter-v2.mdx
Labels: Good to go!

#1115 Added device mode related FAQ
  docs/destinations/rudderstack-connection-modes.mdx
Labels: Good to go!

#1114 e-commerce »» ecommerce
  docs/destinations/streaming-destinations/adobe-analytics/adobe-analytics-web-device-mode.mdx
  docs/destinations/streaming-destinations/attentive-tag.mdx
  docs/destinations/streaming-destinations/clevertap.mdx
  docs/destinations/streaming-destinations/fb-pixel.mdx
  docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-cloud-mode.mdx
  docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-device-mode.mdx
  docs/destinations/streaming-destinations/google-analytics-ga.mdx
  docs/destinations/streaming-destinations/iterable/iterable-cloud-mode.mdx
  docs/destinations/streaming-destinations/ometria.mdx
  docs/destinations/streaming-destinations/pinterest-ads/pinterest-ads-cloud-mode.mdx
  docs/destinations/streaming-destinations/pinterest-ads/pinterest-ads-device-mode.mdx
  docs/event-spec/ecommerce-events-spec/index.mdx
  docs/event-spec/ecommerce-events-spec/ordering.mdx
  docs/event-spec/standard-events/track.mdx
  docs/sources/event-streams/sdks/rudderstack-javascript-sdk/supported-api.mdx
  src/sidebar.js
Labels: Review in progress

#1118 Removed FAQ from TikTok ads doc
  docs/destinations/streaming-destinations/tiktok-ads.mdx
Labels: Good to go!

#1116 GA4 settings update
  docs/destinations/streaming-destinations/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
Labels: Good to go!

#1119 Ecommerce field calculations
  docs/event-spec/ecommerce-events-spec/ordering.mdx
Labels: Good to go!

#1120 Update common-fields.mdx
  docs/event-spec/standard-events/common-fields.mdx
Labels: Good to go!

#1117 Auth0 doc update
  docs/sources/event-streams/cloud-apps/auth0.mdx
Labels: Good to go!

#1121 React native SDK updates
  docs/sources/event-streams/sdks/rudderstack-react-native-sdk.mdx
Labels: Good to go!

#1079 Bing ads extract source doc
  docs/assets/cloud-extract-sources/bing-ads-connection-settings-2.png
  docs/assets/cloud-extract-sources/bing-ads-v2-settings.png
  docs/sources/extract/bing-ads-v2.mdx
  docs/sources/extract/bing-ads.mdx
  src/data/sources.yaml
  src/sidebar.js
Labels: Good to go!

#1125 Allowlist IPs update
  src/components/iplist.js
Labels: Ready for review

#1127 Reverted destination docs
  docs/destinations/streaming-destinations/axeptio.mdx
  docs/destinations/streaming-destinations/microsoft-clarity.mdx
  docs/destinations/streaming-destinations/satismeter.mdx
  src/data/destinations.yaml
  src/sidebar.js
Labels: Good to go!

#1111 BigQuery Stream doc update
  docs/assets/event-stream-destinations/bqstream-service-account-4.png
  docs/destinations/streaming-destinations/bigquery-stream.mdx
Labels: Good to go!

#1133 Reverted destinations
  docs/destinations/streaming-destinations/axeptio.mdx
  docs/destinations/streaming-destinations/microsoft-clarity.mdx
  docs/destinations/streaming-destinations/satismeter.mdx
  src/data/destinations.yaml
  src/sidebar.js
Labels: Good to go!

#1134 Rockerbox updates
  docs/destinations/streaming-destinations/rockerbox/setting-up-rockerbox.mdx
Labels: Good to go!

#1140 Added source integration videos
  docs/sources/event-streams/cloud-apps/auth0.mdx
  docs/sources/event-streams/cloud-apps/pagerduty.mdx
  docs/sources/event-streams/cloud-apps/pipedream.mdx
  docs/sources/event-streams/cloud-apps/satismeter.mdx
Labels: Good to go!

#1138 User management update
  docs/assets/rs-cloud/permissions-management-1.png
  docs/dashboard-guides/teammates.mdx
  docs/dashboard-guides/user-management.mdx
  src/sidebar.js
  vercel.json
Labels: Good to go!

#1135 Update session tracking docs
  docs/sources/event-streams/sdks/session-tracking/faq.mdx
  docs/sources/event-streams/sdks/session-tracking/index.mdx
Labels: Good to go!

#1139 S3 permissions update
  docs/user-guides/administrators-guide/bucket-configuration-settings.mdx
Labels: Good to go!
